Repository k0sproject/k0s, pull requests merged in 2020-11, with the labels that each got.

#366 k0s-in-docker
  .github/workflows/release.yml
  Dockerfile
  README.md
  docker-entrypoint.sh
  docs/k0s-in-docker.md
Labels: area/containers, area/packaging, documentation, enhancement

#370 Fix default-config to dump all meta fields too
  pkg/apis/v1beta1/cluster.go
Labels: area/configuration, bug

#369 Add relese process docs
  RELEASE.md
  docs/conformance-testing.md
Labels: documentation

#379 Documentation on the status and scope of the project
  README.md
Labels: documentation

#381 Enable cloud providers for k0s clusters
  cmd/worker.go
  docs/cloud-providers.md
  docs/troubleshooting.md
  pkg/component/worker/kubelet.go
Labels: area/configuration, area/worker, documentation, enhancement

#407 Clarify readme
  README.md
Labels: documentation

#419 Create a "Single Node Quick Start" guide.
  docs/k0s-single-node.md
Labels: documentation

#412 Refactor config doc structure
  docs/configuration.md
Labels: documentation

#458 bugfix: data-dir flag
  cmd/root.go
  cmd/server.go
  cmd/token.go
  inttest/basic/basic_test.go
  inttest/byocri/byocri_test.go
  inttest/common/footloosesuite.go
  inttest/hacontrolplane/hacontrolplane_test.go
  inttest/kine/kine_test.go
  inttest/singlenode/singlenode_test.go
  pkg/component/server/kubeletconfig.go
  pkg/component/server/kubeletconfig_test.go
Labels: area/controlplane, bug
