Repository k0sproject/k0s, pull requests merged in 2020-12, with the labels that each got.

#474 Fix Helm values parsing
  .gitignore
  inttest/addons/addons_test.go
  pkg/apis/helm.k0sproject.io/v1beta1/chart_types.go
  pkg/apis/helm.k0sproject.io/v1beta1/generic_hash.go
Labels: area/controlplane, bug

#478 Install cmd
  .gitignore
  cmd/helpers.go
  cmd/install.go
  cmd/root.go
  cmd/token.go
  cmd/user.go
  internal/util/file.go
  internal/util/users.go
  inttest/common/footloosesuite.go
  inttest/footloose-alpine/Dockerfile
  pkg/apis/v1beta1/cluster.go
  pkg/apis/v1beta1/images.go
  pkg/apis/v1beta1/system.go
  pkg/install/users.go
Labels: enhancement, rel-note

#484 Separate kubeconfig for konnectivity and tighter permissions
  .github/workflows/go.yml
  inttest/basic/basic_test.go
  pkg/component/server/certificates.go
  pkg/component/server/controllermanager.go
  pkg/component/server/konnectivity.go
  pkg/constant/constant.go
Labels: bug

#480 Bump etcd, kine and konnectivity versions
  embedded-bins/Makefile
Labels: area/controlplane, rel-note

#505 Fix join address defaulting
  internal/util/interfaces.go
  pkg/component/worker/kubelet.go
Labels: area/configuration, area/worker, bug

#495 Custom volume plugin dir
  docs/configuration.md
  docs/troubleshooting.md
  pkg/apis/v1beta1/calico.go
  pkg/component/server/calico.go
  pkg/component/server/calico_test.go
  pkg/component/server/kubeletconfig.go
  pkg/component/server/kubeletconfig_test.go
  pkg/component/worker/kubelet.go
  static/gen_manifests.go
  static/manifests/calico/DaemonSet/calico-node.yaml
Labels: area/configuration, area/worker, component/kubelet

#531 Fix metric server manifests location
  cmd/server.go
  pkg/component/server/metricserver.go
Labels: area/controlplane, bug

#550 Add k0s shell completion
  cmd/completion.go
  cmd/install.go
  cmd/kubeconfig.go
  cmd/root.go
  cmd/token.go
  docs/cli/k0s.md
  docs/cli/k0s_completion.md
  docs/create-cluster.md
Labels: enhancement

#477 moved extensions.md from docs/internal/ to docs/. Changed helm examp…
  docs/configuration.md
  docs/extensions.md
Labels: documentation

#562 Always set calico to auto detect iptables backend mode
  docs/internal/upgrading-calico.md
  static/manifests/calico/DaemonSet/calico-node.yaml
Labels: area/network

#527 Config option for external api address
  cmd/server.go
  docs/configuration.md
  internal/util/slice.go
  internal/util/slice_test.go
  pkg/apis/v1beta1/cluster.go
  pkg/apis/v1beta1/cluster_test.go
  pkg/component/server/apiendpointreconciler.go
  pkg/component/server/apiendpointreconciler_test.go
  pkg/component/server/apiserver.go
  pkg/component/server/certificates.go
  pkg/component/server/leaderelector.go
  pkg/kubernetes/client.go
Labels: area/configuration, area/controlplane, documentation, enhancement

#575 Add KillMode=process to systemd unit
  pkg/install/service.go
Labels: area/packaging, area/worker

#588 Fix KillMode=process setting on systemd unit
  pkg/install/service.go
Labels: bug

#589 Backport #588 into release-0.9
  pkg/install/service.go
Labels: backport, bug
