Repository k0sproject/k0s, pull requests merged in 2021-09, with the labels that each got.

#1088 Sonobuoy 0.53.2
  inttest/conformance/README.md
  inttest/conformance/terraform/main.tf
Labels: documentation, chore

#1090 Add documentation for containerd needing apparmor tools
  docs/system-requirements.md
Labels: documentation

#1097 Bump runc to 1.0.2
  embedded-bins/Makefile.variables
Labels: backport/release-1.22

#1105 Allow user to overwrite ANY flags with 'extraArgs'
  .github/workflows/go.yml
  inttest/Makefile.variables
  inttest/extraargs/extraargs_test.go
  pkg/component/controller/apiserver.go
  pkg/component/controller/controllermanager.go
  pkg/component/controller/scheduler.go
Labels: backport/release-1.22

#1108 Update pause image version and improve air-gap test
  inttest/airgap/airgap_test.go
  inttest/common/filetools.go
  pkg/constant/constant_posix.go
Labels: backport/release-1.22

#1110 Document needed kernel configs
  docs/os-deps.md
  docs/system-requirements.md
  mkdocs.yml
Labels: documentation, backport/release-1.22

#1111 Add empty config file for containerd by default
  pkg/component/worker/containerd.go
Labels: bug, area/configuration, component/containerd, backport/release-1.22

#1130 Skip pushing latest docs from 1.21 release branch
  .github/workflows/publish-docs.yml
Labels: bug, documentation

#1124 Prettify config YAML validation errors
  pkg/apis/v1beta1/calico.go
  pkg/apis/v1beta1/cluster.go
  pkg/apis/v1beta1/images.go
  pkg/apis/v1beta1/network.go
  pkg/apis/v1beta1/storage.go
Labels: chore

#1140 Cleanup refactor reset/install
  cmd/reset/reset.go
  internal/pkg/file/file.go
  internal/pkg/file/file_test.go
  pkg/cleanup/bridge_linux.go
  pkg/cleanup/bridge_windows.go
  pkg/cleanup/cleanup_unix.go
  pkg/cleanup/cni.go
  pkg/cleanup/containers.go
  pkg/cleanup/directories.go
  pkg/cleanup/services.go
  pkg/cleanup/users.go
  pkg/install/service.go
  pkg/install/users.go
Labels: chore

#1156 Remove redundant dir.Exist()
  cmd/backup/backup.go
  cmd/restore/restore.go
  internal/pkg/dir/dir.go
  pkg/component/controller/kubeproxy.go
Labels: chore
