Repository k0sproject/k0s, pull requests merged in 2021-12, with the labels that each got.

#1299 Run bundled kubectl and ctr when k0s started via matching symlink
  main.go
Labels: enhancement, area/cli

#1301 Fix some errors being reported twice
  cmd/root.go
Labels: bug, area/cli

#1309 Fix generate-APIClient Makefile target
  Makefile
  hack/client-gen/boilerplate.go.txt
Labels: area/ci, chore

#1323 Update Calico to 3.21.2
  docs/internal/upgrading-calico.md
  pkg/constant/constant_shared.go
  static/manifests/calico/ClusterRole/calico-kube-controllers.yaml
  static/manifests/calico/ClusterRole/calico-node.yaml
  static/manifests/calico/ConfigMap/calico-config.yaml
  static/manifests/calico/CustomResourceDefinition/bgppeers.crd.projectcalico.org.yaml
  static/manifests/calico/CustomResourceDefinition/caliconodestatuses.crd.projectcalico.org.yaml
  static/manifests/calico/CustomResourceDefinition/felixconfigurations.crd.projectcalico.org.yaml
  static/manifests/calico/CustomResourceDefinition/globalnetworkpolicies.crd.projectcalico.org.yaml
  static/manifests/calico/CustomResourceDefinition/ippools.crd.projectcalico.org.yaml
  static/manifests/calico/CustomResourceDefinition/ipreservations.crd.projectcalico.org.yaml
  static/manifests/calico/CustomResourceDefinition/kubecontrollersconfigurations.crd.projectcalico.org.yaml
  static/manifests/calico/CustomResourceDefinition/networkpolicies.crd.projectcalico.org.yaml
  static/manifests/calico/DaemonSet/calico-node.yaml
  static/manifests/calico/Deployment/calico-kube-controllers.yaml
Labels: area/network, component/calico

#1329 Add a dark-themed logo to README.md
  README.md
  docs/img/k0s-logo-full-color-dark.svg
  docs/img/k0s-logo-full-color-light.svg
  docs/img/k0s-logo-full-color.svg
Labels: needs-design, chore

#1337 Version bumps
  embedded-bins/Makefile.variables
Labels: chore, backport/release-1.22

#1336 Fix `APIEndpointReconciler.needsUpdate` boolean negation
  pkg/component/controller/apiendpointreconciler.go
  pkg/component/controller/apiendpointreconciler_test.go
Labels: bug, area/controlplane, backport/release-1.22

#1341 Fix k0s logo url in docs/README.md
  docs/README.md
Labels: bug, documentation

#1348 Fix k0s kubeconfig admin command usage hint
  cmd/kubeconfig/admin.go
  docs/cli/k0s_kubeconfig_admin.md
Labels: chore, area/cli

#1252 Add SingleNode: true/false to k0s status output
  cmd/controller/controller.go
  cmd/status/status.go
  cmd/worker/worker.go
  pkg/install/process.go
Labels: enhancement, area/cli

#1371 Silence not yet readyz errors in inttest
  inttest/common/footloosesuite.go
Labels: chore, area/smoke-tests

#1333 Output logs to stderr, default log level to Warn, add global verbose flag
  cmd/airgap/listimages.go
  cmd/api/api.go
  cmd/backup/backup.go
  cmd/controller/controller.go
  cmd/etcd/list.go
  cmd/kubeconfig/create.go
  cmd/reset/reset.go
  cmd/restore/restore.go
  cmd/root.go
  cmd/token/create.go
  cmd/worker/worker.go
  inttest/cli/cli_test.go
  inttest/common/footloosesuite.go
  inttest/ctr/ctr_test.go
  inttest/hacontrolplane/hacontrolplane_test.go
  main.go
  pkg/backup/config.go
  pkg/backup/filesystem.go
  pkg/cleanup/users.go
  pkg/component/controller/etcd.go
  pkg/component/worker/calico_installer_windows.go
  pkg/component/worker/kubelet.go
  pkg/config/cli.go
  pkg/config/config.go
  pkg/install/service.go
  pkg/leaderelection/lease_pool.go
Labels: enhancement, area/cli

#1379 Modernize the github issue/PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yaml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.yaml
Labels: enhancement, area/ci

#1386 Split command line example and output in docs
  docs/contributors/github_workflow.md
  docs/examples/ansible-playbook.md
  docs/examples/rook-ceph.md
  docs/examples/traefik-ingress.md
  docs/high-availability.md
  docs/k0s-multi-node.md
  docs/manifests.md
  docs/raspberry-pi4.md
  docs/troubleshooting.md
  docs/upgrade.md
  docs/worker-node-config.md
Labels: documentation, chore

#1388 Use github-actions user for marking issues stale
  .github/workflows/stale.yml
Labels: area/ci, chore

#1376 Autogenerate docs/cli during publish-docs CI flow
  .github/workflows/publish-docs.yml
  docs/cli/README.md
  docs/cli/k0s.md
  docs/cli/k0s_api.md
  docs/cli/k0s_completion.md
  docs/cli/k0s_controller.md
  docs/cli/k0s_default-config.md
  docs/cli/k0s_docs.md
  docs/cli/k0s_etcd.md
  docs/cli/k0s_etcd_leave.md
  docs/cli/k0s_etcd_member-list.md
  docs/cli/k0s_install.md
  docs/cli/k0s_install_controller.md
  docs/cli/k0s_install_worker.md
  docs/cli/k0s_kubeconfig.md
  docs/cli/k0s_kubeconfig_admin.md
  docs/cli/k0s_kubeconfig_create.md
  docs/cli/k0s_start.md
  docs/cli/k0s_status.md
  docs/cli/k0s_stop.md
  docs/cli/k0s_token_create.md
  docs/cli/k0s_validate.md
  docs/cli/k0s_validate_config.md
  docs/cli/k0s_version.md
  docs/cli/k0s_worker.md
Labels: documentation, area/ci, area/cli

#1265 Enable the use of kubectl plugins in "k0s kubectl" subcommand
  cmd/kubectl/kubectl.go
  inttest/multicontroller/multicontroller_test.go
Labels: bug, area/cli

#1358 Hide global flags added by embedded kubectl
  cmd/kubectl/kubectl.go
Labels: chore, area/cli
