Repository k0sproject/k0s, pull requests merged in 2021-05, with the labels that each got.

#888 Drop segment fork, use the Extra field in upstream for Direct
  go.mod
  go.sum
  pkg/telemetry/telemetry.go
Labels: area/cli

#884 Controller join cleanup
  cmd/controller/controller.go
  pkg/component/controller/casyncer.go
  pkg/component/controller/etcd.go
Labels: chore

#896 Add k0s start and stop for controlling service state
  cmd/root.go
  cmd/start/start.go
  cmd/stop/stop.go
  docs/cli/k0s.md
  docs/cli/k0s_install.md
  docs/cli/k0s_start.md
  docs/cli/k0s_stop.md
  pkg/install/service.go
Labels: area/cli, enhancement

#903 bump versions for runc, containerd and etcd
  docs/configuration.md
  docs/install.md
  docs/k0s-multi-node.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  inttest/conformance/README.md
  inttest/conformance/terraform/main.tf
  inttest/footloose-alpine/Dockerfile
  pkg/constant/constant_shared.go
  pkg/constant/constant_shared_test.go
Labels: backport

#910 Bump containerd to 1.4.6
  embedded-bins/Makefile.variables
Labels: backport, component/containerd

#912 Fix pod logs check in smokes by always getting a fresh list of pods to find ready pods from
  inttest/common/util.go
  inttest/customports/customports_test.go
Labels: backport/release-1.21, bug

#913 Fix token commands role defaulting
  cmd/token/create.go
  cmd/token/list.go
  cmd/token/token.go
Labels: backport/release-1.21, bug

#918 Use k0s start/stop and sudo in docs examples
  docs/cli/k0s_install_controller.md
  docs/install.md
  docs/k0s-multi-node.md
  docs/k0s-reset.md
  docs/k0s-single-node.md
Labels: documentation

#795 Bump golang to 1.16 for etcd
  embedded-bins/etcd/Dockerfile
Labels: area/etcd, need more info

#937 Configurable mode for kube proxy
  internal/testutil/kube_client.go
  inttest/common/footloosesuite.go
  inttest/dualstack/dualstack_test.go
  pkg/apis/v1beta1/kubeproxy.go
  pkg/apis/v1beta1/network.go
  pkg/apis/v1beta1/network_test.go
  pkg/applier/applier.go
  pkg/applier/applier_test.go
  pkg/applier/manager.go
  pkg/applier/stack.go
  pkg/component/controller/kubeproxy.go
  pkg/component/controller/kuberouter.go
  pkg/component/worker/localproxy.go
  pkg/kubernetes/client.go
Labels: area/configuration, area/controlplane, backport/release-1.21, bug, component/kube-proxy, enhancement
