Repository k0sproject/k0s, pull requests merged in 2021-11, with the labels that each got.

#1238 Don't search for a nologin shell when a user already exists
  pkg/install/users.go
Labels: bug, area/install

#1242 Remove mentions of "helper command" from command help
  cmd/install/controller.go
  cmd/install/install.go
  cmd/install/worker.go
  cmd/reset/reset.go
  cmd/status/status.go
  cmd/validate/validate.go
  docs/cli/k0s.md
  docs/cli/k0s_install.md
  docs/cli/k0s_install_controller.md
  docs/cli/k0s_install_worker.md
  docs/cli/k0s_start.md
  docs/cli/k0s_status.md
  docs/cli/k0s_stop.md
  docs/cli/k0s_validate.md
  docs/cli/k0s_validate_config.md
Labels: chore, area/cli

#1244 Replace ioutil.TempFile with os.CreateTemp
  internal/pkg/file/file.go
Labels: chore

#1246 Give validation errors on unknown config fields
  internal/pkg/strictyaml/strictyaml.go
  internal/pkg/strictyaml/strictyaml_test.go
  pkg/apis/k0s.k0sproject.io/v1beta1/clusterconfig_types.go
  pkg/apis/k0s.k0sproject.io/v1beta1/clusterconfig_types_test.go
Labels: bug, area/configuration, area/cli

#1253 Version bumps
  docs/configuration.md
  embedded-bins/Makefile.variables
  pkg/constant/constant_shared.go
Labels: component/konnectivity, chore, component/kube-router

#1259 Docs: Add emphasis on enabling the dynamic config on every controller
  docs/dynamic-configuration.md
Labels: documentation

#1281 Run smoke-tests using a matrix
  .github/workflows/go.yml
Labels: area/ci, chore

#1282 Remove EMBEDDED_BINS_BUILDMODE=fetch from README
  README.md
Labels: documentation, chore

#1286 Fix konnectivity build image
  embedded-bins/konnectivity/Dockerfile
Labels: area/packaging, component/konnectivity
