Repository k0sproject/k0s, pull requests merged in 2021-06, with the labels that each got.

#954 Add man pages generation to k0s docs subcommand
  cmd/root.go
Labels: area/cli, area/packaging, documentation

#972 Change backup&restore smoke to check kube system level objects only
  inttest/backup/backup_test.go
Labels: area/smoke-tests, backport/release-1.21, bug, chore

#952 Regenerate all k0s managed non-CA certs at k0s startup
  pkg/certificate/manager.go
  pkg/component/controller/certificates.go
Labels: area/controlplane, backport/release-1.21, enhancement
