Repository k0sproject/k0s, pull requests merged in 2021-03, with the labels that each got.

#766 Backport docs to 0.11
  docs/configuration.md
  docs/high-availability.md
  docs/img/k0sctl_deployment.png
  docs/install.md
  docs/k0s-in-docker.md
  docs/k0s-multi-node.md
  docs/k0sctl-install.md
  docs/shell-completion.md
  docs/user-management.md
  mkdocs.yml
Labels: backport, documentation

#768 convert relative file path to absolute
  cmd/install.go
  cmd/root.go
Labels: area/configuration, backport, bug

#778 Don't validate empty config files
  cmd/validate.go
Labels: bug

#798 Fix install commands to also pass any args to service units
  cmd/install.go
Labels: area/cli, bug

#802 Fix konnectivity enablement on api server.
  cmd/controller.go
  go.mod
  go.sum
  inttest/basic/basic_test.go
  inttest/common/util.go
Labels: area/controlplane, bug, component/metrics-server

#801 Reduce amounts of attempts in OCI bundle import
  docs/airgap-install.md
  pkg/component/worker/ocibundle.go
Labels: area/worker

#805 Add readyness check for kube api-server
  inttest/common/footloosesuite.go
  inttest/hacontrolplane/hacontrolplane_test.go
  pkg/component/controller/apiserver.go
Labels: area/controlplane, bug

#811 Backport 800 to 0.12
  inttest/addons/addons_test.go
  inttest/basic/basic_test.go
  inttest/byocri/byocri_test.go
  inttest/common/filetools.go
  inttest/common/footloosesuite.go
  inttest/dualstack/dualstack_test.go
  inttest/footloose-alpine/Dockerfile
  inttest/hacontrolplane/hacontrolplane_test.go
  inttest/install/singlenode_test.go
  inttest/kine/kine_test.go
  inttest/multicontroller/multicontroller_test.go
  inttest/singlenode/singlenode_test.go
Labels: backport

#812 Backport 805 to 0.12
  inttest/common/footloosesuite.go
  inttest/hacontrolplane/hacontrolplane_test.go
  pkg/component/controller/apiserver.go
Labels: backport

#815 Backport 813 to 0.12
  .github/workflows/go.yml
  inttest/common/footloosesuite.go
Labels: backport

#784 Refactoring of cobra cmd commands
  cmd/airgap/airgap.go
  cmd/airgap/listimages.go
  cmd/api/api.go
  cmd/api/util.go
  cmd/completion.go
  cmd/controller/controller.go
  cmd/etcd.go
  cmd/etcd/etcd.go
  cmd/etcd/leave.go
  cmd/etcd/list.go
  cmd/install.go
  cmd/install/controller.go
  cmd/install/install.go
  cmd/install/util.go
  cmd/install/worker.go
  cmd/kubeconfig/admin.go
  cmd/kubeconfig/create.go
  cmd/kubeconfig/kubeconfig.go
  cmd/kubectl/kubectl.go
  cmd/reset/reset.go
  cmd/root.go
  cmd/status.go
  cmd/status/status.go
  cmd/token/create.go
  cmd/token/invalidate.go
  cmd/token/list.go
  cmd/token/token.go
  cmd/tokencreate.go
  cmd/validate.go
  cmd/validate/validate.go
  cmd/worker.go
  cmd/worker/worker.go
  internal/util/interfaces.go
  inttest/hacontrolplane/hacontrolplane_test.go
  pkg/component/controller/casyncer.go
  pkg/component/controller/etcd.go
  pkg/component/worker/utils.go
  pkg/config/cli.go
  pkg/config/yaml.go
  pkg/constant/constant_shared.go
  pkg/install/process.go
  pkg/token/joinclient.go
  pkg/token/kubeconfig.go
Labels: area/cli, bug, chore
