Repository k0sproject/k0s, pull requests merged in 2021-02, with the labels that each got.

#671 Fix install variable to be passed as '--key=value'
  Makefile
  cmd/installServer.go
  cmd/installWorker.go
  inttest/Makefile
  inttest/footloose-alpine/Dockerfile
  inttest/install/singlenode_test.go
Labels: area/install, bug

#669 print external LB address in admin kubeconfig
  cmd/kubeconfig.go
Labels: bug

#679 set kubelet cert path under dataDir
  pkg/component/worker/kubelet.go
Labels: bug

#695 fix the path order for k0s components
  pkg/supervisor/supervisor.go
Labels: bug

#697 Fix regression: kubeconfig cmd prints log output
  cmd/kubeconfig.go
Labels: bug

#709 Make config parsing fail when reading invalid or non-existing config
  cmd/helpers.go
  cmd/root.go
  inttest/basic/basic_test.go
  inttest/byocri/byocri_test.go
  inttest/hacontrolplane/hacontrolplane_test.go
Labels: area/cli, area/configuration

#701 Token invalidation
  cmd/token.go
  cmd/tokencreate.go
  cmd/tokeninvalidate.go
  cmd/tokenlist.go
  go.mod
  go.sum
  pkg/token/manager.go
Labels: area/controlplane, area/security, enhancement

#690 Add support for setting node labels is k0s worker command
  cmd/installController.go
  cmd/installWorker.go
  cmd/util.go
  cmd/worker.go
  inttest/basic/basic_test.go
  inttest/common/footloosesuite.go
  pkg/component/worker/kubelet.go
Labels: area/worker, component/kubelet, enhancement

#711 Fix leftover server role references in install command
  cmd/installController.go
  cmd/util.go
Labels: area/cli, area/controlplane, area/install, area/k0sctl, bug

#700 resolve conflict between k0s global flags and kubectl subcommand flags
  cmd/api.go
  cmd/controller.go
  cmd/etcd.go
  cmd/install.go
  cmd/installController.go
  cmd/installWorker.go
  cmd/root.go
  cmd/token.go
  cmd/validate.go
  cmd/worker.go
Labels: bug

#713 More validation for config
  go.mod
  pkg/apis/v1beta1/api.go
  pkg/apis/v1beta1/api_test.go
  pkg/apis/v1beta1/cluster.go
  pkg/apis/v1beta1/network.go
  pkg/apis/v1beta1/network_test.go
  pkg/apis/v1beta1/psp.go
  pkg/apis/v1beta1/psp_test.go
  pkg/apis/v1beta1/storage.go
Labels: area/configuration, area/controlplane

#706 Add tini as init process into k0s container images
  Dockerfile
Labels: area/containers, bug

#708 CSR Approver
  cmd/controller.go
  internal/testutil/kube_client.go
  inttest/basic/basic_test.go
  pkg/component/controller/apiserver.go
  pkg/component/controller/csrapprover.go
  pkg/component/controller/csrapprover_test.go
  pkg/component/controller/kubeletconfig.go
Labels: area/controlplane, area/security, enhancement

#732 More telemetry data
  go.mod
  go.sum
  pkg/telemetry/segment.go
  pkg/telemetry/telemetry.go
Labels: area/controlplane, enhancement

#727 Add ability to pass extra args for kubelet process
  cmd/worker.go
  docs/worker-node-config.md
  internal/util/flags.go
  internal/util/flags_test.go
  internal/util/mapped_args.go
  internal/util/mapped_args_test.go
  inttest/basic/basic_test.go
  inttest/common/footloosesuite.go
  mkdocs.yml
  pkg/component/worker/kubelet.go
Labels: area/cli, area/worker, component/kubelet
