Repository k0sproject/k0s, pull requests merged in 2021-04, with the labels that each got.

#822 Remove global flags from kc subcommand
  cmd/kubectl/kubectl.go
  cmd/root.go
  pkg/config/cli.go
Labels: bug

#826 Use fmt.Errorf everywhere for error handling
  cmd/controller/controller.go
  cmd/kubeconfig/admin.go
  cmd/kubeconfig/create.go
  internal/util/interfaces.go
  internal/util/templatewriter.go
  pkg/apis/v1beta1/cluster.go
  pkg/apis/v1beta1/network.go
  pkg/applier/manager.go
  pkg/applier/stack.go
  pkg/assets/stage.go
  pkg/certificate/manager.go
  pkg/component/controller/apiserver.go
  pkg/component/controller/calico.go
  pkg/component/controller/casyncer.go
  pkg/component/controller/certificates.go
  pkg/component/controller/controllermanager.go
  pkg/component/controller/csrapprover.go
  pkg/component/controller/defaultpsp.go
  pkg/component/controller/etcd.go
  pkg/component/controller/kine.go
  pkg/component/controller/scheduler.go
  pkg/component/controller/systemrbac.go
  pkg/component/worker/kubelet.go
  pkg/component/worker/kubeletconfigclient.go
  pkg/component/worker/utils.go
  pkg/crictl/crictl.go
  pkg/etcd/client.go
  pkg/kubernetes/client.go
  pkg/token/joinclient.go
  pkg/token/kubeconfig.go
Labels: chore

#842 Bump up kube-router to 1.2.1
  pkg/constant/constant_shared.go
Labels: area/network
