Repository k0sproject/k0s, pull requests merged in 2022-08, with the labels that each got.

#1966 [Backport release-1.24] Use a custom GitHub token for checkouts in the backport action
  .github/workflows/backport.yaml
Labels: bug, area/ci, backport/release-1.23

#1925 Bump golangci-lint version to v1.47.2
  hack/tools/Makefile.variables
  pkg/autopilot/controller/updates/updater.go
Labels: chore

#1971 Airgap strict mode documented
  docs/airgap-install.md
Labels: documentation, backport/release-1.24

#1970 Update kine to v0.9.3
  embedded-bins/Makefile.variables
Labels: area/controlplane, chore, backport/release-1.24

#1973 Bump kube-router to v1.5.1
  pkg/constant/constant_shared.go
Labels: area/network, chore, component/kube-router

#1850 Move component.Healthy() into its own interface
  pkg/applier/manager.go
  pkg/component/component.go
  pkg/component/controller/apiendpointreconciler.go
  pkg/component/controller/apiserver.go
  pkg/component/controller/calico.go
  pkg/component/controller/clusterConfig.go
  pkg/component/controller/controllermanager.go
  pkg/component/controller/controllersleasecounter.go
  pkg/component/controller/coredns.go
  pkg/component/controller/crd.go
  pkg/component/controller/csrapprover.go
  pkg/component/controller/defaultpsp.go
  pkg/component/controller/dummyleaderelector.go
  pkg/component/controller/etcd.go
  pkg/component/controller/extensions_controller.go
  pkg/component/controller/k0scloudprovider.go
  pkg/component/controller/k0scloudprovider_test.go
  pkg/component/controller/k0scontrolapi.go
  pkg/component/controller/kine.go
  pkg/component/controller/konnectivity.go
  pkg/component/controller/kubeletconfig.go
  pkg/component/controller/kubeproxy.go
  pkg/component/controller/kuberouter.go
  pkg/component/controller/leaderelector.go
  pkg/component/controller/metrics.go
  pkg/component/controller/metricserver.go
  pkg/component/controller/noderole.go
  pkg/component/controller/scheduler.go
  pkg/component/controller/systemrbac.go
  pkg/component/controller/tunneledapiendpointreconciller.go
  pkg/component/manager.go
  pkg/component/status/status.go
  pkg/component/worker/containerd.go
  pkg/component/worker/kubelet.go
  pkg/component/worker/ocibundle.go
  pkg/component/worker/static_pods.go
  pkg/component/worker/static_pods_test.go
  pkg/component/worker/stubs.go
  pkg/telemetry/component.go
Labels: chore

#1978 Bump golangci-lint version to v1.47.3
  hack/tools/Makefile.variables
Labels: area/ci, chore

#1969 Cache airgap image bundle in all builds
  .github/workflows/go.yml
  .github/workflows/release.yml
  .gitignore
  Makefile
  hack/image-bundler/Dockerfile
  hack/image-bundler/bundler.sh
  image-bundle/.gitignore
  image-bundle/Makefile
  image-bundle/bundler.sh
  inttest/Makefile
  inttest/airgap/airgap_test.go
  inttest/ap-airgap/airgap_test.go
  inttest/autopilot/common/footloosesuite.go
  inttest/common/footloosesuite.go
Labels: bug, area/ci, backport/release-1.24

#1980 Bump Go to v1.18.5
  embedded-bins/Makefile.variables
Labels: chore, backport/release-1.24

#1981 [release-1.23] Bump Go to v1.17.13
  embedded-bins/Makefile.variables
Labels: chore

#1979 Bump konnectivity to 0.0.32-k01
  embedded-bins/Makefile.variables
  pkg/constant/constant_shared.go
Labels: backport/release-1.24

#1994 Fix the release version of docs for mermaid.
  docs/requirements.txt
  docs/requirements_release.txt
Labels: documentation, backport/release-1.24

#1997 Actually leverage image bundle caching on ARM CIs
  .github/workflows/go.yml
Labels: bug, area/ci, backport/release-1.24

#1999 Use the OSS version of `mkdocs-material`
  .github/dependabot.yml
  .github/workflows/publish-docs-manual.yml
  .github/workflows/publish-docs.yml
  docs/requirements.txt
  docs/requirements_release.txt
Labels: documentation, backport/release-1.24

#2015 [Backport release-1.24] Fix GitHub release workflow
  .github/workflows/release.yml
  Makefile
  go.mod
  pkg/constant/constant_shared_test.go
Labels: bug, area/ci

#2023 Bring back supervised process logging
  pkg/supervisor/supervisor.go
Labels: bug, backport/release-1.24

#2020 Bump golangci-lint version to v1.48.0
  hack/tools/Makefile.variables
Labels: chore

#2016 Bump containerd to v1.6.8
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/worker, chore, component/containerd, backport/release-1.24

#2025 Build smoke test matrix from Makefile variable
  .github/workflows/go.yml
Labels: area/ci

#2018 [release-1.23] Use fixed golangci-lint version in workflow
  .github/workflows/lint.yaml
Labels: bug, area/ci

#2012 Add new workflow to build docs
  .github/workflows/build-docs.yml
  .github/workflows/publish-docs-manual.yml
  .github/workflows/publish-docs.yml
  docs/.gitignore
  docs/requirements.txt
  mkdocs.yml
Labels: documentation, area/ci

#2036 Remove mkdocs-git-revision-date-localized-plugin
  .github/workflows/build-docs.yml
  .github/workflows/publish-docs-manual.yml
  .github/workflows/publish-docs.yml
  Makefile
  docs/Dockerfile.serve-dev
  docs/Makefile
  docs/requirements.txt
Labels: documentation, enhancement

#1992 Bump cri-dockerd to v0.2.5
  inttest/byocri/byocri_test.go
  inttest/footloose-alpine/Dockerfile
Labels: chore, area/smoke-tests

#2042 Use "object name safe" hostnames for leases and autopilot
  inttest/Makefile.variables
  inttest/capitalhostnames/capitalhostnames_test.go
  pkg/autopilot/common/hostname.go
  pkg/component/controller/controllersleasecounter.go
Labels: bug, area/controlplane, component/konnectivity, backport/release-1.22, backport/release-1.23, backport/release-1.24

#2035 Fix kine/SQLite database open mode
  pkg/apis/k0s.k0sproject.io/v1beta1/storage.go
  pkg/apis/k0s.k0sproject.io/v1beta1/storage_test.go
Labels: bug, backport/release-1.24

#2049 Fix spelling of GitHub
  .github/workflows/check-network.yaml
  README.md
  RELEASE.md
  docs/README.md
  docs/contributors/github_workflow.md
  docs/contributors/overview.md
Labels: documentation, chore

#2050 Move Dockerfile args down to where they are used
  embedded-bins/Makefile
  embedded-bins/containerd/Dockerfile
  embedded-bins/etcd/Dockerfile
  embedded-bins/iptables/Dockerfile
  embedded-bins/kine/Dockerfile
  embedded-bins/konnectivity/Dockerfile
  embedded-bins/kubernetes/Dockerfile
  embedded-bins/kubernetes/Dockerfile.windows
  embedded-bins/runc/Dockerfile
Labels: chore

#2048 [Backport release-1.23] Use "object name safe" hostnames for leases
  inttest/Makefile.variables
  inttest/capitalhostnames/capitalhostnames_test.go
  pkg/component/controller/controllersleasecounter.go
Labels: bug, area/controlplane, component/konnectivity, backport/release-1.22

#2052 Use GNU Make 3.81 as baseline
  Makefile
  README.md
  docs/contributors/github_workflow.md
  docs/contributors/overview.md
  docs/contributors/testing.md
  inttest/Makefile
Labels: documentation

#2055 Add tests for the gen-bindata auxiliary program
  .gitignore
  Makefile
  hack/gen-bindata/cmd/main.go
  hack/gen-bindata/gen_bindata.go
  hack/gen-bindata/gen_bindata_test.go
  hack/validate-images/main.go
Labels: chore

#2066 Rework the Raspberry Pi docs
  docs/architecture.md
  docs/configuration.md
  docs/raspberry-pi4.md
Labels: documentation

#2057 [Backport release-1.22] Use "object name safe" hostnames for leases
  inttest/Makefile.variables
  inttest/capitalhostnames/capitalhostnames_test.go
  pkg/component/controller/controllersleasecounter.go
Labels: bug, area/controlplane, component/konnectivity

#2072 [Backport release-1.23] Add capitalhostnames inttest to test matrix
  .github/workflows/go.yml
Labels: bug, area/ci, area/smoke-tests, backport/release-1.22

#2074 Let Dependabot ignore the Kubernetes Go dependency
  .github/dependabot.yml
Labels: chore

#2051 Bump libseccomp to v2.5.4
  embedded-bins/runc/Dockerfile
Labels: area/containers, chore, component/containerd, backport/release-1.24

#2076 [Backport release-1.22] Add capitalhostnames inttest to test matrix
  .github/workflows/go.yml
  inttest/capitalhostnames/capitalhostnames_test.go
Labels: bug, area/ci, area/smoke-tests

#2079 Bump iptables to v1.8.8
  embedded-bins/Makefile
  embedded-bins/Makefile.variables
  embedded-bins/iptables/Dockerfile
  embedded-bins/iptables/revert-fix-eth-alen.patch
  embedded-bins/iptables/use-uint-instead-of-u_int.patch
Labels: chore, backport/release-1.24

#2078 [Backport release-1.24] Bump libseccomp to v2.5.4
  embedded-bins/runc/Dockerfile
Labels: area/containers, chore, component/containerd, backport/release-1.23

#2080 [release-1.23] Pin apiextensions-apiserver
  go.mod
  go.sum
Labels: chore

#2095 [release-1.23] Bump CoreDNS to 1.7.1
  pkg/constant/constant_shared.go
Labels: area/network, chore, backport/release-1.22

#2102 [release-1.22] Ensure all k8s modules have the right version
  go.mod
  go.sum
Labels: chore

#2094 [Backport release-1.23] Bump iptables to v1.8.8
  embedded-bins/Makefile
  embedded-bins/Makefile.variables
  embedded-bins/iptables/Dockerfile
  embedded-bins/iptables/revert-fix-eth-alen.patch
  embedded-bins/iptables/use-uint-instead-of-u_int.patch
  embedded-bins/kubernetes/Dockerfile
Labels: chore

#2099 [release-1.23] Bump go 1.18.5
  .github/workflows/check-network.yaml
  .github/workflows/go.yml
  .github/workflows/lint.yaml
  .github/workflows/publish-docs-manual.yml
  .github/workflows/publish-docs.yml
  .github/workflows/release.yml
  Makefile
  build/Dockerfile
  embedded-bins/Makefile.variables
  embedded-bins/containerd/Dockerfile
  embedded-bins/etcd/Dockerfile
  embedded-bins/kine/Dockerfile
  embedded-bins/konnectivity/Dockerfile
  embedded-bins/kubernetes/Dockerfile
  embedded-bins/runc/Dockerfile
  hack/ci-deps/go.mod
  hack/ci-deps/go.sum
Labels: chore, backport/release-1.22

#2107 Bump golangci-lint to v1.49.0
  .github/workflows/lint.yaml
  Makefile
  hack/tools/Makefile.variables
Labels: chore

#2109 Bump runc to 1.1.4
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: chore, backport/release-1.22, backport/release-1.23, backport/release-1.24
