Repository k0sproject/k0s, pull requests merged in 2022-04, with the labels that each got.

#1639 Refactor sysinfo CLI reporter
  cmd/sysinfo/sysinfo.go
  cmd/sysinfo/sysinfo_test.go
Labels: chore

#1632 upgrade calico to v3.22.1
  pkg/constant/constant_shared.go
  static/manifests/calico/CustomResourceDefinition/ippools.crd.projectcalico.org.yaml
Labels: chore, backlog/candidate, component/calico

#1626 [Docs] Cgroups v2 with Docker Desktop
  docs/k0s-in-docker.md
Labels: documentation

#1564 Revise local docs testing setup
  .github/workflows/publish-docs-manual.yml
  .github/workflows/publish-docs.yml
  Makefile
  docs/.dockerignore
  docs/.gitignore
  docs/Dockerfile.serve-dev
  docs/Makefile
  docs/Makefile.variables
  docs/contributors/testing.md
  docs/docker-compose.yml
  docs/internal/publishing_docs_using_mkdocs.md
Labels: area/ci

#1649 Don't log same error twice
  cmd/controller/controller.go
  cmd/worker/worker.go
Labels: chore

#1653 Bump etcd 3.5.4
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: chore, backport/release-1.22, backport/release-1.23

#1655 Release 1.23 version bumps
  docs/configuration.md
  docs/install.md
  docs/k0s-multi-node.md
  docs/releases.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  inttest/conformance/README.md
  pkg/constant/constant_shared.go
Labels: security fix, chore

#1652 Dependabot enabled
  .github/dependabot.yml
Labels: area/ci, chore

#1656 Release 1.22 version bumps
  .gitignore
  docs/configuration.md
  docs/install.md
  docs/releases.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  inttest/conformance/README.md
  pkg/constant/constant_shared.go
Labels: chore

#1657 Add docs to Component interfaces
  pkg/component/component.go
Labels: documentation

#1658 Bump kubernetes 1.21.12
  cmd/backup/backup.go
  cmd/restore/restore.go
  docs/airgap-install.md
  docs/configuration.md
  docs/install.md
  docs/k0s-multi-node.md
  docs/reset.md
  docs/upgrade.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  inttest/common/footloosesuite.go
  inttest/conformance/README.md
  inttest/conformance/terraform/main.tf
  inttest/footloose-alpine/Dockerfile
  inttest/sonobuoy/signetwork_test.go
  pkg/backup/etcd.go
  pkg/constant/constant_shared.go
Labels: chore

#1664 Some sysprobe fixes for cgroups
  internal/pkg/sysinfo/host_linux.go
  internal/pkg/sysinfo/probes/linux/cgroup_v2.go
  internal/pkg/sysinfo/probes/linux/cgroups.go
Labels: bug
