Repository k0sproject/k0s, pull requests merged in 2022-06, with the labels that each got.

#1777 Improve kubectl kubeconfig detection
  cmd/kubectl/kubectl.go
Labels: bug, area/cli

#1637 Add component to provision static pod manifests
  docs/configuration.md
  pkg/apis/k0s.k0sproject.io/v1beta1/workerprofile.go
  pkg/apis/k0s.k0sproject.io/v1beta1/workerprofile_test.go
  pkg/component/worker/static_pods.go
  pkg/component/worker/static_pods_test.go
Labels: enhancement, component/kubelet

#1781 First start watching bundle dir, then list/add existing dirs
  pkg/applier/manager.go
Labels: bug, area/controlplane, backport/release-1.21, backport/release-1.22, backport/release-1.23

#1785 [release-1.23] First start watching bundle dir, then list/add existing dirs
  pkg/applier/manager.go
Labels: bug, area/controlplane

#1681 Remove unused Reconcile() methods from components
  cmd/controller/controller.go
  pkg/applier/manager.go
  pkg/component/controller/apiserver.go
  pkg/component/controller/controllersleasecounter.go
  pkg/component/controller/csrapprover.go
  pkg/component/controller/dummyleaderelector.go
  pkg/component/controller/etcd.go
  pkg/component/controller/k0scloudprovider.go
  pkg/component/controller/k0scontrolapi.go
  pkg/component/controller/kine.go
  pkg/component/controller/leaderelector.go
  pkg/component/controller/systemrbac.go
  pkg/component/manager_test.go
  pkg/component/status/status.go
  pkg/component/worker/calico_installer_windows.go
  pkg/component/worker/containerd.go
  pkg/component/worker/kubelet.go
  pkg/component/worker/kubeproxy_windows.go
  pkg/component/worker/ocibundle.go
  pkg/component/worker/stubs.go
Labels: chore

#1798 Bump containerd to v1.6.6
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: component/containerd, area/security, backport/release-1.23

#1801 [release-1.23] Refactor k0sctl inttest
  .github/workflows/go.yml
  go.mod
  go.sum
  inttest/k0sctl/k0sctl_test.go
Labels: area/smoke-tests

#1805 Fix single node config loading to force use of kine if no storage config is given in partial config
  inttest/singlenode/singlenode_test.go
  pkg/apis/k0s.k0sproject.io/v1beta1/clusterconfig_types.go
  pkg/config/config_test.go
Labels: bug, area/configuration, backport/release-1.22, backport/release-1.23

#1659 Restore --debug flag functionality
  Makefile
  cmd/api/api.go
  cmd/controller/controller.go
  cmd/etcd/etcd.go
  cmd/kubectl/kubectl.go
  cmd/root.go
  cmd/token/create.go
  cmd/worker/worker.go
  go.mod
  go.sum
  pkg/config/cli.go
Labels: regression

#1799 [release-1.23] Bump containerd to v1.5.13
  docs/external-runtime-deps.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: component/containerd, area/security, backport/release-1.22

#1803 [release-1.22] Bump containerd to v1.5.13
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: component/containerd, area/security

#1808 [release-1.23] Restore --debug flag functionality
  Makefile
  cmd/api/api.go
  cmd/controller/controller.go
  cmd/etcd/etcd.go
  cmd/kubectl/kubectl.go
  cmd/root.go
  cmd/token/create.go
  cmd/worker/worker.go
  go.mod
  go.sum
  pkg/config/cli.go
Labels: regression

#1820 Remove latest alias from docs
  .github/workflows/publish-docs-manual.yml
  .github/workflows/publish-docs.yml
Labels: bug, area/ci, backport/release-1.23

#1821 [release-1.23] Remove latest alias from docs
  .github/workflows/publish-docs-manual.yml
  .github/workflows/publish-docs.yml
Labels: bug, area/ci

#1827 [release-1.21] Fix formatting errors according to golangci-lint
  pkg/backup/filesystem.go
  pkg/backup/manager.go
  pkg/backup/sqlitedb.go
  pkg/backup/util.go
Labels: bug, area/ci

#1829 Some fixes for conformance terraform
  .github/workflows/check-network.yaml
  .github/workflows/release.yml
  inttest/Makefile
  inttest/conformance/terraform/.gitignore
  inttest/conformance/terraform/main.tf
  inttest/terraform/test-cluster/controller.tf
  inttest/terraform/test-cluster/main.tf
  inttest/terraform/test-cluster/variables.tf
  inttest/terraform/test-cluster/worker.tf
Labels: backport/release-1.22, backport/release-1.23

#1788 Replace applier's init method with lazyInit
  pkg/applier/applier.go
Labels: chore

#1835 Remove "Update Default Documentation Version" workflow
  .github/workflows/mkdocs-set-default-version.yml
Labels: area/ci, chore

#1864 Bump Kubernetes to v1.24.2
  docs/configuration.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  pkg/constant/constant_shared.go
Labels: chore

#1865 [release-1.23] Bump Kubernetes to v1.23.8
  docs/configuration.md
  docs/install.md
  docs/k0s-multi-node.md
  docs/releases.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  inttest/conformance/README.md
  pkg/constant/constant_shared.go
Labels: chore

#1866 [release-1.22] Bump Kubernetes to v1.22.11
  docs/configuration.md
  docs/install.md
  docs/releases.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  inttest/conformance/README.md
  pkg/constant/constant_shared.go
Labels: chore

#1867 [release-1.21] Bump Kubernetes to v1.21.14
  docs/configuration.md
  docs/install.md
  docs/k0s-multi-node.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  inttest/conformance/README.md
  inttest/conformance/terraform/main.tf
  inttest/footloose-alpine/Dockerfile
  inttest/sonobuoy/signetwork_test.go
  pkg/constant/constant_shared.go
Labels: chore

#1885 Fixups for release workflow
  .github/workflows/release.yml
  image-bundle/Makefile
  image-bundle/bundler.sh
Labels: bug, area/ci, chore
