Repository k0sproject/k0s, pull requests merged in 2022-05, with the labels that each got.

#1667 Bump Kine to 0.9.1
  embedded-bins/Makefile.variables
Labels: chore

#1673 Declare static package
  static/static.go
Labels: bug, area/ci

#1665 Remove quoting when parsing flags for service unit files
  cmd/install/util.go
  inttest/cli/cli_test.go
  inttest/common/footloosesuite.go
  pkg/install/linux_openrc.go
Labels: backport/release-1.22, backport/release-1.23

#1690 Bump containerd 1.6.4
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: chore, component/containerd, dependencies

#1668 Update GitHub actions to current major versions
  .github/dependabot.yml
  .github/workflows/check-network.yaml
  .github/workflows/commit.yaml
  .github/workflows/docs.yml
  .github/workflows/go.yml
  .github/workflows/lint.yaml
  .github/workflows/mkdocs-set-default-version.yml
  .github/workflows/publish-docs-manual.yml
  .github/workflows/publish-docs.yml
  .github/workflows/release.yml
  .github/workflows/stale.yml
Labels: enhancement, area/ci

#1689 Unify interface checks
  pkg/component/controller/apiendpointreconciler.go
  pkg/component/controller/calico.go
  pkg/component/controller/controllermanager.go
  pkg/component/controller/coredns.go
  pkg/component/controller/crd.go
  pkg/component/controller/defaultpsp.go
  pkg/component/controller/extensions_controller.go
  pkg/component/controller/konnectivity.go
  pkg/component/controller/kubeletconfig.go
  pkg/component/controller/kubeproxy.go
  pkg/component/controller/kuberouter.go
  pkg/component/controller/metrics.go
  pkg/component/controller/metricserver.go
  pkg/component/controller/scheduler.go
  pkg/config/config.go
  pkg/container/runtime/cri.go
  pkg/container/runtime/docker.go
  pkg/telemetry/component.go
Labels: chore

#1672 Replace yaml library, use sigs backed library
  cmd/status/status.go
  go.mod
  internal/pkg/strictyaml/strictyaml.go
  inttest/addons/addons_test.go
  inttest/common/footloosesuite.go
  inttest/k0sctl/k0sctl_test.go
  pkg/apis/helm.k0sproject.io/v1beta1/chart_types.go
  pkg/apis/helm.k0sproject.io/v1beta1/generic_hash.go
  pkg/component/controller/calico_test.go
  pkg/component/controller/kubeletconfig.go
  pkg/component/controller/kubeletconfig_test.go
  pkg/helm/helm.go
Labels: chore

#1691 Fix go mod tidy
  .github/workflows/lint.yaml
  Makefile
  go.mod
  go.sum
Labels: bug, dependencies

#1666 Bump go 1.18.1
  .github/workflows/check-network.yaml
  .github/workflows/lint.yaml
  .github/workflows/release.yml
  Makefile
  build/Dockerfile
  build/go.mod
  embedded-bins/Makefile.variables
  embedded-bins/containerd/Dockerfile
  embedded-bins/etcd/Dockerfile
  embedded-bins/kine/Dockerfile
  embedded-bins/konnectivity/Dockerfile
  embedded-bins/kubernetes/Dockerfile
  embedded-bins/kubernetes/Dockerfile.windows
  embedded-bins/runc/Dockerfile
  go.mod
  go.sum
  hack/ci-deps/go.mod
  hack/ci-deps/go.sum
Labels: enhancement

#1696 Fix total memory detection on ARM
  .github/workflows/go.yml
  Makefile
  internal/pkg/sysinfo/probes/linux/linux.go
  internal/pkg/sysinfo/probes/linux/linux_test.go
  internal/pkg/sysinfo/probes/linux/types.go
  internal/pkg/sysinfo/probes/linux/types_arm.go
  internal/pkg/sysinfo/probes/memory_linux.go
  internal/pkg/sysinfo/probes/memory_linux_test.go
Labels: bug

#1701 Bump Kubernetes to 1.24.0
  docs/configuration.md
  docs/install.md
  docs/k0s-in-docker.md
  docs/k0s-multi-node.md
  docs/raspberry-pi4.md
  docs/releases.md
  docs/worker-node-config.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/ci-deps/go.mod
  hack/ci-deps/go.sum
  inttest/conformance/README.md
  inttest/upgrade/upgrade_test.go
  pkg/constant/constant_shared.go
Labels: enhancement, dependencies

#1709 Fix k0s Check Network GitHub workflow
  .github/workflows/check-network.yaml
Labels: bug, area/ci

#1710 Add missing dependencies for golangci-lint
  hack/ci-deps/go.mod
  hack/ci-deps/go.sum
Labels: bug, area/ci

#1711 Also lint tests
  .golangci.yml
  internal/pkg/sysinfo/probes/linux/cgroups_test.go
  internal/pkg/sysinfo/probes/linux/kernel_test.go
  internal/pkg/sysinfo/probes/util_test.go
  inttest/addons/addons_test.go
  inttest/dualstack/dualstack_test.go
  inttest/hacontrolplane/hacontrolplane_test.go
  inttest/k0sctl/k0sctl_test.go
  inttest/kubectl/kubectl_test.go
  inttest/noderole/noderole_single_test.go
  pkg/component/controller/calico_test.go
  pkg/config/config_test.go
Labels: area/ci

#1712 Bump Calico to 3.23.0
  pkg/constant/constant_shared.go
Labels: component/calico

#1715 Check for being the leader before creating the cluster config
  pkg/component/controller/clusterConfig.go
Labels: bug, area/controlplane

#1717 Bump runc to v1.1.2
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/security, backport/release-1.22, backport/release-1.23, dependencies

#1718 Bump Go to 1.18.2
  embedded-bins/Makefile.variables
Labels: area/security

#1722 [release-1.22] Bump runc to v1.1.2
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/security

#1730 Use test temp dir instead of system temp dir in tests
  cmd/kubeconfig/kubeconfig_test.go
  internal/pkg/dir/dir_test.go
  internal/pkg/file/file_test.go
  pkg/applier/applier_test.go
Labels: bug

#1734 Bump Calico to v3.23.1
  pkg/constant/constant_shared.go
Labels: component/calico

#1735 [release-1.23] Bump Calico to v3.21.5
  pkg/constant/constant_shared.go
Labels: component/calico

#1736 [release-1.22] Bump Calico to v3.18.6
  pkg/constant/constant_shared.go
Labels: component/calico

#1740 Bump Helm to v3.9.0
  go.mod
  go.sum
Labels: area/helm

#1724 Remove error return value when stopping the ConfigSource
  cmd/controller/controller.go
  pkg/component/controller/clusterconfig/apiconfigsource.go
  pkg/component/controller/clusterconfig/configsource.go
  pkg/component/controller/clusterconfig/staticsource.go
Labels: chore

#1723 Inline cluster reconcilers
  cmd/controller/controller.go
  pkg/component/controller/calico.go
  pkg/component/controller/calico_test.go
  pkg/component/controller/defaultpsp.go
  pkg/component/controller/kubeletconfig.go
  pkg/component/controller/kubeletconfig_test.go
  pkg/component/controller/kubeproxy.go
  pkg/component/controller/kuberouter.go
  pkg/component/controller/kuberouter_test.go
  pkg/component/controller/metrics.go
  pkg/component/controller/metricserver.go
  pkg/component/controller/metricserver_test.go
  pkg/component/controller/noderole.go
  pkg/component/controller/systemrbac.go
Labels: chore

#1744 Use temp directories provided by testing.T
  cmd/kubeconfig/kubeconfig_test.go
  internal/testutil/runtime_config.go
  pkg/config/config_test.go
  pkg/constant/constant_shared.go
Labels: bug, area/ci

#1640 Refactor sysinfo probes
  internal/pkg/sysinfo/probes/disk.go
  internal/pkg/sysinfo/probes/disk_linux.go
  internal/pkg/sysinfo/probes/disk_other.go
  internal/pkg/sysinfo/probes/linux/cgroup_controllers.go
  internal/pkg/sysinfo/probes/linux/cgroups.go
  internal/pkg/sysinfo/probes/linux/kernel.go
  internal/pkg/sysinfo/probes/linux/kernel_test.go
  internal/pkg/sysinfo/probes/linux/linux.go
  internal/pkg/sysinfo/probes/linux/linux_test.go
  internal/pkg/sysinfo/probes/machineid.go
  internal/pkg/sysinfo/probes/memory.go
  internal/pkg/sysinfo/probes/probes.go
  internal/pkg/sysinfo/sysinfo.go
Labels: chore, area/cli

#1748 Bump konnectivity to 0.0.31-k0s
  embedded-bins/Makefile.variables
  pkg/constant/constant_shared.go
Labels: backport/release-1.21, backport/release-1.22, backport/release-1.23

#1754 [release-1.21] Use footloose fork to fix use of cgroupv2 for inttests
  go.mod
  go.sum
Labels: area/ci

#1660 Remove global data-dir flag
  cmd/kubectl/kubectl.go
  cmd/root.go
  inttest/byocri/byocri_test.go
  inttest/common/footloosesuite.go
Labels: area/cli

#1771 Bump latest k0s version to v1.23.6+k0s.2
  docs/install.md
  docs/k0s-in-docker.md
  docs/k0s-multi-node.md
  docs/raspberry-pi4.md
  docs/releases.md
  docs/worker-node-config.md
  inttest/conformance/README.md
  inttest/upgrade/upgrade_test.go
Labels: documentation, chore
