Repository k0sproject/k0s, pull requests merged in 2022-03, with the labels that each got.

#1574 Replace hard /bin/true and /bin/false paths in tests with exec.LookPath
  pkg/supervisor/supervisor_test.go
Labels: chore

#1573 Containerd 1.5.10 and go 1.17.8 updates
  docs/external-runtime-deps.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  inttest/conformance/README.md
Labels: component/containerd, backport, backport/release-1.23

#1578 Bring back docs version selector
  mkdocs.yml
Labels: documentation

#1580 Makefile tweaks
  Makefile
Labels: area/ci

#1579 Update docs version management logic
  .github/workflows/publish-docs.yml
Labels: documentation, area/ci

#1589 Make docs "main" an alias of "head"
  .github/workflows/publish-docs.yml
Labels: documentation

#1588 Fix docs traefik example link
  docs/examples/nginx-ingress.md
Labels: documentation

#1593 Doc versioning cherrypicks
  .github/workflows/publish-docs.yml
  docs/examples/nginx-ingress.md
Labels: documentation

#1577 Add pre-flight checks and probes module
  .github/workflows/go.yml
  cmd/controller/controller.go
  cmd/sysinfo/sysinfo.go
  cmd/worker/worker.go
  docs/external-runtime-deps.md
  docs/raspberry-pi4.md
  docs/system-requirements.md
  go.mod
  go.sum
  internal/pkg/sysinfo/host_linux.go
  internal/pkg/sysinfo/host_other.go
  internal/pkg/sysinfo/machineid/machineid.go
  internal/pkg/sysinfo/machineid/machineid_test.go
  internal/pkg/sysinfo/probes/disk.go
  internal/pkg/sysinfo/probes/disk_linux.go
  internal/pkg/sysinfo/probes/disk_other.go
  internal/pkg/sysinfo/probes/linux/cgroup_controllers.go
  internal/pkg/sysinfo/probes/linux/cgroup_v1.go
  internal/pkg/sysinfo/probes/linux/cgroup_v2.go
  internal/pkg/sysinfo/probes/linux/cgroups.go
  internal/pkg/sysinfo/probes/linux/cgroups_test.go
  internal/pkg/sysinfo/probes/linux/kernel.go
  internal/pkg/sysinfo/probes/linux/kernel_test.go
  internal/pkg/sysinfo/probes/linux/linux.go
  internal/pkg/sysinfo/probes/linux/linux_test.go
  internal/pkg/sysinfo/probes/linux/types.go
  internal/pkg/sysinfo/probes/linux/types_arm.go
  internal/pkg/sysinfo/probes/machineid.go
  internal/pkg/sysinfo/probes/memory.go
  internal/pkg/sysinfo/probes/memory_linux.go
  internal/pkg/sysinfo/probes/memory_other.go
  internal/pkg/sysinfo/probes/probes.go
  internal/pkg/sysinfo/probes/util.go
  internal/pkg/sysinfo/probes/util_test.go
  internal/pkg/sysinfo/sysinfo.go
  internal/testutil/sysinfo/reporter.go
  inttest/cli/cli_test.go
  inttest/common/footloosesuite.go
  inttest/common/util.go
  pkg/component/controller/konnectivity.go
  pkg/leaderelection/lease_pool.go
  pkg/telemetry/telemetry.go
Labels: documentation, enhancement, area/controlplane, area/worker, area/cli

#1569 Add clusterDomain configuration option
  cmd/controller/certificates.go
  docs/configuration.md
  pkg/apis/k0s.k0sproject.io/v1beta1/network.go
  pkg/apis/k0s.k0sproject.io/v1beta1/network_test.go
  pkg/component/controller/coredns.go
  pkg/component/controller/kubeletconfig.go
  pkg/component/controller/kubeletconfig_test.go
  pkg/component/worker/kubelet.go
  pkg/constant/constant_windows.go
Labels: enhancement, area/configuration

#1606 [release-1.22] Bump containerd to 1.5.11 (CVE-2022-24769)
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: backport/release-1.22, backport/release-1.23

#1609 Bump containerd to 1.5.11 (CVE-2022-24769)
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: component/containerd, backport/release-1.22, backport/release-1.23

#1615 [release-1.21] Bump konnectivity to 0.0.30-k0s
  embedded-bins/Makefile.variables
  pkg/constant/constant_shared.go
Labels: component/konnectivity

#1613 [release-1.23] konnectivity 0.0.30
  embedded-bins/Makefile.variables
  pkg/constant/constant_shared.go
Labels: component/konnectivity

#1619 Improve docs k0sctl airgap installation config example
  docs/airgap-install.md
Labels: documentation

#1620 Pin dependencies for publish docs workflow
  .github/workflows/publish-docs.yml
  docs/requirements_release.txt
Labels: bug, documentation

#1600 Add outdated version warning to docs
  docs/custom_theme/main.html
  mkdocs.yml
Labels: documentation, area/ci
