Repository k0sproject/k0s, pull requests merged in 2022-10, with the labels that each got.

#2230 Use built-in SSH client to wait for SSH connections in inttests
  inttest/common/footloosesuite.go
Labels: chore, area/smoke-tests

#2180 Bump CoreDNS to v1.10.0
  pkg/constant/constant_shared.go
Labels: chore

#2229 Bump cri-dockerd to v0.2.6
  inttest/footloose-alpine/Dockerfile
Labels: chore

#2228 Bump golangci-lint to v1.50.0
  hack/tools/Makefile.variables
Labels: chore

#2195 Add cluster domain to bootstrapping config
  pkg/apis/k0s.k0sproject.io/v1beta1/clusterconfig_types.go
Labels: bug, area/controlplane, backport/release-1.22, backport/release-1.23, backport/release-1.24, backport/release-1.25

#2204 Fix missing pod/container labels
  docs/troubleshooting.md
  inttest/basic/basic_test.go
  inttest/common/util.go
  pkg/component/worker/kubelet.go
Labels: bug, component/containerd, backport/release-1.24, backport/release-1.25

#2235 Use named return values in WriteAtomically
  internal/pkg/file/file.go
  internal/pkg/file/file_test.go
Labels: bug

#2212 Add context to SSH in inttests
  inttest/addons/addons_test.go
  inttest/ap-ha3x3/ha3x3_test.go
  inttest/backup/backup_test.go
  inttest/basic/basic_test.go
  inttest/byocri/byocri_test.go
  inttest/capitalhostnames/capitalhostnames_test.go
  inttest/cli/cli_test.go
  inttest/cnichange/cnichange_test.go
  inttest/common/filetools.go
  inttest/common/footloosesuite.go
  inttest/common/launchdelegate.go
  inttest/common/ssh.go
  inttest/common/vmsuite.go
  inttest/ctr/ctr_test.go
  inttest/customdomain/customdomain_test.go
  inttest/customports/customports_test.go
  inttest/disabledcomponents/disabled_components_test.go
  inttest/dualstack/dualstack_test.go
  inttest/externaletcd/external_etcd_test.go
  inttest/hacontrolplane/hacontrolplane_test.go
  inttest/kine/kine_test.go
  inttest/kubectl/kubectl_test.go
  inttest/kubeletcertrotate/kubeletcertrotate_test.go
  inttest/kuberouter/kuberouter_hairpin_test.go
  inttest/psp/psp_test.go
  inttest/singlenode/singlenode_test.go
  inttest/upgrade/upgrade_test.go
  inttest/workerrestart/workerrestart_test.go
Labels: enhancement, area/smoke-tests

#2241 [release-1.23] Bump Go to v1.18.7 for real
  .github/workflows/check-network.yaml
  .github/workflows/go.yml
  .github/workflows/lint.yaml
  .github/workflows/publish-docs-manual.yml
  .github/workflows/publish-docs.yml
  .github/workflows/release.yml
  Makefile
  build/Dockerfile
  embedded-bins/containerd/Dockerfile
  embedded-bins/etcd/Dockerfile
  embedded-bins/kine/Dockerfile
  embedded-bins/konnectivity/Dockerfile
  embedded-bins/kubernetes/Dockerfile
  embedded-bins/runc/Dockerfile
Labels: chore

#2243 Improve checking of cmline args in dual-stack inttest
  inttest/dualstack/dualstack_test.go
Labels: chore, area/smoke-tests

#2258 Ignore deprecation lints in CI
  .golangci.yml
Labels: chore

#2256 Also lint the hack tools
  .golangci.yml
  hack/gen-bindata/gen_bindata.go
  pkg/component/controller/apiendpointreconciler.go
Labels: chore

#2268 Add depguard linter and forbid usage of gopkg.in/yaml
  .golangci.yml
  go.mod
  pkg/autopilot/updater/client.go
Labels: chore

#2266 [release-1.24] Bump Kubernetes to v1.24.7
  docs/autopilot-multicommand.md
  docs/autopilot.md
  docs/configuration.md
  docs/docker-shim.md
  docs/install.md
  docs/k0s-in-docker.md
  docs/k0s-multi-node.md
  docs/raspberry-pi4.md
  docs/releases.md
  docs/worker-node-config.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  inttest/conformance/README.md
  pkg/constant/constant_shared.go
Labels: chore

#2267 [release-1.23] Bump Kubernetes to v1.23.13
  Makefile
  docs/configuration.md
  docs/install.md
  docs/k0s-multi-node.md
  docs/releases.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  inttest/conformance/README.md
  pkg/constant/constant_shared.go
Labels: chore

#2265 Bump Kubernetes to v1.25.3
  .github/workflows/publish-docs-manual.yml
  Makefile
  docs/airgap-install.md
  docs/autopilot-multicommand.md
  docs/autopilot.md
  docs/configuration.md
  docs/docker-shim.md
  docs/install.md
  docs/k0s-in-docker.md
  docs/k0s-multi-node.md
  docs/raspberry-pi4.md
  docs/releases.md
  docs/reset.md
  docs/upgrade.md
  docs/worker-node-config.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.sum
  inttest/conformance/README.md
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/constant/constant_shared.go
Labels: chore, backport/release-1.25

#2264 Replace set-output with env file in GH Actions
  .github/workflows/check-network.yaml
  .github/workflows/go.yml
  .github/workflows/publish-docs.yml
  .github/workflows/release.yml
Labels: area/ci, chore

#2271 Add footloose-base as prerequisite to update-server
  inttest/Makefile
Labels: bug, area/smoke-tests

#2259 Add some notes in docs about iptables versions and modes
  docs/networking.md
Labels: documentation

#2225 Supervised process cleanup function
  inttest/basic/basic_test.go
  pkg/component/controller/konnectivity.go
  pkg/supervisor/supervisor.go
Labels: backport/release-1.23, backport/release-1.24, backport/release-1.25

#2278 Fix docs build after pip 22.3 update
  .github/workflows/build-docs.yml
  .github/workflows/publish-docs-manual.yml
  .github/workflows/publish-docs.yml
  docs/.dockerignore
  docs/Dockerfile.serve-dev
  docs/Makefile
  docs/requirements.txt
  docs/requirements_pip.txt
  mkdocs.yml
Labels: documentation, area/ci, chore, backport/release-1.25

#2234 Add simple Kubernetes watch facility
  inttest/ap-airgap/airgap_test.go
  inttest/ap-ha3x3/ha3x3_test.go
  inttest/ap-platformselect/platformselect_test.go
  inttest/ap-quorum/quorum_test.go
  inttest/ap-quorumsafety/quorumsafety_test.go
  inttest/ap-selector/selector_test.go
  inttest/ap-single/single_test.go
  inttest/ap-updater/updater_test.go
  inttest/basic/basic_test.go
  inttest/calico/calico_test.go
  inttest/capitalhostnames/capitalhostnames_test.go
  inttest/cli/cli_test.go
  inttest/common/footloosesuite.go
  inttest/common/util.go
  inttest/customdomain/customdomain_test.go
  inttest/customports/customports_test.go
  inttest/defaultstorage/defaultstorage_test.go
  inttest/kubeletcertrotate/kubeletcertrotate_test.go
  inttest/kuberouter/kuberouter_hairpin_test.go
  inttest/metrics/metrics_test.go
  pkg/autopilot/common/waitfor.go
  pkg/component/controller/clusterconfig/apiconfigsource.go
  pkg/kubernetes/watch/apps.go
  pkg/kubernetes/watch/core.go
  pkg/kubernetes/watch/k0s.go
  pkg/kubernetes/watch/watcher.go
Labels: enhancement

#2293 Concurrent logs collection after inttests
  .github/workflows/go.yml
  inttest/common/footloosesuite.go
  inttest/common/launchdelegate.go
Labels: enhancement, area/smoke-tests

#2296 Fix ap-removedapis inttest
  inttest/ap-quorumsafety/quorumsafety_test.go
  inttest/ap-removedapis/removedapis_test.go
Labels: bug, area/smoke-tests

#2307 Reduce docker image size
  .github/workflows/release.yml
  Dockerfile
Labels: backport/release-1.24, backport/release-1.25

#2302 Bump kine to v0.9.6
  embedded-bins/Makefile.variables
Labels: chore, component/kine, backport/release-1.25

#2306 Bump Calico to 3.24.3
  pkg/constant/constant_shared.go
Labels: chore, component/calico, backport/release-1.25

#2304 [release-1.23] Bump containerd to v1.5.14
  docs/external-runtime-deps.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: chore, component/containerd

#2303 Bump containerd to v1.6.9
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: chore, component/containerd, backport/release-1.25

#2305 Bump golangci-lint to v1.50.1
  hack/tools/Makefile.variables
Labels: area/ci, chore

#2270 Write files atomically where appropriate
  cmd/controller/certificates.go
  cmd/controller/controller.go
  cmd/token/preshared.go
  internal/autopilot/pkg/templatewriter/templatewriter.go
  internal/pkg/archive/archive.go
  internal/pkg/file/file.go
  pkg/certificate/manager.go
  pkg/component/controller/etcd.go
  pkg/component/controller/kubeletconfig.go
  pkg/component/worker/calico_installer_windows.go
  pkg/component/worker/containerd.go
  pkg/component/worker/kubelet.go
  pkg/component/worker/utils.go
  pkg/config/cli.go
  pkg/config/file_config.go
Labels: enhancement

#2319 [Backport release-1.25] Bump containerd to v1.6.9
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: chore, component/containerd, backport/release-1.24

#2288 Ability to disable k0s endpoint-reconciler
  cmd/controller/controller.go
  pkg/component/controller/apiserver.go
  pkg/config/cli.go
  pkg/constant/constant_shared.go
Labels: backport/release-1.23, backport/release-1.24, backport/release-1.25

#2322 Use test context everywhere in inttests
  inttest/addons/addons_test.go
  inttest/airgap/airgap_test.go
  inttest/ap-airgap/airgap_test.go
  inttest/ap-ha3x3/ha3x3_test.go
  inttest/ap-platformselect/platformselect_test.go
  inttest/ap-quorum/quorum_test.go
  inttest/ap-quorumsafety/quorumsafety_test.go
  inttest/ap-removedapis/removedapis_test.go
  inttest/ap-selector/selector_test.go
  inttest/ap-single/single_test.go
  inttest/ap-updater/updater_test.go
  inttest/backup/backup_test.go
  inttest/configchange/config_test.go
  inttest/defaultstorage/defaultstorage_test.go
  inttest/dualstack/dualstack_test.go
  inttest/k0scloudprovider/k0scloudprovider_test.go
  inttest/kubeletcertrotate/kubeletcertrotate_test.go
  inttest/metricscraper/metricscraper_test.go
  inttest/noderole-no-taints/noderole_no_taints_test.go
  inttest/noderole-single/noderole_single_test.go
  inttest/noderole/noderole_test.go
  inttest/psp/psp_test.go
  inttest/tunneledkas/suite_test.go
Labels: chore, area/smoke-tests

#2332 Add context to ToolSuite in inttests
  inttest/toolsuite/operations/planapply.go
  inttest/toolsuite/tests/versionupdate_test.go
  inttest/toolsuite/toolsuite.go
Labels: chore, area/smoke-tests

#2335 Bump OpenEBS to v3.3.0
  pkg/constant/constant_shared.go
Labels: chore, storage

#2320 [Backport release-1.24] Bump containerd to v1.6.9
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: chore, component/containerd

#2336 Make autopilot new plan tests more resilient
  pkg/autopilot/controller/plans/cmdprovider/airgapupdate/newplan_test.go
  pkg/autopilot/controller/plans/cmdprovider/k0supdate/newplan_test.go
Labels: chore
