Repository k0sproject/k0s, pull requests merged in 2022-11, with the labels that each got.

#2308 [release-1.24] Bump Calico to v3.23.4
  pkg/constant/constant_shared.go
  static/manifests/calico/DaemonSet/calico-node.yaml
Labels: chore, component/calico

#2333 Use require instead of assert where applicable in tests
  cmd/airgap/listimages_test.go
  cmd/kubeconfig/kubeconfig_test.go
  inttest/addons/addons_test.go
  inttest/airgap/airgap_test.go
  inttest/ap-airgap/airgap_test.go
  inttest/ap-ha3x3/ha3x3_test.go
  inttest/ap-platformselect/platformselect_test.go
  inttest/ap-quorum/quorum_test.go
  inttest/ap-quorumsafety/quorumsafety_test.go
  inttest/ap-removedapis/removedapis_test.go
  inttest/ap-selector/selector_test.go
  inttest/ap-single/single_test.go
  inttest/ap-updater/updater_test.go
  inttest/basic/basic_test.go
  inttest/byocri/byocri_test.go
  inttest/calico/calico_test.go
  inttest/capitalhostnames/capitalhostnames_test.go
  inttest/cli/cli_test.go
  inttest/common/footloosesuite.go
  inttest/configchange/config_test.go
  inttest/ctr/ctr_test.go
  inttest/customca/customca_test.go
  inttest/customdomain/customdomain_test.go
  inttest/defaultstorage/defaultstorage_test.go
  inttest/disabledcomponents/disabled_components_test.go
  inttest/externaletcd/external_etcd_test.go
  inttest/extraargs/extraargs_test.go
  inttest/hacontrolplane/hacontrolplane_test.go
  inttest/k0sctl/k0sctl_test.go
  inttest/kubeletcertrotate/kubeletcertrotate_test.go
  inttest/kuberouter/kuberouter_hairpin_test.go
  inttest/metrics/metrics_test.go
  inttest/multicontroller/multicontroller_test.go
  inttest/noderole-no-taints/noderole_no_taints_test.go
  inttest/noderole-single/noderole_single_test.go
  inttest/noderole/noderole_test.go
  inttest/psp/psp_test.go
  inttest/statussocket/statussocket_test.go
  inttest/tunneledkas/suite_test.go
  inttest/upgrade/upgrade_test.go
  inttest/workerrestart/workerrestart_test.go
  pkg/apis/k0s.k0sproject.io/v1beta1/network_test.go
Labels: chore, area/smoke-tests

#2343 Bump golang to 1.18.8
  embedded-bins/Makefile.variables
Labels: chore, area/security, backport/release-1.23

#2347 Bump sonobuoy to v0.56.11
  inttest/Makefile
Labels: chore, area/smoke-tests

#2342 Bump Go to v1.19.3
  embedded-bins/Makefile.variables
Labels: chore, area/security, backport/release-1.25

#2348 Pin some GH workflows to the k0s repository
  .github/workflows/check-network.yaml
  .github/workflows/go.yml
  .github/workflows/publish-docs.yml
Labels: area/ci, chore

#2351 Watcher with error callback
  inttest/common/footloosesuite.go
  inttest/common/util.go
  pkg/autopilot/common/waitfor.go
  pkg/component/controller/clusterconfig/apiconfigsource.go
  pkg/kubernetes/watch/watcher.go
  pkg/kubernetes/watch/watcher_test.go
Labels: enhancement

#2355 Bump Calico to 3.24.3
  docs/configuration.md
  pkg/constant/constant_shared.go
Labels: chore, component/calico, backport/release-1.25

#2337 Unify make prerequisites and gen-bindata args for static assets
  .gitignore
  Makefile
  static/doc.go
Labels: chore

#2359 [release-1.24] Bump Calico to v3.23.5
  pkg/constant/constant_shared.go
Labels: chore, component/calico

#2360 [Backport release-1.25] Bump Calico to v3.24.4
  docs/configuration.md
  pkg/constant/constant_shared.go
Labels: chore, component/calico

#2251 Fix dualstack config propagation in dynamic config mode
  inttest/Makefile
  inttest/Makefile.variables
  inttest/dualstack/dualstack_test.go
  pkg/apis/k0s.k0sproject.io/v1beta1/clusterconfig_types.go
Labels: backport/release-1.25

#2379 Fix list rendering in docs/contributors/testing.md
  docs/contributors/testing.md
Labels: documentation

#2386 Bump Calico to v3.24.5
  docs/configuration.md
  pkg/constant/constant_shared.go
Labels: bug, area/network, component/calico, backport/release-1.25

#2389 [release-1.24] Bump Kubernetes to v1.24.8
  docs/autopilot-multicommand.md
  docs/autopilot.md
  docs/configuration.md
  docs/docker-shim.md
  docs/install.md
  docs/k0s-in-docker.md
  docs/k0s-multi-node.md
  docs/raspberry-pi4.md
  docs/releases.md
  docs/worker-node-config.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  inttest/conformance/README.md
  pkg/constant/constant_shared.go
Labels: security fix

#2394 [release-1.23] Bump Kubernetes to v1.23.14
  docs/configuration.md
  docs/install.md
  docs/k0s-multi-node.md
  docs/releases.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  inttest/conformance/README.md
  pkg/constant/constant_shared.go
Labels: security fix

#2388 Bump Kubernetes to v1.25.4
  .github/workflows/publish-docs-manual.yml
  docs/airgap-install.md
  docs/autopilot-multicommand.md
  docs/autopilot.md
  docs/configuration.md
  docs/docker-shim.md
  docs/install.md
  docs/k0s-in-docker.md
  docs/k0s-multi-node.md
  docs/raspberry-pi4.md
  docs/releases.md
  docs/reset.md
  docs/upgrade.md
  docs/worker-node-config.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  inttest/conformance/README.md
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/constant/constant_shared.go
Labels: security fix, backport/release-1.25

#2390 [release-1.22] Bump kubernetes 1.22.16
  docs/configuration.md
  docs/install.md
  docs/releases.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  inttest/conformance/README.md
  inttest/footloose-alpine/Dockerfile
  pkg/constant/constant_shared.go
Labels: security fix

#2401 Select OpenRC launch mode for upgrade inttest
  inttest/upgrade/upgrade_test.go
Labels: bug, area/smoke-tests

#2402 [Backport release-1.25] Bump Kubernetes to v1.25.4
  .github/workflows/publish-docs-manual.yml
  docs/airgap-install.md
  docs/autopilot-multicommand.md
  docs/autopilot.md
  docs/configuration.md
  docs/docker-shim.md
  docs/install.md
  docs/k0s-in-docker.md
  docs/k0s-multi-node.md
  docs/raspberry-pi4.md
  docs/releases.md
  docs/reset.md
  docs/upgrade.md
  docs/worker-node-config.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  inttest/conformance/README.md
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/constant/constant_shared.go
Labels: security fix

#2407 [Backport release-1.25] Switch from k8s.gcr.io to registry.k8s.io
  cmd/airgap/listimages_test.go
  docs/configuration.md
  docs/docker-shim.md
  docs/raspberry-pi4.md
  inttest/airgap/airgap_test.go
  inttest/psp/psp_test.go
  pkg/constant/constant_posix.go
  pkg/constant/constant_shared.go
Labels: chore, backport/release-1.24

#2408 [Backport release-1.24] Switch from k8s.gcr.io to registry.k8s.io
  cmd/airgap/listimages_test.go
  docs/configuration.md
  docs/docker-shim.md
  inttest/airgap/airgap_test.go
  inttest/psp/psp_test.go
  pkg/constant/constant_posix.go
  pkg/constant/constant_shared.go
Labels: chore, backport/release-1.23

#2409 [Backport release-1.23] Switch from k8s.gcr.io to registry.k8s.io
  cmd/airgap/listimages_test.go
  docs/configuration.md
  inttest/airgap/airgap_test.go
  inttest/psp/psp_test.go
  pkg/constant/constant_posix.go
  pkg/constant/constant_shared.go
Labels: chore

#2387 Calico test improvement: added pod-to-pod connectivity check
  inttest/calico/calico_test.go
  inttest/common/pod.go
Labels: area/smoke-tests, backport/release-1.24, backport/release-1.25

#2403 Let the ARM based smoke tests not be fail-fast
  .github/workflows/go.yml
Labels: area/smoke-tests

#2414 Ensure k0s and containerd use identical pause images
  go.mod
  go.sum
  inttest/basic/basic_test.go
Labels: area/containers, component/containerd, area/smoke-tests

#2412 Use iptables to airgap the airgap inttest
  inttest/airgap/airgap_test.go
  inttest/common/airgap.go
Labels: bug, area/smoke-tests

#2374 Let k0s exchange the kubelet bootstrap kubeconfig
  cmd/worker/worker.go
  inttest/Makefile.variables
  inttest/hostnameoverride/hostnameoverride_test.go
  pkg/component/worker/kubelet.go
  pkg/component/worker/utils.go
  pkg/constant/constant_shared.go
Labels: enhancement, area/worker

#2435 Bump containerd to v1.6.10
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/network, chore, component/containerd, backport/release-1.25

#2437 [Backport release-1.25] Bump containerd to v1.6.10
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/network, chore, component/containerd, backport/release-1.24

#2422 Add unstructured and metadata utils to manifest applier
  pkg/applier/applier.go
  pkg/applier/meta.go
  pkg/applier/stack.go
  pkg/applier/stackapplier.go
  pkg/applier/unstructured.go
Labels: enhancement

#2446 [Backport release-1.24] Bump containerd to v1.6.10
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/network, chore, component/containerd

#2376 Don't create the test network if it already exists
  inttest/ap-airgap/airgap_test.go
  inttest/ap-ha3x3/ha3x3_test.go
  inttest/ap-quorum/quorum_test.go
  inttest/ap-quorumsafety/quorumsafety_test.go
  inttest/ap-selector/selector_test.go
  inttest/common/footloosesuite.go
  inttest/kubeletcertrotate/kubeletcertrotate_test.go
Labels: chore, area/smoke-tests

#2457 Bump metrics-server to v0.6.2
  docs/configuration.md
  docs/raspberry-pi4.md
  pkg/constant/constant_shared.go
Labels: chore, component/metrics-server
