Repository k0sproject/k0s, pull requests merged in 2022-12, with the labels that each got.

#2451 Manage Alpine version via Makefile variables
  .github/workflows/release.yml
  Dockerfile
  Makefile
  docs/Makefile
  embedded-bins/Makefile.variables
  hack/image-bundler/Dockerfile
  inttest/Makefile
  inttest/calico/calico_test.go
  inttest/footloose-alpine/Dockerfile
Labels: chore

#2474 Introduce Normalize method for controller options
  cmd/controller/controller.go
  docs/configuration.md
  pkg/config/cli.go
  pkg/config/cli_test.go
Labels: area/cli

#2468 Fix k0s restore location
  internal/pkg/dir/dir.go
  internal/pkg/dir/dir_test.go
  inttest/backup/backup_test.go
  pkg/backup/filesystem.go
Labels: bug, area/backup, backport/release-1.25

#2478 Fix copy-paste error: ControllerManager vs. Storage
  pkg/apis/k0s.k0sproject.io/v1beta1/clusterconfig_types.go
Labels: bug, backport/release-1.25

#2488 Bump containerD to 1.6.12
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: component/containerd, backport/release-1.24, backport/release-1.25

#2502 Fix autopilot doc
  .github/workflows/channel.yaml.tpl
  docs/autopilot.md
  examples/autopilot/updateconfig.yaml
Labels: backport/release-1.24, backport/release-1.25

#2501 Change the yaml format in the generated edge_release file
  .github/workflows/channel.yaml.tpl
Labels: backport/release-1.25

#2489 [release-1.23] Bump containerD to 1.5.16
  docs/external-runtime-deps.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: component/containerd, area/security

#2516 Document container-selinux requirement for selinux
  docs/selinux.md
Labels: documentation

#2428 Enhanced config CRD validation
  inttest/basic/basic_test.go
  pkg/apis/k0s.k0sproject.io/v1beta1/api.go
  pkg/apis/k0s.k0sproject.io/v1beta1/api_test.go
  pkg/apis/k0s.k0sproject.io/v1beta1/clusterconfig_types.go
  pkg/apis/k0s.k0sproject.io/v1beta1/clusterconfig_types_test.go
  pkg/apis/k0s.k0sproject.io/v1beta1/images.go
  pkg/apis/k0s.k0sproject.io/v1beta1/konnectivity.go
  pkg/apis/k0s.k0sproject.io/v1beta1/network.go
  pkg/apis/k0s.k0sproject.io/v1beta1/network_test.go
  pkg/apis/k0s.k0sproject.io/v1beta1/storage.go
  pkg/component/controller/calico_test.go
  pkg/component/controller/clusterConfig.go
  pkg/component/controller/konnectivity.go
  pkg/component/controller/kuberouter_test.go
  pkg/component/controller/metricserver_test.go
  pkg/config/config_test.go
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: area/configuration

#2504 UpdateConfig treatment improvements
  docs/autopilot.md
  inttest/ap-updater/updater_test.go
  pkg/apis/autopilot.k0sproject.io/v1beta2/updateconfig.go
  pkg/apis/autopilot.k0sproject.io/v1beta2/zz_generated.deepcopy.go
  pkg/autopilot/controller/updates/updater.go
  static/manifests/autopilot/CustomResourceDefinition/autopilot.k0sproject.io_updateconfigs.yaml
Labels: backport/release-1.24, backport/release-1.25

#2522 k0s binary path detection for autopilot
  inttest/ap-single/single_test.go
  pkg/autopilot/controller/signal/k0s/apply.go
  pkg/autopilot/controller/signal/k0s/download.go
  pkg/autopilot/controller/signal/k0s/init.go
Labels: backport/release-1.25

#2523 [Backport release-1.23] Fix k0s restore location
  internal/pkg/dir/dir.go
  internal/pkg/dir/dir_test.go
  inttest/backup/backup_test.go
  pkg/backup/filesystem.go
Labels: bug, backport/release-1.22, area/backup

#2525 [Backport release-1.25] Calico test improved: added pod-to-pod connectivity check
  inttest/calico/calico_test.go
  inttest/common/pod.go
Labels: area/smoke-tests, backport/release-1.24

#2527 [Backport release-1.22] Fix k0s restore location
  internal/pkg/dir/dir.go
  inttest/backup/backup_test.go
  pkg/backup/filesystem.go
Labels: bug, area/backup

#2425 Replace kubelet-config with worker-config component
  cmd/api/api.go
  cmd/controller/controller.go
  cmd/worker/worker.go
  docs/configuration.md
  docs/worker-node-config.md
  inttest/disabledcomponents/disabled_components_test.go
  pkg/component/controller/clusterConfig.go
  pkg/component/controller/kubeletconfig.go
  pkg/component/controller/kubeletconfig_test.go
  pkg/component/controller/workerconfig/reconciler.go
  pkg/component/controller/workerconfig/reconciler_test.go
  pkg/component/controller/workerconfig/snapshot.go
  pkg/component/worker/config/config.go
  pkg/component/worker/config/config_test.go
  pkg/component/worker/config/loader.go
  pkg/component/worker/config/loader_test.go
  pkg/component/worker/kubelet.go
  pkg/component/worker/kubeletconfigclient.go
  pkg/component/worker/utils.go
  pkg/config/cli.go
  pkg/config/cli_test.go
  pkg/config/file_config.go
  pkg/constant/constant_shared.go
  pkg/kubernetes/client.go
  pkg/token/manager.go
Labels: enhancement, area/configuration

#2536 Bump containerd to 1.6.14
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: chore, backport/release-1.24, backport/release-1.25

#2538 Bump cri-dockerd to v0.3.0
  inttest/Makefile.variables
  inttest/footloose-alpine/Dockerfile
Labels: chore, area/smoke-tests

#2539 [Backport release-1.25] Bump containerd to 1.6.14
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: chore, component/containerd

#2540 [Backport release-1.24] Bump containerd to 1.6.14
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: chore, component/containerd

#2534 Disable konnectivity agent control plane proxy if not used
  pkg/component/controller/konnectivity.go
Labels: area/worker, component/konnectivity

#2531 Bump konnectivity to 0.0.33-k0s
  docs/configuration.md
  embedded-bins/Makefile.variables
  pkg/constant/constant_shared.go
Labels: chore, backport/release-1.22, backport/release-1.23, backport/release-1.24, backport/release-1.25

#2545 Remove hashes from pip files
  .github/workflows/build-docs.yml
  .github/workflows/publish-docs-manual.yml
  .github/workflows/publish-docs.yml
  docs/Dockerfile.serve-dev
  docs/Makefile
  docs/requirements.txt
  docs/requirements_pip.txt
Labels: chore

#2547 Restore correct auth source precedence for kubelet bootstrapping
  pkg/component/worker/utils.go
Labels: bug
