Repository k0sproject/k0s, pull requests merged in 2022-01, with the labels that each got.

#1407 Update copyright boilerplate year and add CI check
  .github/workflows/lint.yaml
  .golangci.yml
  hack/client-gen/boilerplate.go.txt
Labels: area/ci, chore, lint

#1414 Add filename usage hint to "k0s restore"
  cmd/restore/restore.go
Labels: chore, area/cli, area/backup

#1431 Do not push 1.22 docs as latest or default
  .github/workflows/publish-docs.yml
Labels: documentation, backport/release-1.22

#1429 Use path "-" in backup and restore to write to stdout or read from stdin
  cmd/backup/backup.go
  cmd/restore/restore.go
  internal/pkg/archive/archive.go
  inttest/Makefile
  inttest/backup/backup_test.go
  pkg/backup/config.go
  pkg/backup/manager.go
Labels: enhancement, area/cli, area/backup

#1432 Fix docs push command
  .github/workflows/publish-docs.yml
Labels: documentation, backport/release-1.21

#1439 Fix stdout output of config when using k0s restore --config-out -
  pkg/backup/config.go
Labels: bug, area/backup

#1447 Unmark stale issues and PRs when updated
  .github/workflows/stale.yml
Labels: area/ci

#1465 Fix k0s kubeconfig create usage hint
  cmd/kubeconfig/create.go
Labels: chore, area/cli

#1477 Fix config reconciler success message typo
  pkg/component/controller/clusterConfig.go
Labels: area/configuration, chore
