Repository k0sproject/k0s, pull requests merged in 2022-09, with the labels that each got.

#2128 Remove some functions from stringslice package
  cmd/controller/controller.go
  go.mod
  go.sum
  internal/pkg/stringslice/stringslice.go
  internal/pkg/stringslice/stringslice_test.go
  pkg/applier/stack.go
Labels: chore

#2129 Use Kubernetes API to create Kubelet kubeconfig
  cmd/controller/controller.go
  cmd/token/create.go
  pkg/token/joinencode.go
  pkg/token/kubeconfig.go
  pkg/token/kubeconfig_test.go
Labels: chore

#2138 Fix usage of K0SCTL_VERSION in GitHub release workflows
  .github/workflows/check-network.yaml
  .github/workflows/release.yml
Labels: bug, area/ci

#2140 Also add iptables symlink
  pkg/component/worker/kubelet.go
Labels: bug, area/network, backport/release-1.22, backport/release-1.23, backport/release-1.24

#2127 Fix kine version
  embedded-bins/kine/Dockerfile
Labels: backport/release-1.22, backport/release-1.23, backport/release-1.24

#2160 Bump Kine to v0.9.4
  embedded-bins/Makefile.variables
Labels: chore, backport/release-1.24

#2124 iptables-nft support
  cmd/worker/worker.go
  docs/configuration.md
  docs/worker-node-config.md
  embedded-bins/Makefile
  embedded-bins/Makefile.variables
  embedded-bins/iptables/Dockerfile
  internal/pkg/iptablesutils/iptables.go
  inttest/ap-ha3x3/ha3x3_test.go
  pkg/component/worker/kubelet.go
  pkg/config/cli.go
Labels: backport/release-1.21, backport/release-1.22, backport/release-1.23, backport/release-1.24

#2158 [release-1.24] Bump Kubernetes to v1.24.5
  docs/autopilot-multicommand.md
  docs/configuration.md
  docs/docker-shim.md
  docs/install.md
  docs/k0s-in-docker.md
  docs/k0s-multi-node.md
  docs/raspberry-pi4.md
  docs/releases.md
  docs/worker-node-config.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  inttest/conformance/README.md
  pkg/constant/constant_shared.go
Labels: security fix, chore

#2159 [release-1.23] Bump Kubernetes to v1.23.11
  docs/configuration.md
  docs/install.md
  docs/k0s-multi-node.md
  docs/releases.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  inttest/conformance/README.md
  pkg/constant/constant_shared.go
Labels: security fix, chore

#2167 [release-1.24] Bump Go to v1.18.6
  embedded-bins/Makefile.variables
Labels: chore, backport/release-1.23

#2143 Bump Go to v1.19.1
  embedded-bins/Makefile.variables
Labels: chore

#2142 Bump CoreDNS to v1.9.4
  pkg/constant/constant_shared.go
Labels: area/network, chore

#2168 Bump Kubernetes to 1.25.1
  .github/workflows/publish-docs-manual.yml
  Makefile
  docs/airgap-install.md
  docs/autopilot-multicommand.md
  docs/autopilot.md
  docs/configuration.md
  docs/docker-shim.md
  docs/install.md
  docs/k0s-in-docker.md
  docs/k0s-multi-node.md
  docs/raspberry-pi4.md
  docs/releases.md
  docs/reset.md
  docs/upgrade.md
  docs/worker-node-config.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  inttest/conformance/README.md
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/constant/constant_shared.go
Labels: security fix, chore

#2173 Update Go version in go.mod to 1.19
  go.mod
Labels: chore

#2164 Bump etcd binary to v3.5.5
  embedded-bins/Makefile.variables
  pkg/constant/constant_shared_test.go
Labels: chore, backport/release-1.24

#2175 [Backport release-1.23] Bump etcd binary to v3.5.5
  embedded-bins/Makefile.variables
  pkg/constant/constant_shared_test.go
Labels: chore, backport/release-1.22

#2176 [Backport release-1.22] Bump etcd binary to v3.5.5
  embedded-bins/Makefile.variables
  pkg/constant/constant_shared_test.go
Labels: chore

#2191 Rename public `CmdOpts` to private `commands`
  cmd/airgap/listimages.go
  cmd/api/api.go
  cmd/backup/backup.go
  cmd/backup/backup_windows.go
  cmd/config/config.go
  cmd/config/edit.go
  cmd/config/status.go
  cmd/config/validate.go
  cmd/controller/controller.go
  cmd/ctr/ctr.go
  cmd/etcd/etcd.go
  cmd/etcd/leave.go
  cmd/etcd/list.go
  cmd/install/controller.go
  cmd/install/install.go
  cmd/install/worker.go
  cmd/kubeconfig/admin.go
  cmd/kubeconfig/create.go
  cmd/kubeconfig/kubeconfig.go
  cmd/kubeconfig/kubeconfig_test.go
  cmd/kubectl/kubectl.go
  cmd/reset/reset.go
  cmd/restore/restore.go
  cmd/restore/restore_windows.go
  cmd/root.go
  cmd/start/start.go
  cmd/status/status.go
  cmd/stop/stop.go
  cmd/token/create.go
  cmd/token/invalidate.go
  cmd/token/list.go
  cmd/token/token.go
  cmd/validate/validate.go
  cmd/version/version.go
  cmd/worker/worker.go
  go.mod
  inttest/common/footloosesuite.go
  pkg/component/controller/kuberouter.go
  pkg/config/cli.go
  pkg/container/runtime/docker.go
Labels: chore

#2189 Don't load cluster config automatically
  cmd/airgap/listimages.go
  cmd/controller/controller.go
  cmd/etcd/etcd.go
  cmd/worker/worker.go
  pkg/config/cli.go
Labels: bug

#2201 Early logging configuration
  cmd/api/api.go
  cmd/controller/controller.go
  cmd/root.go
  cmd/worker/worker.go
Labels: bug

#2210 Remove old Autopilot FootlooseSuite
  inttest/autopilot/common/filetools.go
  inttest/autopilot/common/footloosesuite.go
Labels: chore, area/smoke-tests

#2211 Refactor launch delegate into its own file
  inttest/common/footloosesuite.go
  inttest/common/launchdelegate.go
  inttest/k0scloudprovider/k0scloudprovider_test.go
Labels: chore, area/smoke-tests

#2206 Use stdout provided by Cobra
  cmd/airgap/listimages.go
  cmd/api/api.go
  cmd/backup/backup.go
  cmd/config/create.go
  cmd/etcd/list.go
  cmd/kubeconfig/admin.go
  cmd/kubeconfig/create.go
  cmd/restore/restore.go
  cmd/root.go
  cmd/status/status.go
  cmd/sysinfo/sysinfo.go
  cmd/token/create.go
  cmd/token/invalidate.go
  cmd/token/list.go
  cmd/version/version.go
  main.go
  pkg/backup/config.go
  pkg/backup/manager.go
  pkg/component/worker/kubeproxy_windows.go
Labels: bug

#2205 Fix k0s kubectl --kubeconfig flag
  cmd/kubectl/kubectl.go
Labels: bug, area/cli

#2213 Run noderole inttests separately
  inttest/Makefile
  inttest/Makefile.variables
  inttest/noderole-no-taints/noderole_no_taints_test.go
  inttest/noderole-single/noderole_single_test.go
Labels: chore, area/smoke-tests
