Repository k0sproject/k0s, pull requests merged in 2022-07, with the labels that each got.

#1932 Let Dependabot ignore some Go dependencies
  .github/dependabot.yml
Labels: chore

#1928 [release-1.21] Bump etcd to v3.4.19
  embedded-bins/Makefile.variables
Labels: area/etcd, chore

#1929 [release-1.22] Bump Kubernetes to v1.22.12
  docs/configuration.md
  docs/install.md
  docs/releases.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  inttest/conformance/README.md
  pkg/constant/constant_shared.go
Labels: chore

#1931 Bump Kubernetes to v1.24.3
  docs/autopilot-multicommand.md
  docs/autopilot.md
  docs/configuration.md
  docs/docker-shim.md
  docs/install.md
  docs/k0s-in-docker.md
  docs/k0s-multi-node.md
  docs/raspberry-pi4.md
  docs/releases.md
  embedded-bins/Makefile.variables
  examples/autopilot/plan.yaml
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  inttest/autopilot/common/defaults.go
  inttest/common/defaults.go
  inttest/conformance/README.md
  inttest/upgrade/upgrade_test.go
  pkg/autopilot/controller/plans/cmdprovider/airgapupdate/schedulable_test.go
  pkg/autopilot/controller/plans/cmdprovider/k0supdate/schedulable_test.go
  pkg/autopilot/controller/signal/airgap/signal_test.go
  pkg/autopilot/controller/signal/k0s/apply_test.go
  pkg/autopilot/controller/signal/k0s/signal_test.go
  pkg/constant/constant_shared.go
Labels: chore

#1930 [release-1.23] Bump Kubernetes to v1.23.9
  docs/configuration.md
  docs/install.md
  docs/k0s-multi-node.md
  docs/releases.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  inttest/conformance/README.md
  pkg/constant/constant_shared.go
Labels: chore

#1941 [release-1.23] Bump Go to v1.17.12
  embedded-bins/Makefile.variables
Labels: chore, area/security

#1940 Bump Go to v1.18.4
  embedded-bins/Makefile.variables
Labels: chore, area/security

#1950 [release-1.23] Bump Calico to v3.21.6
  pkg/constant/constant_shared.go
Labels: chore, component/calico

#1958 fix(docs): feature gates are of type bool
  docs/configuration.md
Labels: documentation

#1957 Use a custom GitHub token in the backport action
  .github/workflows/backport.yaml
Labels: bug, area/ci, backport/release-1.24

#1960 [Backport release-1.24] Use a custom GitHub token in the backport action
  .github/workflows/backport.yaml
Labels: bug, area/ci, backport/release-1.23

#1897 Bump Calico to v3.23.3
  pkg/constant/constant_shared.go
  static/manifests/calico/ClusterRole/calico-node.yaml
Labels: chore, component/calico, backport/release-1.24

#1963 Use a custom GitHub token for checkouts in the backport action
  .github/workflows/backport.yaml
Labels: bug, area/ci, backport/release-1.24

#1961 [Backport release-1.23] Use a custom GitHub token in the backport action
  .github/workflows/backport.yaml
Labels: bug, area/ci, backport/release-1.22
