Repository k0sproject/k0s, pull requests merged in 2023-03, with the labels that each got.

#2813 [Backport release-1.25] Fix external address reconciliation w.r.t. dynamic config
  cmd/controller/controller.go
  inttest/Makefile
  inttest/Makefile.variables
  inttest/customports/customports_test.go
  pkg/component/controller/apiendpointreconciler.go
  pkg/component/controller/apiendpointreconciler_test.go
  pkg/component/controller/tunneledapiendpointreconciller.go
Labels: bug, area/controlplane, backport/release-1.24

#2827 [Backport release-1.25] Bump go-sqlite3 to v1.14.16
  go.mod
  go.sum
Labels: security fix, chore, dependencies, backport/release-1.24

#2820 Sync tool dependency versions with k0s
  hack/tool/go.mod
  hack/tool/go.sum
Labels: chore

#2825 [release-1.24] Bump Kubernetes to v1.24.11
  docs/autopilot-multicommand.md
  docs/autopilot.md
  docs/configuration.md
  docs/docker-shim.md
  docs/install.md
  docs/k0s-in-docker.md
  docs/k0s-multi-node.md
  docs/raspberry-pi4.md
  docs/releases.md
  docs/worker-node-config.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  inttest/conformance/README.md
  pkg/constant/constant_shared.go
Labels: chore

#2824 [release-1.25] Bump Kubernetes to v1.25.7
  .github/workflows/publish-docs-manual.yml
  docs/airgap-install.md
  docs/autopilot-multicommand.md
  docs/autopilot.md
  docs/configuration.md
  docs/docker-shim.md
  docs/install.md
  docs/k0s-in-docker.md
  docs/k0s-multi-node.md
  docs/raspberry-pi4.md
  docs/releases.md
  docs/reset.md
  docs/upgrade.md
  docs/worker-node-config.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  inttest/conformance/README.md
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/constant/constant_shared.go
Labels: chore

#2826 [release-1.23] Bump Kubernetes to v1.23.17
  .github/workflows/release.yml
  docs/configuration.md
  docs/install.md
  docs/k0s-multi-node.md
  docs/releases.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  inttest/conformance/README.md
  pkg/constant/constant_shared.go
Labels: chore

#2823 Bump Kubernetes to v1.26.2
  .github/workflows/publish-docs-manual.yml
  docs/autopilot.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/conformance/README.md
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/constant/constant_shared.go
Labels: chore, backport/release-1.26

#2832 [Backport release-1.26] Bump Kubernetes to v1.26.2
  .github/workflows/publish-docs-manual.yml
  docs/autopilot.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/conformance/README.md
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/constant/constant_shared.go
Labels: chore

#2834 Fix docker build-context creation in release
  .github/workflows/release.yml
Labels: backport/release-1.23, backport/release-1.24, backport/release-1.25, backport/release-1.26

#2848 Remove unneeded steps from lint CI workflow
  .github/workflows/lint.yaml
Labels: area/ci, chore

#2850 TLS server configuration hardening
  cmd/api/api.go
  pkg/component/controller/apiserver.go
  pkg/component/controller/etcd.go
  pkg/component/controller/konnectivity.go
  pkg/component/controller/kubeletconfig.go
  pkg/component/controller/workerconfig/reconciler.go
  pkg/component/controller/workerconfig/reconciler_test.go
  pkg/constant/constant_shared.go
  pkg/constant/constant_shared_test.go
Labels: security fix, area/controlplane, backport/release-1.26

#2857 Use `gh` CLI instead of curl/jq when downloading k0s for the docs build
  .github/workflows/build-docs.yml
  .github/workflows/publish-docs-manual.yml
  .github/workflows/publish-docs.yml
  docs/Makefile
  docs/Makefile.variables
Labels: area/ci, chore

#2847 Test Autopilot updates for current and previous k0s minor versions
  .github/workflows/go.yml
  hack/tools/gen-matrix.sh
Labels: area/ci, chore

#2858 [Backport release-1.26] TLS server configuration hardening
  cmd/api/api.go
  pkg/component/controller/apiserver.go
  pkg/component/controller/etcd.go
  pkg/component/controller/konnectivity.go
  pkg/component/controller/kubeletconfig.go
  pkg/component/controller/workerconfig/reconciler.go
  pkg/component/controller/workerconfig/reconciler_test.go
  pkg/constant/constant_shared.go
  pkg/constant/constant_shared_test.go
Labels: security fix, area/controlplane

#2861 [Backport release-1.25] TLS server configuration hardening
  cmd/api/api.go
  pkg/component/controller/apiserver.go
  pkg/component/controller/etcd.go
  pkg/component/controller/konnectivity.go
  pkg/component/controller/kubeletconfig.go
  pkg/constant/constant_shared.go
  pkg/constant/constant_shared_test.go
Labels: security fix, area/controlplane, backport/release-1.24

#2867 Bump go to v1.20.2
  embedded-bins/Makefile.variables
Labels: chore

#2869 [Backport release-1.23] TLS server configuration hardening
  cmd/api/api.go
  go.mod
  go.sum
  pkg/component/controller/apiserver.go
  pkg/component/controller/etcd.go
  pkg/component/controller/konnectivity.go
  pkg/component/controller/kubeletconfig.go
  pkg/constant/constant_shared.go
  pkg/constant/constant_shared_test.go
Labels: security fix, area/controlplane

#2696 [release-1.23] Upgrade GitHub actions to use Node.js 16, pt. 2
  .github/workflows/docs.yml
  .github/workflows/publish-docs-manual.yml
  .github/workflows/publish-docs.yml
Labels: area/ci, chore, Stale

#2874 Make CoreDNS component to use both node config and dynamic config
  cmd/controller/controller.go
  inttest/Makefile.variables
  inttest/custom-cidrs/customcidrs_test.go
  pkg/component/controller/coredns.go
Labels: backport/release-1.24, backport/release-1.25, backport/release-1.26

#2862 Remove docker/libnetwork
  go.mod
  go.sum
  pkg/component/worker/kubelet.go
  pkg/component/worker/kubelet_test.go
Labels: chore

#2901 Use FORCE_HOST_GO=y when building Kubernetes
  embedded-bins/kubernetes/Dockerfile
Labels: chore, backport/release-1.26

#2915 Better error reporting in CSRApprover
  pkg/component/controller/csrapprover.go
Labels: chore

#2810 Don't generate a go-client for resource lists
  pkg/apis/autopilot.k0sproject.io/v1beta2/clientset/typed/autopilot.k0sproject.io/v1beta2/autopilot.k0sproject.io_client.go
  pkg/apis/autopilot.k0sproject.io/v1beta2/clientset/typed/autopilot.k0sproject.io/v1beta2/controlnodelist.go
  pkg/apis/autopilot.k0sproject.io/v1beta2/clientset/typed/autopilot.k0sproject.io/v1beta2/fake/fake_autopilot.k0sproject.io_client.go
  pkg/apis/autopilot.k0sproject.io/v1beta2/clientset/typed/autopilot.k0sproject.io/v1beta2/fake/fake_controlnodelist.go
  pkg/apis/autopilot.k0sproject.io/v1beta2/clientset/typed/autopilot.k0sproject.io/v1beta2/fake/fake_planlist.go
  pkg/apis/autopilot.k0sproject.io/v1beta2/clientset/typed/autopilot.k0sproject.io/v1beta2/fake/fake_updateconfiglist.go
  pkg/apis/autopilot.k0sproject.io/v1beta2/clientset/typed/autopilot.k0sproject.io/v1beta2/generated_expansion.go
  pkg/apis/autopilot.k0sproject.io/v1beta2/clientset/typed/autopilot.k0sproject.io/v1beta2/planlist.go
  pkg/apis/autopilot.k0sproject.io/v1beta2/clientset/typed/autopilot.k0sproject.io/v1beta2/updateconfiglist.go
  pkg/apis/autopilot.k0sproject.io/v1beta2/types.go
  pkg/apis/autopilot.k0sproject.io/v1beta2/updateconfig.go
  pkg/apis/k0s.k0sproject.io/clientset/typed/k0s.k0sproject.io/v1beta1/clusterconfiglist.go
  pkg/apis/k0s.k0sproject.io/clientset/typed/k0s.k0sproject.io/v1beta1/fake/fake_clusterconfiglist.go
  pkg/apis/k0s.k0sproject.io/clientset/typed/k0s.k0sproject.io/v1beta1/fake/fake_k0s.k0sproject.io_client.go
  pkg/apis/k0s.k0sproject.io/clientset/typed/k0s.k0sproject.io/v1beta1/generated_expansion.go
  pkg/apis/k0s.k0sproject.io/clientset/typed/k0s.k0sproject.io/v1beta1/k0s.k0sproject.io_client.go
  pkg/apis/k0s.k0sproject.io/v1beta1/clusterconfig_types.go
Labels: chore

#2844 Bump controller-tools to v0.11.3
  hack/tools/Makefile.variables
  static/manifests/autopilot/CustomResourceDefinition/autopilot.k0sproject.io_controlnodes.yaml
  static/manifests/autopilot/CustomResourceDefinition/autopilot.k0sproject.io_plans.yaml
  static/manifests/autopilot/CustomResourceDefinition/autopilot.k0sproject.io_updateconfigs.yaml
  static/manifests/helm/CustomResourceDefinition/helm.k0sproject.io_charts.yaml
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore

#2845 Deprecate api-config component feature gate
  cmd/controller/controller.go
  pkg/component/controller/clusterConfig.go
  pkg/config/cli.go
  pkg/constant/constant_shared.go
Labels: area/configuration, area/cli

#2936 Bump runc to v1.1.5
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: security fix, area/containers, backport/release-1.24, backport/release-1.25, backport/release-1.26

#2928 Update docs about dockershim removal
  docs/dockershim.md
  docs/runtime.md
  docs/troubleshooting.md
  mkdocs.yml
Labels: documentation, chore

#2943 [Backport release-1.24] Use FORCE_HOST_GO=y when building Kubernetes
  embedded-bins/kubernetes/Dockerfile
Labels: chore

#2918 Kubernetes v1.26.3
  .github/workflows/publish-docs-manual.yml
  docs/autopilot.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/conformance/README.md
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/constant/constant_shared.go
Labels: backport/release-1.26

#2927 [Backport release-1.25] Fix runtime config permissions from 0755 to 0600
  pkg/config/file_config.go
Labels: bug, area/security, backport/release-1.24

#2948 Prevent leaking global flags from dependencies
  .golangci.yml
  cmd/kubectl/kubectl.go
  cmd/root_test.go
  pkg/config/cli.go
  pkg/k0scloudprovider/command.go
  pkg/k0scloudprovider/provider.go
Labels: chore, area/cli

#2955 Use separate buffers for stdout&err in streams for pod exec in smokes
  inttest/common/pod.go
Labels: bug, chore, backport/release-1.25, backport/release-1.26
