Repository k0sproject/k0s, pull requests merged in 2023-12, with the labels that each got.

#3780 Remove the duplicate restClientGetter from the stack applier
  pkg/applier/applier.go
  pkg/kubernetes/rest.go
Labels: area/controlplane, chore

#3789 Bump Go to v1.21.5
  embedded-bins/Makefile.variables
  go.mod
  hack/tool/go.mod
Labels: security fix

#3800 Fix doc configuration.md spec.workerProfiles examples misplaced
  docs/configuration.md
Labels: backport/release-1.26, backport/release-1.27, backport/release-1.28

#3798 Set controller-runtime logger in inttest
  go.mod
  inttest/addons/addons_test.go
Labels: chore, area/smoke-tests

#3756 Bump cri-dockerd to v0.3.8
  inttest/bootloose-alpine/Dockerfile
Labels: chore, area/smoke-tests

#3773 Move K0sUpdateVersion from BootlooseSuite into inttest
  inttest/ap-ha3x3/ha3x3_test.go
  inttest/common/bootloosesuite.go
Labels: chore, area/smoke-tests

#3753 Bump sonobuoy to v0.57.1
  go.mod
  go.sum
  inttest/Makefile.variables
Labels: chore, area/smoke-tests

#3776 Bump kine to v0.11.2
  embedded-bins/Makefile.variables
Labels: area/controlplane, chore, component/kine

#3788 [release-1.28] Bump Go to v1.20.12
  embedded-bins/Makefile.variables
Labels: security fix, backport/release-1.27

#3820 Fix Code of Conduct linking in docs
  .github/workflows/build-docs.yml
  CODE_OF_CONDUCT.md
  docs/CODE_OF_CONDUCT.md
  docs/contributors/CODE_OF_CONDUCT.md
  docs/contributors/overview.md
Labels: bug, documentation, area/ci

#3821 [Backport release-1.27] Bump Go to v1.20.12
  embedded-bins/Makefile.variables
Labels: security fix, backport/release-1.26

#3819 Fix latest -> stable links in Markdown files
  README.md
  docs/FAQ.md
  docs/README.md
Labels: bug, documentation

#3809 Add ControlNode deletion to docs on how to remove a controller node
  docs/remove_controller.md
Labels: documentation, backport/release-1.28

#3797 Assume Helm release has been uninstalled if not found
  inttest/addons/addons_test.go
  pkg/component/controller/extensions_controller.go
  pkg/helm/helm.go
Labels: bug, area/helm

#3790 Remove necessity to suppress NotFound errors in Applier
  inttest/addons/addons_test.go
  pkg/applier/applier.go
  pkg/applier/applier_test.go
Labels: area/controlplane, chore

#3804 [Backport release-1.26] Add DefaultStorageExtension() and test
  pkg/apis/k0s.k0sproject.io/v1beta1/clusterconfig_types.go
  pkg/apis/k0s.k0sproject.io/v1beta1/clusterconfig_types_test.go
  pkg/apis/k0s.k0sproject.io/v1beta1/extensions.go
Labels: bug, area/configuration

#3792 Patch away chart finalizers
  inttest/addons/addons_test.go
  pkg/component/controller/extensions_controller.go
Labels: bug, area/helm

#3835 [Backport release-1.28] Fix CVE-2023-48795
  go.mod
  go.sum
Labels: security fix, backport/release-1.27

#3839 Bump Python to 3.11.7 for docs build
  docs/Makefile.variables
Labels: chore

#3838 Update to Alpine 3.19.0
  Makefile
  embedded-bins/Makefile
  embedded-bins/Makefile.variables
  embedded-bins/kine/Dockerfile
Labels: chore

#3847 Bump cni-node image to 1.3.0-k0s.0
  pkg/constant/constant_shared.go
Labels: chore
