Repository k0sproject/k0s, pull requests merged in 2023-06, with the labels that each got.

#3198 Enhance release&support info on docs
  docs/commercial-support.md
  docs/img/k0s_release_cycle.png
  docs/img/k0s_releases.png
  docs/img/k8s_release_cycle.png
  docs/releases.md
  mkdocs.yml
Labels: documentation, backport/release-1.27

#3220 Bump sonobuoy to v0.56.17
  go.mod
  go.sum
  inttest/Makefile
  inttest/conformance/README.md
Labels: chore, area/smoke-tests

#3213 Bump kubernetes to 1.27.3 (CVE-2023-2728)
  docs/autopilot.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/constant/constant_shared.go
Labels: security fix, backport/release-1.27

#3215 [release-1.24] Bump Kubernetes to v1.24.15
  docs/autopilot-multicommand.md
  docs/autopilot.md
  docs/configuration.md
  docs/docker-shim.md
  docs/install.md
  docs/k0s-in-docker.md
  docs/k0s-multi-node.md
  docs/raspberry-pi4.md
  docs/releases.md
  docs/worker-node-config.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  inttest/conformance/README.md
  pkg/constant/constant_shared.go
Labels: security fix

#3218 [release-1.25] Bump Kubernetes to v1.25.11
  docs/airgap-install.md
  docs/autopilot-multicommand.md
  docs/autopilot.md
  docs/configuration.md
  docs/docker-shim.md
  docs/install.md
  docs/k0s-in-docker.md
  docs/k0s-multi-node.md
  docs/raspberry-pi4.md
  docs/releases.md
  docs/reset.md
  docs/upgrade.md
  docs/worker-node-config.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  inttest/conformance/README.md
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/constant/constant_shared.go
Labels: security fix

#3219 [release-1.26] Bump Kubernetes to v1.26.6
  docs/autopilot.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  inttest/conformance/README.md
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/constant/constant_shared.go
Labels: security fix

#3233 [release-1.27] Bump kubernetes to 1.27.3 (CVE-2023-2728)
  docs/autopilot.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/constant/constant_shared.go
Labels: security fix

#3232 Replace Slack with Lens Forums in the rest of the docs
  README.md
  docs/README.md
  docs/contributors/overview.md
  mkdocs.yml
Labels: documentation, backport/release-1.27

#3226 Clean up embedded-bins stamp files even when Docker fails
  embedded-bins/Makefile
Labels: chore

#3200 [release-1.26] go 1.19.10
  embedded-bins/Makefile.variables
Labels: chore, backport/release-1.25

#3238 Increase golangci-lint timeout
  .golangci.yml
Labels: chore

#3239 [Backport release-1.25] go 1.19.10
  .github/workflows/build-docs.yml
  .github/workflows/release.yml
  Dockerfile
  Makefile
  docs/Makefile
  docs/Makefile.variables
  embedded-bins/Makefile.variables
  hack/image-bundler/Dockerfile
  inttest/Makefile
  inttest/calico/calico_test.go
  inttest/footloose-alpine/Dockerfile
  inttest/footloose-alpine/root/etc/nginx/conf.d
Labels: chore, backport/release-1.24

#3236 [release-1.27] Update to Alpine 3.17.4
  embedded-bins/Makefile.variables
Labels: chore

#3240 [Backport release-1.24] go 1.19.10
  .github/workflows/release.yml
  Dockerfile
  Makefile
  docs/Makefile
  docs/Makefile.variables
  embedded-bins/Makefile.variables
  hack/image-bundler/Dockerfile
  inttest/Makefile
  inttest/calico/calico_test.go
  inttest/footloose-alpine/Dockerfile
  inttest/footloose-alpine/root/etc/nginx/conf.d
Labels: chore
