Repository k0sproject/k0s, pull requests merged in 2023-02, with the labels that each got.

#2647 Add possibility to inject custom telemetry attributes via ConfigMap
  pkg/telemetry/telemetry.go
Labels: backport/release-1.24, backport/release-1.25, backport/release-1.26

#2665 Bump containerd to v1.6.16
  docs/nllb.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: chore, component/containerd, backport/release-1.24, backport/release-1.25, backport/release-1.26

#2667 [release-1.23] Bump containerd to v1.5.17
  docs/external-runtime-deps.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: chore, component/containerd, backport/release-1.22

#2644 Introduce WaitForPlanState helper in AP inttests
  inttest/ap-airgap/airgap_test.go
  inttest/ap-ha3x3/ha3x3_test.go
  inttest/ap-platformselect/platformselect_test.go
  inttest/ap-quorum/quorum_test.go
  inttest/ap-quorumsafety/quorumsafety_test.go
  inttest/ap-removedapis/removedapis_test.go
  inttest/ap-selector/selector_test.go
  inttest/ap-single/single_test.go
  inttest/ap-updater/updater_test.go
  inttest/kubeletcertrotate/kubeletcertrotate_test.go
  inttest/toolsuite/tests/versionupdate_test.go
  pkg/autopilot/common/waitfor.go
Labels: chore, area/smoke-tests

#2679 Bump golangci-lint to v1.51.0
  hack/tools/Makefile.variables
Labels: area/ci, chore

#2651 [Backport release-1.22] Bump etcd binary to v3.5.7
  .github/workflows/check-network.yaml
  .github/workflows/go.yml
  .github/workflows/lint.yaml
  .github/workflows/release.yml
  Makefile
  build/Dockerfile
  embedded-bins/Makefile.variables
  embedded-bins/containerd/Dockerfile
  embedded-bins/etcd/Dockerfile
  embedded-bins/kine/Dockerfile
  embedded-bins/konnectivity/Dockerfile
  embedded-bins/kubernetes/Dockerfile
  embedded-bins/runc/Dockerfile
Labels: area/etcd, chore

#2648 [Backport release-1.25] Replace unmaintained GitHub Actions
  .github/workflows/release.yml
Labels: area/ci, chore, backport/release-1.24

#2676 Bump Go to v1.20
  embedded-bins/Makefile.variables
  go.mod
  hack/tool/go.mod
  hack/tool/go.sum
  internal/pkg/file/file_test.go
Labels: chore

#2686 Bump golangci-lint to v1.51.1
  hack/tools/Makefile.variables
Labels: area/ci, chore

#2674 Use custom log writer for stdout/err in supervisor
  pkg/supervisor/logwriter.go
  pkg/supervisor/logwriter_test.go
  pkg/supervisor/supervisor.go
Labels: bug, security fix, backport/release-1.26

#2684 [Backport release-1.25] Bump containerd to v1.6.16
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: chore, component/containerd, backport/release-1.24

#2689 [Backport release-1.24] Bump containerd to v1.6.16
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: chore, component/containerd

#2683 [Backport release-1.22] Bump containerd to v1.5.17
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: chore, component/containerd

#2692 [release-1.23] Upgrade GitHub actions to use Node.js 16
  .github/workflows/check-network.yaml
  .github/workflows/commit.yaml
  .github/workflows/go.yml
  .github/workflows/lint.yaml
  .github/workflows/mkdocs-set-default-version.yml
  .github/workflows/publish-docs-manual.yml
  .github/workflows/publish-docs.yml
  .github/workflows/release.yml
  .github/workflows/stale.yml
Labels: area/ci, chore, backport/release-1.22

#2652 [Backport release-1.23] Replace set-output with env file in GH Actions
  .github/workflows/go.yml
  .github/workflows/publish-docs.yml
  .github/workflows/release.yml
Labels: area/ci, chore, backport/release-1.22

#2690 [Backport release-1.23] Replace unmaintained GitHub Actions
  .github/workflows/release.yml
Labels: area/ci, chore, backport/release-1.22

#2702 [Backport release-1.23] Don't fail-fast on inttest failures
  .github/workflows/go.yml
Labels: area/ci, chore, backport/release-1.22

#2703 [Backport release-1.24] Use custom log writer for stdout/err in supervisor
  pkg/supervisor/logwriter.go
  pkg/supervisor/logwriter_test.go
  pkg/supervisor/supervisor.go
Labels: bug, security fix, backport/release-1.23

#2697 [Backport release-1.22] Upgrade GitHub actions to use Node.js 16
  .github/workflows/check-network.yaml
  .github/workflows/commit.yaml
  .github/workflows/docs.yml
  .github/workflows/go.yml
  .github/workflows/lint.yaml
  .github/workflows/mkdocs-set-default-version.yml
  .github/workflows/publish-docs.yml
  .github/workflows/release.yml
  .github/workflows/stale.yml
Labels: area/ci, chore

#2698 [Backport release-1.22] Replace set-output with env file in GH Actions
  .github/workflows/publish-docs.yml
  .github/workflows/release.yml
Labels: area/ci, chore

#2706 [Backport release-1.23] Use custom log writer for stdout/err in supervisor
  pkg/supervisor/logwriter.go
  pkg/supervisor/logwriter_test.go
  pkg/supervisor/supervisor.go
Labels: bug, security fix, backport/release-1.22

#2708 [Backport release-1.22] Use custom log writer for stdout/err in supervisor
  pkg/supervisor/logwriter.go
  pkg/supervisor/logwriter_test.go
  pkg/supervisor/supervisor.go
Labels: bug, security fix

#2717 [Backport release-1.26] Bump helm.sh/helm/v3 from 3.10.3 to 3.11.1
  go.mod
  go.sum
Labels: security fix

#2723 Bump containerd to v1.6.17
  docs/nllb.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: chore, component/containerd, backport/release-1.26

#2721 Integrate Troubleshoot support bundle collection into inttests
  .github/workflows/go.yml
  inttest/common/footloosesuite.go
  inttest/footloose-alpine/Dockerfile
  inttest/footloose-alpine/root/etc/troubleshoot/k0s-inttest.yaml
  inttest/footloose-alpine/root/usr/local/bin/troubleshoot-k0s-inttest.sh
Labels: area/ci, chore, area/smoke-tests

#2734 Use contextual logger in OCIBundleReconciler
  pkg/component/worker/ocibundle.go
Labels: chore

#2730 Pass context explicitly to the SSH helper function in the footloose test suite
  inttest/addons/addons_test.go
  inttest/ap-ha3x3/ha3x3_test.go
  inttest/ap-single/single_test.go
  inttest/backup/backup_test.go
  inttest/basic/basic_test.go
  inttest/byocri/byocri_test.go
  inttest/capitalhostnames/capitalhostnames_test.go
  inttest/cli/cli_test.go
  inttest/cnichange/cnichange_test.go
  inttest/common/airgap.go
  inttest/common/filetools.go
  inttest/common/footloosesuite.go
  inttest/ctr/ctr_test.go
  inttest/customca/customca_test.go
  inttest/customdomain/customdomain_test.go
  inttest/customports/customports_test.go
  inttest/disabledcomponents/disabled_components_test.go
  inttest/dualstack/dualstack_test.go
  inttest/embedded-binaries/embedded_binaries_test.go
  inttest/externaletcd/external_etcd_test.go
  inttest/extraargs/extraargs_test.go
  inttest/hacontrolplane/hacontrolplane_test.go
  inttest/k0sctl/k0sctl_test.go
  inttest/kine/kine_test.go
  inttest/kubectl/kubectl_test.go
  inttest/kubeletcertrotate/kubeletcertrotate_test.go
  inttest/kuberouter/kuberouter_hairpin_test.go
  inttest/psp/psp_test.go
  inttest/singlenode/singlenode_test.go
  inttest/upgrade/upgrade_test.go
Labels: area/smoke-tests

#2701 Properly bridge cfssl logs to logrus
  cmd/api/api.go
  cmd/controller/controller.go
  cmd/kubeconfig/create.go
  cmd/root.go
  cmd/worker/worker.go
  internal/pkg/log/cfssl.go
  internal/pkg/log/k0s.go
  main.go
  pkg/leaderelection/lease_pool.go
Labels: bug

#2739 [release-1.23] Bump containerd to v1.15.18
  docs/external-runtime-deps.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: chore, component/containerd, backport/release-1.22

#2732 [release-1.26] Bump go to v1.19.6
  embedded-bins/Makefile.variables
Labels: chore, backport/release-1.25

#2733 Add note about k0sctl to the configuration docs
  docs/configuration.md
Labels: documentation

#2747 Fixes for broken CI on main
  inttest/addons/addons_test.go
  pkg/constant/constant_shared.go
Labels: bug

#2731 Bump Go to v1.20.1
  embedded-bins/Makefile.variables
Labels: chore

#2699 Bump CoreDNS to v1.10.1
  pkg/constant/constant_shared.go
Labels: area/network, chore, backport/release-1.26

#2720 Detangle autopilot waitfor code
  inttest/ap-airgap/airgap_test.go
  inttest/ap-ha3x3/ha3x3_test.go
  inttest/ap-platformselect/platformselect_test.go
  inttest/ap-quorum/quorum_test.go
  inttest/ap-quorumsafety/quorumsafety_test.go
  inttest/ap-removedapis/removedapis_test.go
  inttest/ap-selector/selector_test.go
  inttest/ap-single/single_test.go
  inttest/ap-updater/updater_test.go
  inttest/common/autopilot/waitfor.go
  inttest/kubeletcertrotate/kubeletcertrotate_test.go
  inttest/toolsuite/tests/versionupdate_test.go
  pkg/autopilot/common/waitfor.go
  pkg/autopilot/controller/setup.go
  static/misc/api-resources.yaml
Labels: chore, area/smoke-tests, component/autopilot

#2764 Fix copyright notice year
  inttest/common/autopilot/waitfor.go
Labels: bug, area/ci

#2766 Expose KUBE_VERSION in docs dev container
  docs/Dockerfile.serve-dev
  docs/Makefile
Labels: documentation, chore

#2768 Enable dependabot for hack/tool
  .github/dependabot.yml
Labels: chore, area/smoke-tests

#2769 Add KUBE_VERSION to mike when publishing docs
  .github/workflows/publish-docs.yml
Labels: documentation, area/ci, chore

#2744 [Backport release-1.25] Bump containerd to v1.6.17
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: chore, component/containerd, backport/release-1.24

#2746 Fix airgap bundle caching in CI
  .github/workflows/go.yml
Labels: bug, area/ci, backport/release-1.26

#2737 Bump containerd to v1.6.18
  docs/external-runtime-deps.md
  docs/nllb.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: chore, component/containerd, backport/release-1.25, backport/release-1.26

#2745 Bump kine to v0.9.9
  embedded-bins/Makefile.variables
  pkg/component/controller/kine.go
Labels: area/controlplane, chore, backport/release-1.26

#2781 [Backport release-1.26] Bump containerd to v1.6.18
  docs/external-runtime-deps.md
  docs/nllb.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: chore, component/containerd

#2782 [Backport release-1.25] Bump containerd to v1.6.18
  docs/external-runtime-deps.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: chore, component/containerd

#2783 [Backport release-1.24] Bump containerd to v1.6.18
  docs/external-runtime-deps.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: chore, component/containerd

#2784 [Backport release-1.26] Bump kine to v0.9.9
  embedded-bins/Makefile.variables
Labels: area/controlplane, chore, backport/release-1.25

#2786 [Backport release-1.25] Bump kine to v0.9.9
  embedded-bins/Makefile.variables
Labels: area/controlplane, chore, backport/release-1.24

#2788 Replace Slack with Lens Forums in README
  README.md
Labels: documentation, chore

#2804 Copyright: Assume untracked files as "current year"
  hack/copyright.sh
Labels: area/ci, chore

#2803 [Backport release-1.26] Fix external address reconciliation w.r.t. dynamic config
  cmd/controller/controller.go
  inttest/Makefile
  inttest/Makefile.variables
  inttest/customports/customports_test.go
  pkg/component/controller/apiendpointreconciler.go
  pkg/component/controller/apiendpointreconciler_test.go
  pkg/component/controller/tunneledapiendpointreconciller.go
Labels: bug, area/controlplane, backport/release-1.25

#2729 Ensure cleanup of inttests also during the setup phase
  inttest/common/footloosesuite.go
Labels: bug, area/smoke-tests

#2765 Restore some docs dependency version bumps
  docs/requirements.txt
Labels: documentation, chore

#2816 [release-1.25] Take kube-proxy API address from node config
  pkg/component/controller/kubeproxy.go
Labels: bug, area/network, component/kube-proxy, backport/release-1.24

#2799 Bump go-sqlite3 to v1.14.16
  go.mod
  go.sum
Labels: security fix, chore, dependencies, backport/release-1.26
