Repository k0sproject/k0s, pull requests merged in 2023-04, with the labels that each got.

#2961 Fix kube-proxy iptables masqueradeAll default value.
  pkg/apis/k0s.k0sproject.io/v1beta1/kubeproxy.go
Labels: backport/release-1.26

#2969 Bump Go version to v1.19.8
  embedded-bins/Makefile.variables
Labels: backport/release-1.24, backport/release-1.25

#2567 Remove network-plugin and cni-bin-dir on Windows
  pkg/component/worker/kubelet.go
Labels: area/windows

#2991 Bump containerd to v1.7.0
  docs/external-runtime-deps.md
  docs/nllb.md
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
  inttest/basic/basic_test.go
  inttest/embedded-binaries/embedded_binaries_test.go
  pkg/constant/constant_posix.go
Labels: area/containers, chore, component/containerd

#2994 Restructure kubectl plugin execution
  cmd/kubectl/kubectl.go
  inttest/common/filetools.go
  inttest/kubectl/kubectl_test.go
Labels: bug, area/cli

#3003 Bump Kubernetes to v1.26.4
  .github/workflows/publish-docs-manual.yml
  docs/autopilot.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/conformance/README.md
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/constant/constant_shared.go
Labels: chore, backport/release-1.26

#2997 [release-1.25] Bump Kubernetes to v1.25.9
  .github/workflows/publish-docs-manual.yml
  docs/airgap-install.md
  docs/autopilot-multicommand.md
  docs/autopilot.md
  docs/configuration.md
  docs/docker-shim.md
  docs/install.md
  docs/k0s-in-docker.md
  docs/k0s-multi-node.md
  docs/raspberry-pi4.md
  docs/releases.md
  docs/reset.md
  docs/upgrade.md
  docs/worker-node-config.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  inttest/conformance/README.md
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/constant/constant_shared.go
Labels: chore

#3002 Bump github.com/cloudflare/cfssl from 1.6.3 to 1.6.4
  go.mod
  go.sum
Labels: chore, dependencies

#2995 Bump runc to v1.1.6
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, backport/release-1.26

#2996 Bump etcd to v3.5.8
  embedded-bins/Makefile.variables
  go.mod
  go.sum
  pkg/component/controller/etcd.go
Labels: area/etcd, chore, backport/release-1.26

#3004 [Backport release-1.24] Fix dualstack config propagation in dynamic config mode
  inttest/Makefile
  inttest/Makefile.variables
  inttest/dualstack/dualstack_test.go
  pkg/apis/k0s.k0sproject.io/v1beta1/clusterconfig_types.go
Labels: bug, area/network, area/controlplane

#2914 Improve logging and context handling in basic inttest
  inttest/basic/basic_test.go
Labels: chore, area/smoke-tests

#2902 inttests: Use correct arch in footloose image
  inttest/Makefile
  inttest/footloose-alpine/Dockerfile
Labels: chore, area/smoke-tests

#3009 [release-1.25] Bump etcd binary to v3.5.8
  embedded-bins/Makefile.variables
Labels: area/etcd, chore, backport/release-1.24

#3006 [Backport release-1.26] Bump runc to v1.1.6
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, backport/release-1.25

#2880 Bump Kubernetes to v1.27.1
  .github/workflows/publish-docs-manual.yml
  docs/autopilot.md
  docs/dockershim.md
  docs/runtime.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/conformance/README.md
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/autopilot.k0sproject.io/v1beta2/clientset/doc.go
  pkg/apis/autopilot.k0sproject.io/v1beta2/clientset/typed/autopilot.k0sproject.io/v1beta2/fake/fake_controlnode.go
  pkg/apis/autopilot.k0sproject.io/v1beta2/clientset/typed/autopilot.k0sproject.io/v1beta2/fake/fake_plan.go
  pkg/apis/autopilot.k0sproject.io/v1beta2/clientset/typed/autopilot.k0sproject.io/v1beta2/fake/fake_updateconfig.go
  pkg/apis/k0s.k0sproject.io/clientset/doc.go
  pkg/apis/k0s.k0sproject.io/clientset/typed/k0s.k0sproject.io/v1beta1/fake/fake_clusterconfig.go
  pkg/autopilot/common/hostname.go
  pkg/component/controller/controllersleasecounter.go
  pkg/component/controller/csrapprover.go
  pkg/component/controller/extensions_controller.go
  pkg/component/controller/kubeletconfig_test.go
  pkg/component/controller/workerconfig/reconciler_test.go
  pkg/component/worker/config/config_test.go
  pkg/component/worker/kubelet.go
  pkg/component/worker/utils.go
  pkg/constant/constant_shared.go
  pkg/k0scloudprovider/command.go
Labels: chore

#3034 Bump controller-tools to v0.11.4
  hack/tools/Makefile.variables
  static/manifests/autopilot/CustomResourceDefinition/autopilot.k0sproject.io_controlnodes.yaml
  static/manifests/autopilot/CustomResourceDefinition/autopilot.k0sproject.io_plans.yaml
  static/manifests/autopilot/CustomResourceDefinition/autopilot.k0sproject.io_updateconfigs.yaml
  static/manifests/helm/CustomResourceDefinition/helm.k0sproject.io_charts.yaml
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore

#3038 Fix racy leader pool test
  pkg/leaderelection/lease_pool_test.go
Labels: chore, backport/release-1.27
