Repository k0sproject/k0s, pull requests merged in 2023-05, with the labels that each got.

#3058 Bump Go to v1.20.4
  embedded-bins/Makefile.variables
Labels: chore, backport/release-1.27

#3059 [release-1.26] Bump Go to v1.19.9
  embedded-bins/Makefile.variables
Labels: chore, backport/release-1.25

#3055 Let addons inttest respect the suite's context
  inttest/addons/addons_test.go
Labels: chore, area/smoke-tests

#3053 Clear error in Helm chart status after successful reconciliation
  pkg/component/controller/extensions_controller.go
Labels: bug, area/helm

#3078 Remove unused constant `WinDataDirDefault`
  pkg/constant/constant_shared.go
Labels: chore

#3080 Bump github.com/opencontainers/image-spec to v1.1.0-rc3
  go.mod
  go.sum
Labels: chore, dependencies

#3067 [Backport release-1.24] Bump Go to v1.19.9
  embedded-bins/Makefile.variables
Labels: chore

#3082 Helm upgrade bug fix
  inttest/addons/addons_test.go
  pkg/component/controller/extensions_controller.go
Labels: backport/release-1.25, backport/release-1.26, backport/release-1.27

#3091 [Backport release-1.25] Helm upgrade bug fix
  inttest/addons/addons_test.go
  pkg/component/controller/extensions_controller.go
Labels: area/helm

#3089 [Backport release-1.26] Helm upgrade bug fix
  inttest/addons/addons_test.go
  pkg/component/controller/extensions_controller.go
Labels: area/helm

#3079 Remove unused inttest util function `ConfigGetter.FakeAPIConfig()`
  internal/testutil/runtime_config.go
Labels: chore

#3092 [Backport release-1.26] Clear error in Helm chart status after successful reconciliation
  pkg/component/controller/extensions_controller.go
Labels: bug, area/helm, backport/release-1.25

#3099 Bump containerd to v1.7.1
  docs/external-runtime-deps.md
  docs/nllb.md
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, component/containerd, backport/release-1.27

#3040 Bump runc to v1.1.7
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, backport/release-1.27

#3065 Bump calico image version (vuln fixes)
  pkg/constant/constant_shared.go
Labels: security fix, component/calico, backport/release-1.27

#3081 [release-1.26] Bump containerd to v1.6.21
  docs/external-runtime-deps.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, component/containerd

#3108 Bump etcd to v3.5.9
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/etcd, chore, backport/release-1.27

#3105 [Backport release-1.27] Bump runc to v1.1.7
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, backport/release-1.26

#3113 [Backport release-1.25] Bump runc to v1.1.7
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, backport/release-1.24

#3068 Update otelhttp to v0.39.0
  go.mod
  go.sum
Labels: security fix, dependencies, backport/release-1.27

#3056 Bump controller-tools to v0.12.0
  hack/tools/Makefile.variables
  static/manifests/autopilot/CustomResourceDefinition/autopilot.k0sproject.io_controlnodes.yaml
  static/manifests/autopilot/CustomResourceDefinition/autopilot.k0sproject.io_plans.yaml
  static/manifests/autopilot/CustomResourceDefinition/autopilot.k0sproject.io_updateconfigs.yaml
  static/manifests/helm/CustomResourceDefinition/helm.k0sproject.io_charts.yaml
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore

#3083 [Backport release-1.25] Bump containerd to v1.6.21
  docs/external-runtime-deps.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, component/containerd

#3084 [Backport release-1.24] Bump containerd to v1.6.21
  docs/external-runtime-deps.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, component/containerd

#3114 [Backport release-1.26] Bump github.com/docker/distribution from 2.8.1+incompatible to 2.8.2+incompatible
  go.mod
  go.sum
Labels: security fix, dependencies, go, backport/release-1.25

#3100 Make multicontroller inttest be fail-fast
  inttest/multicontroller/multicontroller_test.go
Labels: chore, area/smoke-tests

#3115 Bump Alpine to v3.18
  docs/Makefile.variables
  embedded-bins/Makefile.variables
  hack/image-bundler/Dockerfile
Labels: chore

#3041 Bump kine to v0.10.1
  embedded-bins/Makefile.variables
  pkg/component/controller/kine.go
Labels: chore

#3136 Bump Kubernetes to v1.27.2
  .github/workflows/publish-docs-manual.yml
  docs/autopilot.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/conformance/README.md
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/constant/constant_shared.go
Labels: chore, backport/release-1.27

#3139 Bump Kubernetes to v1.26.5
  docs/autopilot.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.sum
  inttest/conformance/README.md
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/constant/constant_shared.go
Labels: chore, backport/release-1.26

#3057 Bump Helm to v3.12.0
  go.mod
  go.sum
Labels: chore, area/helm

#3138 [release-1.24] Bump Kubernetes to v1.24.14
  docs/autopilot-multicommand.md
  docs/autopilot.md
  docs/configuration.md
  docs/docker-shim.md
  docs/install.md
  docs/k0s-in-docker.md
  docs/k0s-multi-node.md
  docs/raspberry-pi4.md
  docs/releases.md
  docs/worker-node-config.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  inttest/conformance/README.md
  pkg/constant/constant_shared.go
Labels: chore

#3137 Use filepath.Join directly for Windows UNC paths
  pkg/supervisor/pingpong_windows.go
Labels: chore

#3141 [Backport release-1.27] Bump Kubernetes to v1.27.2
  .github/workflows/publish-docs-manual.yml
  docs/autopilot.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/conformance/README.md
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/constant/constant_shared.go
Labels: chore, backport

#3140 [release-1.25] Bump Kubernetes to v1.25.10
  docs/airgap-install.md
  docs/autopilot-multicommand.md
  docs/autopilot.md
  docs/configuration.md
  docs/docker-shim.md
  docs/install.md
  docs/k0s-in-docker.md
  docs/k0s-multi-node.md
  docs/raspberry-pi4.md
  docs/releases.md
  docs/reset.md
  docs/upgrade.md
  docs/worker-node-config.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  inttest/conformance/README.md
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/constant/constant_shared.go
Labels: chore

#3042 Bump troubleshoot to v0.64.0
  inttest/footloose-alpine/Dockerfile
Labels: chore, area/smoke-tests

#3146 [Backport release-1.26] Bump pymdown-extensions from 9.9.1 to 10.0 in /docs
  docs/requirements.txt
Labels: documentation, security fix, dependencies, python, backport/release-1.25

#3143 [release-1.25] Bump etcd binary to v3.5.9
  embedded-bins/Makefile.variables
Labels: area/etcd, chore, backport/release-1.24

#3144 [Backport release-1.24] Bump github.com/docker/distribution from 2.8.1+incompatible to 2.8.2+incompatible
  go.mod
  go.sum
Labels: security fix, dependencies, go

#3148 Add missing prerequisites to footlose Docker image
  inttest/Makefile
Labels: chore, area/smoke-tests

#3147 Bump cri-dockerd to v0.3.2
  inttest/footloose-alpine/Dockerfile
Labels: chore, area/smoke-tests

#3151 [Backport release-1.24] Bump pymdown-extensions from 9.4 to 10.0 in /docs
  docs/requirements.txt
Labels: documentation, security fix, dependencies, python

#3157 Bump sonobuoy to v0.56.16
  inttest/Makefile
Labels: chore, backport/release-1.25, backport/release-1.26, backport/release-1.27

#3158 [Backport release-1.24] Bump sonobuoy to v0.56.16
  inttest/Makefile
Labels: chore, backport
