Repository k0sproject/k0s, pull requests merged in 2023-01, with the labels that each got.

#2573 Bump containerd to 1.6.15
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: bug, component/containerd, backport/release-1.24, backport/release-1.25

#2577 [Backport release-1.25] Bump containerd to 1.6.15
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: bug, component/containerd

#2578 [Backport release-1.24] Bump containerd to 1.6.15
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: bug, component/containerd

#2575 Add missing replaces for Kubernetes modules
  go.mod
  go.sum
Labels: chore

#2576 Bump manifest-tool to v2.0.6
  go.mod
  go.sum
Labels: chore

#2429 Node-local load balancing
  Makefile
  cmd/airgap/listimages.go
  cmd/airgap/listimages_test.go
  cmd/controller/controller.go
  cmd/worker/worker.go
  go.mod
  hack/validate-images/main.go
  internal/pkg/iface/iface.go
  internal/pkg/net/hostport.go
  internal/pkg/net/hostport_test.go
  inttest/Makefile
  inttest/Makefile.variables
  inttest/basic/basic_test.go
  inttest/cli/cli_test.go
  inttest/common/filetools.go
  inttest/common/footloosesuite.go
  inttest/common/launchdelegate.go
  inttest/common/util.go
  inttest/nllb/nllb_test.go
  pkg/airgap/images.go
  pkg/apis/k0s.k0sproject.io/v1beta1/clusterconfig_types.go
  pkg/apis/k0s.k0sproject.io/v1beta1/images.go
  pkg/apis/k0s.k0sproject.io/v1beta1/images_test.go
  pkg/apis/k0s.k0sproject.io/v1beta1/konnectivity.go
  pkg/apis/k0s.k0sproject.io/v1beta1/network.go
  pkg/apis/k0s.k0sproject.io/v1beta1/nllb.go
  pkg/apis/k0s.k0sproject.io/v1beta1/nllb_test.go
  pkg/apis/k0s.k0sproject.io/v1beta1/zz_generated.deepcopy.go
  pkg/autopilot/controller/root_worker.go
  pkg/component/controller/controllermanager.go
  pkg/component/controller/konnectivity.go
  pkg/component/controller/kubeproxy.go
  pkg/component/controller/workerconfig/reconciler.go
  pkg/component/controller/workerconfig/reconciler_test.go
  pkg/component/controller/workerconfig/snapshot.go
  pkg/component/worker/config/config.go
  pkg/component/worker/config/config_test.go
  pkg/component/worker/config/loader.go
  pkg/component/worker/config/loader_test.go
  pkg/component/worker/kubelet.go
  pkg/component/worker/nllb/doc.go
  pkg/component/worker/nllb/envoy.go
  pkg/component/worker/nllb/envoy_test.go
  pkg/component/worker/nllb/reconciler.go
  pkg/component/worker/nllb/reconciler_test.go
  pkg/config/config.go
  pkg/constant/constant_shared.go
  pkg/kubernetes/watch/core.go
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: area/network, area/worker, component/konnectivity, component/kubelet, component/kube-proxy

#2585 Remove Docker replacements from go.mod
  go.mod
  go.sum
Labels: chore

#2592 Overwrite (if needed) conformance results on upload.
  .github/workflows/release.yml
Labels: chore, backport/release-1.23, backport/release-1.24, backport/release-1.25

#2583 Disable some unneeded components in kuberouter inttest
  inttest/kuberouter/kuberouter_hairpin_test.go
Labels: chore, area/smoke-tests

#2584 Add docs for node-local load balancing
  docs/configuration.md
  docs/nllb.md
  mkdocs.yml
  pkg/apis/k0s.k0sproject.io/v1beta1/nllb.go
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: documentation

#2607 Bump go to 1.19.5
  embedded-bins/Makefile.variables
Labels: backport/release-1.25, backport/release-1.26

#2615 Bump Kubernetes to v1.26.1
  .github/workflows/publish-docs-manual.yml
  docs/airgap-install.md
  docs/autopilot-multicommand.md
  docs/autopilot.md
  docs/configuration.md
  docs/docker-shim.md
  docs/install.md
  docs/k0s-in-docker.md
  docs/k0s-multi-node.md
  docs/nllb.md
  docs/raspberry-pi4.md
  docs/releases.md
  docs/reset.md
  docs/upgrade.md
  docs/worker-node-config.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  inttest/conformance/README.md
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/constant/constant_shared.go
Labels: chore, backport/release-1.26

#2616 [release-1.25] Bump Kubernetes to v1.25.6
  .github/workflows/publish-docs-manual.yml
  docs/airgap-install.md
  docs/autopilot-multicommand.md
  docs/autopilot.md
  docs/configuration.md
  docs/docker-shim.md
  docs/install.md
  docs/k0s-in-docker.md
  docs/k0s-multi-node.md
  docs/raspberry-pi4.md
  docs/releases.md
  docs/reset.md
  docs/upgrade.md
  docs/worker-node-config.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  inttest/conformance/README.md
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/constant/constant_shared.go
Labels: chore

#2617 [release-1.23] Bump Kubernetes to v1.23.16
  docs/configuration.md
  docs/install.md
  docs/k0s-multi-node.md
  docs/releases.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  inttest/conformance/README.md
  pkg/constant/constant_shared.go
Labels: chore

#2618 [release-1.24] Bump Kubernetes to v1.24.10
  docs/autopilot-multicommand.md
  docs/autopilot.md
  docs/configuration.md
  docs/docker-shim.md
  docs/install.md
  docs/k0s-in-docker.md
  docs/k0s-multi-node.md
  docs/raspberry-pi4.md
  docs/releases.md
  docs/worker-node-config.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  inttest/conformance/README.md
  pkg/constant/constant_shared.go
Labels: chore

#2620 Bump etcd to v3.5.7
  embedded-bins/Makefile.variables
  go.mod
  go.sum
  pkg/constant/constant_shared_test.go
Labels: area/etcd, chore, backport/release-1.22, backport/release-1.23, backport/release-1.24, backport/release-1.25, backport/release-1.26

#2619 [release-1.26] Bump Kubernetes to v1.26.1
  .github/workflows/publish-docs-manual.yml
  docs/airgap-install.md
  docs/autopilot-multicommand.md
  docs/autopilot.md
  docs/configuration.md
  docs/docker-shim.md
  docs/install.md
  docs/k0s-in-docker.md
  docs/k0s-multi-node.md
  docs/nllb.md
  docs/raspberry-pi4.md
  docs/releases.md
  docs/reset.md
  docs/upgrade.md
  docs/worker-node-config.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  inttest/conformance/README.md
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/constant/constant_shared.go
Labels: chore

#2624 Improve CoreDNS affinity check in basic inttest
  inttest/basic/basic_test.go
  pkg/kubernetes/watch/watcher.go
Labels: chore, area/smoke-tests

#2629 [release-1.25] Bump etcd binary to v3.5.7
  embedded-bins/Makefile.variables
Labels: chore, backport/release-1.22, backport/release-1.23, backport/release-1.24

#2290 Fail inttests when the deadline is exceeded
  inttest/common/footloosesuite.go
Labels: bug, area/ci, area/smoke-tests

#2472 Bump Alpine to 3.17.1
  embedded-bins/Makefile.variables
  inttest/footloose-alpine/Dockerfile
  inttest/footloose-alpine/root/etc/nginx/conf.d
Labels: chore

#2638 Bump cri-dockerd to v0.3.1
  inttest/footloose-alpine/Dockerfile
Labels: chore

#2643 Fix docs Python Docker image
  .github/workflows/build-docs.yml
  docs/Makefile.variables
Labels: bug, documentation, area/ci

#2633 [Backport release-1.23] Bump etcd binary to v3.5.7
  embedded-bins/Makefile.variables
Labels: chore, backport/release-1.22

#2646 [Backport release 1.24] Replace set-output with env file in GH Actions
  .github/workflows/go.yml
  .github/workflows/publish-docs.yml
  .github/workflows/release.yml
Labels: area/ci, chore, backport/release-1.23

#2641 docs: Documenting Kubelet path
  docs/storage.md
  docs/troubleshooting.md
Labels: documentation
