Repository k0sproject/k0s, pull requests merged in 2023-09, with the labels that each got.

#3432 Bump k0sctl to v0.15.5
  .github/workflows/check-network.yaml
  .github/workflows/ostests-e2e.yaml
  hack/ostests/modules/os/os_alpine_3_17_userdata.tftpl
  inttest/k0sctl/k0sctl_test.go
Labels: area/ci, chore

#3459 Bump Go to v1.20.8
  embedded-bins/Makefile.variables
Labels: security fix, backport/release-1.27

#3241 Use Docker iid files consequently in builds
  Makefile
  embedded-bins/Makefile
  embedded-bins/Makefile.variables
Labels: chore

#3462 Bump k0sproject/version to v0.4.1
  .github/workflows/publish-docs.yml
  hack/tools/gen-matrix.sh
  hack/tools/run-autopilot-matrix-tests.sh
Labels: chore, area/smoke-tests

#3470 Lower disk space eviction limits for network conformance inttest
  inttest/network-conformance/network_test.go
Labels: bug, area/ci

#3469 Remove cid file before invoking docker build
  embedded-bins/Makefile
Labels: bug

#3467 [Backport release-1.26] Bump github.com/cyphar/filepath-securejoin from 0.2.3 to 0.2.4
  go.mod
  go.sum
Labels: security fix, dependencies, go, backport/release-1.25

#3461 [Backport release-1.27] Bump Go to v1.20.8
  embedded-bins/Makefile.variables
Labels: security fix, backport/release-1.26

#3481 Bump kine to 0.10.3
  embedded-bins/Makefile.variables
Labels: area/controlplane, chore, component/kine

#3485 Bump containerd to v1.7.6
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, component/containerd, backport/release-1.27

#3480 [Backport release-1.26] Bump Go to v1.20.8
  embedded-bins/Makefile.variables
Labels: security fix, backport/release-1.25

#3486 [release-1.25] Bump Kubernetes to v1.25.14
  docs/airgap-install.md
  docs/autopilot-multicommand.md
  docs/autopilot.md
  docs/configuration.md
  docs/docker-shim.md
  docs/install.md
  docs/k0s-in-docker.md
  docs/k0s-multi-node.md
  docs/raspberry-pi4.md
  docs/releases.md
  docs/reset.md
  docs/upgrade.md
  docs/worker-node-config.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  inttest/conformance/README.md
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/constant/constant_shared.go
Labels: chore

#3483 Capture target variable in loop body
  pkg/autopilot/controller/readyprober.go
Labels: bug

#2680 Bump iptables to v1.8.9
  embedded-bins/Makefile.variables
  embedded-bins/iptables/Dockerfile
  embedded-bins/iptables/revert-fix-eth-alen.patch
  embedded-bins/iptables/use-uint-instead-of-u_int.patch
Labels: area/network, chore

#3491 Remove unused error channel
  pkg/autopilot/controller/readyprober.go
Labels: chore

#3510 Fixes for kernel >= 6.0
  inttest/cli/cli_test.go
  inttest/common/footloosesuite.go
  pkg/constant/constant_shared.go
Labels: bug, area/network, area/smoke-tests, component/calico

#3511 [Backport release-1.27] Change kubelet args passed in CLI inttest
  inttest/cli/cli_test.go
  inttest/common/footloosesuite.go
Labels: bug, area/smoke-tests, backport/release-1.26

#3495 Fix log collection in cli inttest
  inttest/cli/cli_test.go
Labels: chore, area/smoke-tests

#3499 Initialize global controller-runtime logger
  go.mod
  go.sum
  internal/pkg/log/k0s.go
  pkg/component/controller/extensions_controller.go
Labels: chore

#3513 [Backport release-1.25] Change kubelet args passed in CLI inttest
  inttest/cli/cli_test.go
  inttest/common/footloosesuite.go
Labels: bug, area/smoke-tests, backport/release-1.24

#3501 Add new dimension for kube-proxy mode to OS testing matrix
  .github/workflows/ostests-e2e.yaml
  .github/workflows/ostests-matrix.yaml
  .github/workflows/ostests-nightly.yaml
  hack/ostests/README.md
  hack/ostests/main.tf
  hack/ostests/modules/k0sctl/variables.tf
  hack/ostests/variables.tf
Labels: enhancement, area/smoke-tests

#3493 [Backport release-1.27] Bump containerd to v1.7.6
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, component/containerd

#3517 Add missing default for kube-proxy-mode to OS testing workflow
  .github/workflows/ostests-e2e.yaml
Labels: bug, area/smoke-tests

#3519 Also remove required for kube-proxy-mode from OS testing workflow
  .github/workflows/ostests-e2e.yaml
Labels: bug, area/smoke-tests

#3520 [release-1.27] Bump Kubernetes to v1.27.6
  .github/workflows/publish-docs-manual.yml
  docs/autopilot.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/conformance/README.md
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/constant/constant_shared.go
Labels: chore

#3525 Bump CoreDNS to v1.11.1
  pkg/constant/constant_shared.go
Labels: area/controlplane, chore

#3528 Bump Kubernetes to v1.28.2
  .github/workflows/publish-docs-manual.yml
  docs/autopilot.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/constant/constant_shared.go
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore

#3529 Fix checksums job in release workflow
  .github/workflows/release.yml
Labels: bug, area/ci

#3532 Add GitHub token to checksums step in release workflow
  .github/workflows/release.yml
Labels: bug, area/ci

#3533 Update kubernetes pause image to v3.9
  pkg/constant/constant_windows.go
Labels: chore

#3534 Use release ID in checksums step of release pipeline
  .github/workflows/release.yml
Labels: bug, area/ci
