Repository k0sproject/k0s, pull requests merged in 2023-08, with the labels that each got.

#3338 Bump go to 1.20.7 (CVE-2023-29409)
  embedded-bins/Makefile.variables
Labels: backport/release-1.25, backport/release-1.26, backport/release-1.27

#3345 Bump containerd 1.6.22
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: backport/release-1.25

#3369 Fix workerprofile data types on the generated CRD
  inttest/configchange/config_test.go
  inttest/nllb/nllb_test.go
  pkg/apis/k0s/v1beta1/clusterconfig_types_test.go
  pkg/apis/k0s/v1beta1/workerprofile.go
  pkg/apis/k0s/v1beta1/workerprofile_test.go
  pkg/apis/k0s/v1beta1/zz_generated.deepcopy.go
  pkg/component/controller/kubeletconfig.go
  pkg/component/controller/kubeletconfig_test.go
  pkg/component/controller/workerconfig/reconciler.go
  pkg/component/controller/workerconfig/reconciler_test.go
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: backport/release-1.25, backport/release-1.26, backport/release-1.27

#3371 Bump runc to 1.1.9
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: backport/release-1.25, backport/release-1.26, backport/release-1.27

#3376 [Release 1.26] k0s crd fix
  inttest/configchange/config_test.go
  inttest/nllb/nllb_test.go
  pkg/apis/k0s.k0sproject.io/v1beta1/clusterconfig_types_test.go
  pkg/apis/k0s.k0sproject.io/v1beta1/workerprofile.go
  pkg/apis/k0s.k0sproject.io/v1beta1/workerprofile_test.go
  pkg/apis/k0s.k0sproject.io/v1beta1/zz_generated.deepcopy.go
  pkg/component/controller/kubeletconfig.go
  pkg/component/controller/kubeletconfig_test.go
  pkg/component/controller/workerconfig/reconciler.go
  pkg/component/controller/workerconfig/reconciler_test.go
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: backport/release-1.25

#3374 [Backport release-1.27] Bump runc to 1.1.9
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, backport/release-1.26

#3379 Typo fix for external-runtime-deps.md
  docs/external-runtime-deps.md
Labels: documentation

#3385 [Backport release-1.26] Bump runc to 1.1.9
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, backport/release-1.25

#3395 Bump metrics-server to v0.6.4
  docs/configuration.md
  docs/raspberry-pi4.md
  pkg/constant/constant_shared.go
Labels: chore, component/metrics-server

#3393 Bump controller runtime to v0.15
  go.mod
  go.sum
  pkg/autopilot/controller/plans/core/planstatecontroller_test.go
Labels: chore

#3397 [release-1.26] Bump containerd to v1.6.23
  docs/external-runtime-deps.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, component/containerd, backport/release-1.25

#3396 Bump controller-tools to v0.13.0
  hack/tools/Makefile.variables
  pkg/apis/autopilot/v1beta2/zz_generated.deepcopy.go
  pkg/apis/helm/v1beta1/zz_generated.deepcopy.go
  pkg/apis/k0s/v1beta1/zz_generated.deepcopy.go
  static/manifests/autopilot/CustomResourceDefinition/autopilot.k0sproject.io_controlnodes.yaml
  static/manifests/autopilot/CustomResourceDefinition/autopilot.k0sproject.io_plans.yaml
  static/manifests/autopilot/CustomResourceDefinition/autopilot.k0sproject.io_updateconfigs.yaml
  static/manifests/helm/CustomResourceDefinition/helm.k0sproject.io_charts.yaml
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore

#3403 [Backport release-1.25] Bump containerd to v1.6.23
  docs/external-runtime-deps.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, component/containerd

#3380 Distinguish if feature gate false because it is set as false or by default
  pkg/apis/k0s/v1beta1/clusterconfig_types_test.go
  pkg/apis/k0s/v1beta1/feature_gates.go
  pkg/apis/k0s/v1beta1/feature_gates_test.go
Labels: backport/release-1.25, backport/release-1.26, backport/release-1.27

#3413 [release-1.26] Bump Kubernetes to v1.26.8
  .github/workflows/publish-docs-manual.yml
  docs/airgap-install.md
  docs/autopilot-multicommand.md
  docs/autopilot.md
  docs/configuration.md
  docs/docker-shim.md
  docs/install.md
  docs/k0s-in-docker.md
  docs/k0s-multi-node.md
  docs/nllb.md
  docs/raspberry-pi4.md
  docs/releases.md
  docs/reset.md
  docs/upgrade.md
  docs/worker-node-config.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/conformance/README.md
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/constant/constant_shared.go
Labels: security fix

#3388 Add GitHub workflows for OS testing
  .github/workflows/ostests-e2e.yaml
  .github/workflows/ostests-matrix.yaml
  .github/workflows/ostests-nightly.yaml
  hack/ostests/README.md
  hack/ostests/main.tf
  hack/ostests/variables.tf
Labels: enhancement

#3416 [release-1.24] Bump Kubernetes to v1.24.17
  docs/autopilot-multicommand.md
  docs/autopilot.md
  docs/configuration.md
  docs/docker-shim.md
  docs/install.md
  docs/k0s-in-docker.md
  docs/k0s-multi-node.md
  docs/raspberry-pi4.md
  docs/releases.md
  docs/worker-node-config.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  inttest/conformance/README.md
  pkg/constant/constant_shared.go
Labels: security fix

#3418 [release-1.27] Bump Kubernetes to v1.27.5
  .github/workflows/publish-docs-manual.yml
  docs/autopilot.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  inttest/conformance/README.md
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/constant/constant_shared.go
Labels: security fix

#3420 Bump containerd to 1.7.4
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: component/containerd, backport/release-1.27

#3419 Build k0s Docker image on GitHub managed runners
  .github/workflows/release.yml
Labels: bug, area/ci, backport/release-1.27

#3412 Actually merge CRI configs from drop-ins instead of concatenating them
  go.mod
  go.sum
  pkg/component/worker/containerd/criconfig.go
  pkg/component/worker/containerd/criconfig_test.go
Labels: backport/release-1.27

#3425 [Backport release-1.24] Build k0s Docker image on GitHub managed runners
  .github/workflows/release.yml
Labels: bug, area/ci

#3426 [Backport release-1.27] Actually merge CRI configs from drop-ins instead of concatenating them
  go.mod
  go.sum
  pkg/component/worker/containerd/criconfig.go
  pkg/component/worker/containerd/criconfig_test.go
Labels: bug, area/containers, component/containerd

#3427 Bump containerd 1.7.5
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: bug, area/containers, component/containerd, backport/release-1.27

#3439 Bump Alpine to v3.18.3
  embedded-bins/Makefile.variables
  inttest/footloose-alpine/Dockerfile
Labels: chore

#3434 [Backport release-1.26] Bump metrics-server to v0.6.4
  docs/configuration.md
  docs/raspberry-pi4.md
  pkg/constant/constant_shared.go
Labels: chore, component/metrics-server, backport/release-1.25
