Repository k0sproject/k0s, pull requests merged in 2023-07, with the labels that each got.

#3244 Add a script to tag and push k0s releases
  RELEASE.md
  hack/release.sh
Labels: chore

#3193 Remove special-case for setup-go on ARMv7
  .github/workflows/go.yml
Labels: chore, area/smoke-tests

#3255 Bump containerd to 1.7.2
  docs/external-runtime-deps.md
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: chore, component/containerd, backport/release-1.27

#3261 Sort inttests alphabetically
  inttest/Makefile.variables
Labels: chore, area/smoke-tests

#3268 DNS fixes in docker entrypoint for both legacy and nft
  docker-entrypoint.sh
Labels: bug

#3269 Don't mention latest Docker tag in docs
  docs/k0s-in-docker.md
Labels: documentation, backport/release-1.27

#3277 Fix typo in function name
  internal/pkg/sysinfo/probes/linux/cgroup_controllers.go
  internal/pkg/sysinfo/probes/linux/cgroup_v1.go
  internal/pkg/sysinfo/probes/linux/cgroup_v2.go
Labels: chore

#3274 [release-1.26] Update all versions in docs to 1.26.6
  .github/workflows/publish-docs-manual.yml
  docs/airgap-install.md
  docs/autopilot-multicommand.md
  docs/configuration.md
  docs/docker-shim.md
  docs/install.md
  docs/k0s-in-docker.md
  docs/k0s-multi-node.md
  docs/nllb.md
  docs/raspberry-pi4.md
  docs/releases.md
  docs/reset.md
  docs/upgrade.md
  docs/worker-node-config.md
Labels: documentation

#3278 Bump cri-dockerd to v0.3.4
  inttest/footloose-alpine/Dockerfile
Labels: chore, area/smoke-tests

#3273 [Backport release-1.26] Don't mention latest Docker tag in docs
  docs/k0s-in-docker.md
Labels: documentation

#3275 [Backport release-1.25] Don't mention latest Docker tag in docs
  docs/k0s-in-docker.md
Labels: documentation

#3288 Canonical spelling of AppArmor
  docs/raspberry-pi4.md
  internal/pkg/sysinfo/host_linux.go
  internal/pkg/sysinfo/probes/linux/apparmor.go
Labels: chore

#3287 Update to Alpine 3.18.2
  embedded-bins/Makefile.variables
Labels: chore

#3262 Exclude cluster config status from config create
  pkg/apis/k0s/v1beta1/clusterconfig_types.go
  pkg/apis/k0s/v1beta1/clusterconfig_types_test.go
  pkg/apis/k0s/v1beta1/zz_generated.deepcopy.go
Labels: bug, area/configuration, backport/release-1.27

#3293 Bump go to 1.20.6
  embedded-bins/Makefile.variables
Labels: backport/release-1.27

#3302 Bump runc to 1.1.8
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: backport/release-1.24, backport/release-1.25, backport/release-1.26, backport/release-1.27
