Repository k0sproject/k0s, pull requests merged in 2023-10, with the labels that each got.

#3541 Remove legacy Go build tags
  cmd/backup/backup.go
  cmd/restore/restore.go
  hack/gen-bindata/cmd/main.go
  hack/gen-bindata/gen_bindata.go
  hack/gen-bindata/gen_bindata_test.go
  hack/validate-images/main.go
  internal/pkg/dir/dir_posix_test.go
  internal/pkg/dir/dir_windows_test.go
  internal/pkg/sysinfo/host_linux.go
  internal/pkg/sysinfo/host_other.go
  internal/pkg/sysinfo/probes/disk_linux.go
  internal/pkg/sysinfo/probes/disk_other.go
  internal/pkg/sysinfo/probes/linux/apparmor.go
  internal/pkg/sysinfo/probes/linux/cgroup_controllers.go
  internal/pkg/sysinfo/probes/linux/cgroup_v1.go
  internal/pkg/sysinfo/probes/linux/cgroup_v2.go
  internal/pkg/sysinfo/probes/linux/cgroups.go
  internal/pkg/sysinfo/probes/linux/cgroups_test.go
  internal/pkg/sysinfo/probes/linux/kernel.go
  internal/pkg/sysinfo/probes/linux/kernel_test.go
  internal/pkg/sysinfo/probes/linux/linux.go
  internal/pkg/sysinfo/probes/linux/linux_test.go
  internal/pkg/sysinfo/probes/linux/procfs.go
  internal/pkg/sysinfo/probes/linux/types.go
  internal/pkg/sysinfo/probes/linux/types_arm.go
  internal/pkg/sysinfo/probes/linux/ulimit.go
  internal/pkg/sysinfo/probes/memory_linux.go
  internal/pkg/sysinfo/probes/memory_linux_test.go
  internal/pkg/sysinfo/probes/memory_other.go
  pkg/backup/config.go
  pkg/backup/etcd.go
  pkg/backup/filesystem.go
  pkg/backup/filesystem_posix_test.go
  pkg/backup/manager.go
  pkg/backup/sqlitedb.go
  pkg/backup/util.go
  pkg/component/worker/kernelsetup.go
  pkg/component/worker/kernelsetup_linux.go
  pkg/config/runtime_posix.go
  pkg/constant/constant_posix.go
  pkg/constant/constant_windows.go
  pkg/supervisor/detachattr.go
  pkg/supervisor/pingpong_posix.go
  pkg/supervisor/supervisor_windows.go
  pkg/telemetry/sysinfo.go
  pkg/telemetry/sysinfo_linux.go
Labels: chore

#3540 Add -trimpath and -buildvcs=false to go build args
  Makefile
Labels: chore

#3539 Disable race checker conditionally in Makefile
  .github/workflows/go.yml
  Makefile
Labels: area/ci, chore

#3538 Update kubernetes pause image to v3.9, for real
  pkg/constant/constant_posix.go
Labels: chore

#3549 Update to Alpine 3.18.4
  embedded-bins/Makefile.variables
Labels: chore

#3553 Fix image detection for kubelet metrics in inttests
  inttest/common/util.go
Labels: chore, area/smoke-tests

#3558 Bump Go to v1.20.9
  embedded-bins/Makefile.variables
Labels: security fix, chore, backport/release-1.28

#3550 Bump troubleshoot to v0.73.0
  inttest/footloose-alpine/Dockerfile
Labels: chore, area/smoke-tests

#3572 Reclaim GitHub Runner disk space
  .github/workflows/go.yml
  .github/workflows/reclaim-runner-disk-space.bash
  inttest/network-conformance/network_test.go
Labels: bug, area/ci, area/smoke-tests, backport/release-1.28

#3580 [Backport release-1.27] Reclaim GitHub Runner disk space
  .github/workflows/go.yml
  .github/workflows/reclaim-runner-disk-space.bash
Labels: bug, area/ci, area/smoke-tests, backport/release-1.26

#3077 Revisit devices and freezer controller detection for cgroup v2
  docs/raspberry-pi4.md
  go.mod
  go.sum
  internal/pkg/sysinfo/probes/linux/cgroup_controllers.go
  internal/pkg/sysinfo/probes/linux/cgroup_v2.go
  internal/pkg/sysinfo/probes/linux/cgroups_test.go
Labels: bug

#3570 Bump Go to v1.20.10
  embedded-bins/Makefile.variables
Labels: security fix, backport/release-1.28

#3597 Remove remnants of latest k0s Docker image tags in docs
  docs/examples/ambassador-ingress.md
  docs/k0s-in-docker.md
Labels: documentation, chore, backport/release-1.28

#3602 Remove custom Docker networks from integration tests
  inttest/airgap/airgap_test.go
  inttest/ap-airgap/airgap_test.go
  inttest/ap-ha3x3/ha3x3_test.go
  inttest/ap-quorum/quorum_test.go
  inttest/ap-quorumsafety/quorumsafety_test.go
  inttest/ap-selector/selector_test.go
  inttest/common/footloosesuite.go
  inttest/kubeletcertrotate/kubeletcertrotate_test.go
Labels: bug, area/smoke-tests

#3583 Bump cri-dockerd to v0.3.5
  inttest/footloose-alpine/Dockerfile
Labels: chore

#3607 Drop "multiarch manifest problem" mention from airgap doc
  docs/airgap-install.md
Labels: documentation, backport/release-1.28

#3571 [Backport release-1.27] Bump Go to v1.20.10
  embedded-bins/Makefile.variables
Labels: security fix, chore, backport/release-1.26

#3615 Add Amazon Linux 2023 to OS testing matrix
  .github/workflows/ostests-matrix.yaml
  hack/ostests/README.md
  hack/ostests/modules/os/main.tf
  hack/ostests/modules/os/os_al2023.tf
Labels: enhancement, area/ci

#3609 Add label selector also when watching
  pkg/kubernetes/watch/watcher.go
Labels: bug, backport/release-1.28

#3612 Add missing v prefix to k0s Docker tags in docs
  docs/examples/ambassador-ingress.md
  docs/k0s-in-docker.md
Labels: bug, documentation, backport/release-1.28

#3576 [Backport release-1.28] Fixes for CVE-2023-44487
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
Labels: security fix, dependencies, go, backport/release-1.27

#3614 [Backport release-1.26] Bump Go to v1.20.10
  embedded-bins/Makefile.variables
Labels: security fix, chore, backport/release-1.25

#3605 Bump Kubernetes to v1.28.3
  .github/workflows/publish-docs-manual.yml
  docs/autopilot.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/constant/constant_shared.go
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore, backport/release-1.28

#3584 Bump troubleshoot to v0.76.0
  inttest/footloose-alpine/Dockerfile
Labels: chore, area/smoke-tests

#3552 Remove superfluous Go build tags
  internal/pkg/dir/dir_windows_test.go
  internal/pkg/sysinfo/host_linux.go
  internal/pkg/sysinfo/probes/disk_linux.go
  internal/pkg/sysinfo/probes/linux/types_arm.go
  internal/pkg/sysinfo/probes/memory_linux.go
  internal/pkg/sysinfo/probes/memory_linux_test.go
  pkg/component/worker/kernelsetup_linux.go
  pkg/constant/constant_windows.go
  pkg/supervisor/supervisor_windows.go
  pkg/telemetry/sysinfo_linux.go
Labels: chore

#3577 [Backport release-1.27] Fixes for CVE-2023-44487
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
Labels: security fix, dependencies, go, backport/release-1.26

#3635 [Backport release-1.26] Fixes for CVE-2023-44487
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
Labels: security fix, dependencies, go, backport/release-1.25

#3638 [release-1.26] Bump Kubernetes to v1.26.10
  .github/workflows/publish-docs-manual.yml
  docs/airgap-install.md
  docs/autopilot-multicommand.md
  docs/autopilot.md
  docs/configuration.md
  docs/docker-shim.md
  docs/install.md
  docs/k0s-in-docker.md
  docs/k0s-multi-node.md
  docs/nllb.md
  docs/raspberry-pi4.md
  docs/releases.md
  docs/reset.md
  docs/upgrade.md
  docs/worker-node-config.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/conformance/README.md
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/constant/constant_shared.go
Labels: chore

#3567 Bump containerd to 1.7.7
  docs/external-runtime-deps.md
  docs/nllb.md
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, component/containerd, backport/release-1.27, backport/release-1.28

#3641 Fix "executable in PATH" sysprobe
  docs/raspberry-pi4.md
  internal/pkg/sysinfo/host_linux.go
  internal/pkg/sysinfo/probes/executables.go
Labels: bug, area/worker, area/cli, backport/release-1.28

#3634 Bump k0sctl to v0.16.0
  .github/workflows/check-network.yaml
  .github/workflows/ostests-e2e.yaml
  docs/nllb.md
  hack/ostests/README.md
  hack/ostests/modules/os/os_alpine_3_17_userdata.tftpl
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/k0sctl/k0sctl_test.go
Labels: area/ci, chore

#3585 Add a PodDisruptionBudget for CoreDNS
  inttest/basic/basic_test.go
  pkg/component/controller/coredns.go
Labels: area/controlplane

#3645 [Backport release-1.28] Bump containerd to 1.7.7
  docs/external-runtime-deps.md
  docs/nllb.md
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, component/containerd, backport/release-1.27

#3622 [release-1.27] Bump Kubernetes to v1.27.7
  docs/autopilot.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/conformance/README.md
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/constant/constant_shared.go
Labels: chore

#3637 [Backport release-1.25] Partial fixes for CVE-2023-44487
  go.mod
  go.sum
Labels: security fix, dependencies, go

#3564 Make "k0s config validate" display errors
  cmd/config/validate.go
  cmd/config/validate_test.go
Labels: bug, area/configuration, area/cli, backport/release-1.25, backport/release-1.26, backport/release-1.27

#3633 Fix helm race condition
  cmd/controller/controller.go
  pkg/component/controller/extensions_controller.go
  pkg/helm/helm.go
Labels: bug, backport/release-1.25, backport/release-1.26, backport/release-1.27, backport/release-1.28

#3640 Rename pkg/context to k0scontext to avoid named imports
  cmd/controller/controller.go
  pkg/autopilot/controller/updates/clusterinfo.go
  pkg/k0scontext/context.go
Labels: chore

#3646 Bump envoy to v1.27.1
  pkg/constant/constant_shared.go
Labels: security fix

#3650 [Backport release-1.27] Fix helm race condition
  cmd/controller/controller.go
  pkg/component/controller/extensions_controller.go
  pkg/helm/helm.go
Labels: bug, area/helm, backport/release-1.26

#3542 Forward SOURCE_DATE_EPOCH to embedded k8s binaries
  Makefile
  embedded-bins/Makefile
  embedded-bins/Makefile.variables
  embedded-bins/kubernetes/Dockerfile
Labels: chore

#3660 Bump containerd to v1.7.8
  docs/external-runtime-deps.md
  docs/nllb.md
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, component/containerd, backport/release-1.28

#3661 Bump etcd to v3.5.10
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/controlplane, area/etcd, chore, backport/release-1.28

#3663 [Backport release-1.28] Bump etcd to v3.5.10
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/controlplane, area/etcd, chore, backport/release-1.27

#3664 Only include envoy image in default config if images should be included
  cmd/config/create.go
  cmd/config/create_test.go
  docs/configuration.md
  pkg/apis/k0s/v1beta1/nllb.go
Labels: bug, area/cli, backport/release-1.28
