Repository k0sproject/k0s, pull requests merged in 2023-11, with the labels that each got.

#3665 [release-1.28] Bump Envoy to v1.24.12
  pkg/constant/constant_shared.go
Labels: security fix, area/worker, backport/release-1.27

#3662 [Backport release-1.28] Bump containerd to v1.7.8
  docs/external-runtime-deps.md
  docs/nllb.md
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, component/containerd, backport/release-1.27

#3674 [Backport release-1.27] Bump etcd to v3.5.10
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/controlplane, area/etcd, chore, backport/release-1.26

#3677 [release-1.26] Bump Envoy to v1.24.12
  docs/configuration.md
  pkg/constant/constant_shared.go
Labels: security fix, area/worker

#3675 [Backport release-1.26] Bump etcd to v3.5.10
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/controlplane, area/etcd, chore

#3678 Bump runc to v1.1.10
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, backport/release-1.25, backport/release-1.26, backport/release-1.27, backport/release-1.28

#3676 [release-1.25] Bump etcd binary to v3.5.10
  embedded-bins/Makefile.variables
Labels: area/controlplane, area/etcd, chore

#3679 [Backport release-1.26] Fix helm race condition
  pkg/component/controller/extensions_controller.go
  pkg/helm/helm.go
Labels: backport/release-1.25

#3681 [Backport release-1.28] Bump runc to v1.1.10
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, backport/release-1.27

#3682 [Backport release-1.27] Bump runc to v1.1.10
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, backport/release-1.26

#3683 [Backport release-1.26] Bump runc to v1.1.10
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, backport/release-1.25

#3690 [release-1.25] Bump Kubernetes to v1.25.15
  docs/airgap-install.md
  docs/autopilot-multicommand.md
  docs/autopilot.md
  docs/configuration.md
  docs/docker-shim.md
  docs/examples/ambassador-ingress.md
  docs/install.md
  docs/k0s-in-docker.md
  docs/k0s-multi-node.md
  docs/raspberry-pi4.md
  docs/releases.md
  docs/reset.md
  docs/upgrade.md
  docs/worker-node-config.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  inttest/conformance/README.md
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/constant/constant_shared.go
Labels: chore

#3695 Add Amazon Linux 2023 to nightly OS test runs
  .github/workflows/ostests-nightly.yaml
Labels: enhancement, area/ci

#3694 [release-1.28] Bump github.com/docker/docker to v24.0.7+incompatible
  go.mod
  go.sum
Labels: security fix, dependencies, go

#3715 Bump Go to 1.20.11
  embedded-bins/Makefile.variables
Labels: security fix, area/windows, backport/release-1.28

#3718 [release-1.26] Bump Kubernetes to v1.26.11
  .github/workflows/publish-docs-manual.yml
  docs/airgap-install.md
  docs/autopilot-multicommand.md
  docs/autopilot.md
  docs/configuration.md
  docs/docker-shim.md
  docs/examples/ambassador-ingress.md
  docs/install.md
  docs/k0s-in-docker.md
  docs/k0s-multi-node.md
  docs/nllb.md
  docs/raspberry-pi4.md
  docs/releases.md
  docs/reset.md
  docs/upgrade.md
  docs/worker-node-config.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/conformance/README.md
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/constant/constant_shared.go
Labels: security fix, area/windows

#3721 Bump Kine to v0.11.0
  embedded-bins/Makefile.variables
Labels: chore

#3716 Bump Kubernetes to v1.28.4
  .github/workflows/publish-docs-manual.yml
  docs/autopilot.md
  embedded-bins/Makefile.variables
  examples/bootloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/constant/constant_shared.go
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: security fix, area/windows, backport/release-1.28

#3717 [release-1.27] Bump Kubernetes to v1.27.8
  docs/autopilot.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/conformance/README.md
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/constant/constant_shared.go
Labels: security fix, area/windows

#3722 [Backport release-1.27] Bump Go to 1.20.11
  embedded-bins/Makefile.variables
Labels: security fix, area/windows, backport/release-1.26

#3725 [Backport release-1.26] Bump Go to 1.20.11
  embedded-bins/Makefile.variables
Labels: security fix, area/windows, backport/release-1.25

#3723 [release-1.25] Bump Kubernetes to v1.25.16
  docs/airgap-install.md
  docs/autopilot-multicommand.md
  docs/autopilot.md
  docs/configuration.md
  docs/docker-shim.md
  docs/examples/ambassador-ingress.md
  docs/install.md
  docs/k0s-in-docker.md
  docs/k0s-multi-node.md
  docs/raspberry-pi4.md
  docs/releases.md
  docs/reset.md
  docs/upgrade.md
  docs/worker-node-config.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  inttest/conformance/README.md
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/constant/constant_shared.go
Labels: security fix, area/windows

#3742 Fix k0s controller args in autopilot inttests
  inttest/ap-platformselect/platformselect_test.go
  inttest/ap-single/single_test.go
  inttest/ap-updater-periodic/updater_test.go
  inttest/ap-updater/updater_test.go
Labels: bug, area/smoke-tests

#3741 fetch node object from apiserver when (un)cordoning
  pkg/autopilot/controller/signal/k0s/cordon.go
  pkg/autopilot/controller/signal/k0s/uncordon.go
Labels: bug, component/autopilot, backport/release-1.28

#3733 Don't unmount data-dir on k0s reset
  inttest/backup/backup_test.go
  inttest/cli/cli_test.go
  pkg/cleanup/directories.go
Labels: bug, area/cli, backport, area/install

#3746 Silence CLI usage printing on errors at the root command
  cmd/airgap/airgap.go
  cmd/api/api.go
  cmd/backup/backup.go
  cmd/backup/backup_windows.go
  cmd/config/config.go
  cmd/config/validate.go
  cmd/controller/controller.go
  cmd/etcd/etcd.go
  cmd/install/controller.go
  cmd/install/worker.go
  cmd/kubeconfig/kubeconfig.go
  cmd/reset/reset.go
  cmd/restore/restore.go
  cmd/restore/restore_windows.go
  cmd/root.go
  cmd/start/start.go
  cmd/status/status.go
  cmd/stop/stop.go
  cmd/sysinfo/sysinfo.go
  cmd/token/create.go
  cmd/token/list.go
  cmd/token/preshared.go
  cmd/token/token.go
  cmd/validate/validate.go
  cmd/worker/worker.go
Labels: chore, area/cli

#3745 Use a real single node in the ap-single inttest
  inttest/ap-single/single_test.go
Labels: chore, area/smoke-tests, backport/release-1.28

#3760 Remove unused parameters in hack/validate-images
  hack/validate-images/main.go
Labels: area/ci, chore

#3761 Check if Extensions.Storage exists before accessing Type key
  pkg/apis/k0s/v1beta1/clusterconfig_types.go
  pkg/apis/k0s/v1beta1/clusterconfig_types_test.go
  pkg/apis/k0s/v1beta1/extensions.go
Labels: bug, area/configuration, backport/release-1.28

#3755 Bump golangci-lint to v1.55.2
  .golangci.yml
  hack/tools/Makefile.variables
  internal/pkg/sysinfo/probes/linux/cgroup_controllers.go
  internal/pkg/sysinfo/probes/linux/kernel.go
  internal/pkg/sysinfo/probes/linux/linux.go
Labels: area/ci, chore
