Repository k0sproject/k0s, pull requests merged in 2024-10, with the labels that each got.

#4950 Concurrency safe client factory
  cmd/controller/controller.go
  internal/testutil/kube_client.go
  pkg/applier/stack.go
  pkg/autopilot/checks/checks.go
  pkg/component/controller/autopilot.go
  pkg/component/controller/etcd_member_reconciler.go
  pkg/component/controller/metrics.go
  pkg/kubernetes/client.go
Labels: chore

#5064 bug: respect proxy from env when downloading
  internal/http/download.go
Labels: bug, component/autopilot, backport/release-1.31

#5069 Bump kine to 0.13.2
  embedded-bins/Makefile.variables
  pkg/component/controller/kine.go
Labels: backport/release-1.31

#5061 feat: add support for basic auth, insecure tls and headers
  internal/http/download.go
  internal/http/download_test.go
  internal/http/filename_test.go
Labels: chore

#5081 Remove extra colon from docs CPLB config example
  docs/cplb.md
Labels: documentation

#5078 Let the ConfigSource be a regular component
  cmd/controller/controller.go
  pkg/component/controller/clusterconfig/apiconfigsource.go
  pkg/component/controller/clusterconfig/configsource.go
  pkg/component/controller/clusterconfig/staticsource.go
Labels: area/controlplane, area/configuration, chore

#5089 Allow line break HTML elements in Markdown files
  .github/workflows/markdownlint-config.jsonc
Labels: documentation, chore

#5090 Bump markdownlint-cli to v0.42.0
  .github/workflows/docs.yml
Labels: area/ci, chore

#5103 Make contributors code owners as well
  .github/CODEOWNERS
Labels: chore

#5101 Remove the unused file store in a temp folder
  internal/oci/download.go
  internal/oci/download_test.go
Labels: chore

#5104 Integrate ADOPTERS.md in docs
  ADOPTERS.md
  README.md
  docs/adopters.md
  mkdocs.yml
Labels: documentation

#5109 ADR 1: Some formatting nits
  .github/workflows/docs.yml
  .markdownlint.jsonc
  docs/architecture/adr-001-autopilot-oci-basic-auth-support.md
Labels: chore

#5105 Synchronize the repo's and docs README
  README.md
  docs/README.md
  docs/requirements.txt
  mkdocs.yml
Labels: documentation, chore

#5076 Run libseccomp tests in parallel
  embedded-bins/runc/Dockerfile
Labels: chore

#5094 Bump runc to 1.1.15
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: chore, backport/release-1.31

#5137 Introduce supervisor.procHandle interface
  pkg/supervisor/prochandle.go
  pkg/supervisor/prochandle_unix.go
  pkg/supervisor/prochandle_windows.go
  pkg/supervisor/supervisor.go
  pkg/supervisor/supervisor_unix.go
Labels: chore

#5146 Bump Go to v1.22.8
  embedded-bins/Makefile.variables
Labels: chore, backport/release-1.31

#5141 Extend inttest RetryWatchErrors unit test
  inttest/common/util_test.go
Labels: chore

#5111 Don't include the custom theme in the docs
  docs/custom_theme/img/favicon.ico
  mkdocs.yml
Labels: documentation, chore

#5112 Move architecture docs into the architecture subfolder
  docs/architecture/index.md
  docs/architecture/k0s_controller_processes.png
  docs/architecture/k0s_packaging.png
  docs/architecture/k0s_worker_processes.png
  docs/internal/publishing_docs_using_mkdocs.md
  docs/system-monitoring.md
  mkdocs.yml
Labels: documentation, chore

#5142 [Backport release-1.31] Bump runc to 1.1.15
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, backport/release-1.30, component/runc

#5144 Bump runc to v1.2.0
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, component/runc

#5164 [Backport release-1.28] Bump Go to v1.22.8
  embedded-bins/Makefile.variables
Labels: chore

#5153 Bump Kubernetes to v1.31.2
  .github/workflows/publish-docs-manual.yml
  embedded-bins/Makefile.variables
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/constant/constant.go
  static/_crds/k0s/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore, backport/release-1.31

#5145 [release-1.30] Bump Kubernetes to v1.30.6
  embedded-bins/Makefile.variables
  examples/bootloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/constant/constant.go
  static/_crds/v1beta1/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore

#5147 [release-1.29] Bump Kubernetes to v1.29.10
  .github/workflows/publish-docs-manual.yml
  docs/nllb.md
  docs/raspberry-pi4.md
  docs/runtime.md
  docs/worker-node-config.md
  embedded-bins/Makefile.variables
  examples/bootloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/constant/constant_shared.go
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore

#5165 [Backport release-1.30] Bump runc to 1.1.15
  embedded-bins/Makefile.variables
Labels: area/containers, chore, backport/release-1.29, component/runc

#5062 Applier manager improvements
  pkg/applier/manager.go
  pkg/applier/manager_test.go
  pkg/applier/testdata/manager_test/stack1/configmap.yaml
  pkg/applier/testdata/manager_test/stack1/pod.yaml
  pkg/applier/testdata/manager_test/stack2/deploy.yaml
Labels: area/controlplane, chore, backport/release-1.31

#5155 Bump Go to v1.23.2
  build/Dockerfile
  embedded-bins/Makefile.variables
  go.mod
  hack/tool/go.mod
  internal/http/download.go
  internal/http/download_test.go
Labels: chore

#5148 [release-1.28] Bump Kubernetes to v1.28.15
  .github/workflows/publish-docs-manual.yml
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/constant/constant_shared.go
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore

#5067 Let ClusterConfigInitializer apply the api-config stack
  cmd/controller/controller.go
  internal/testutil/fakeclient/tracker.go
  internal/testutil/kube_client.go
  pkg/apis/k0s/v1beta1/clusterconfig_types.go
  pkg/applier/manager.go
  pkg/applier/manager_test.go
  pkg/applier/stack.go
  pkg/component/controller/clusterconfig.go
  pkg/component/controller/clusterconfig_test.go
  pkg/component/controller/etcd_member_reconciler.go
  pkg/kubernetes/client.go
Labels: area/controlplane, chore
