Repository k0sproject/k0s, pull requests merged in 2024-01, with the labels that each got.

#3868 Bump runc to v1.1.11
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, backport/release-1.28

#3874 [Backport release-1.28] Bump runc to v1.1.11
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, backport/release-1.27

#3875 Bump artifact actions
  .github/workflows/build-airgap-image-bundle.yml
  .github/workflows/build-docs.yml
  .github/workflows/build-k0s.yml
  .github/workflows/go.yml
  .github/workflows/ostests-e2e.yaml
  .github/workflows/release.yml
  .github/workflows/sbom-upload.yml
Labels: area/ci, dependencies, github_actions

#3872 [release-1.26] Bump Kubernetes to v1.26.12
  .github/workflows/publish-docs-manual.yml
  docs/airgap-install.md
  docs/autopilot-multicommand.md
  docs/autopilot.md
  docs/configuration.md
  docs/docker-shim.md
  docs/examples/ambassador-ingress.md
  docs/install.md
  docs/k0s-in-docker.md
  docs/k0s-multi-node.md
  docs/nllb.md
  docs/raspberry-pi4.md
  docs/releases.md
  docs/reset.md
  docs/upgrade.md
  docs/worker-node-config.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/conformance/README.md
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/constant/constant_shared.go
Labels: chore

#3871 [release-1.27] Bump Kubernetes to v1.27.9
  .github/workflows/publish-docs-manual.yml
  docs/autopilot.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/conformance/README.md
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/constant/constant_shared.go
Labels: chore

#3876 [Backport release-1.27] Bump runc to v1.1.11
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, backport/release-1.26

#3873 [Backport release-1.26] Bump Go to v1.20.12
  embedded-bins/Makefile.variables
Labels: security fix

#3775 Bump Kubernetes to v1.29.0
  .github/workflows/publish-docs-manual.yml
  docs/autopilot.md
  docs/verifying-signs.md
  embedded-bins/Makefile.variables
  examples/bootloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/applier/applier.go
  pkg/autopilot/checks/checks.go
  pkg/autopilot/controller/plans/cmdprovider/airgapupdate/newplan.go
  pkg/autopilot/controller/plans/cmdprovider/k0supdate/newplan.go
  pkg/component/controller/kubeletconfig_test.go
  pkg/component/controller/workerconfig/reconciler_test.go
  pkg/component/worker/config/config_test.go
  pkg/constant/constant_shared.go
  pkg/kubernetes/rest.go
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore

#3881 [Backport release-1.26] Bump runc to v1.1.11
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore

#3880 [release-1.28] Bump Kubernetes to v1.28.5
  .github/workflows/publish-docs-manual.yml
  docs/autopilot.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/constant/constant_shared.go
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore

#3883 Use reflect.DeepEqual for CoreDNS config comparison
  pkg/component/controller/coredns.go
Labels: bug, area/controlplane

#3882 Add GitHub label action for merge conflicts
  .github/workflows/conflicts.yaml
Labels: area/ci

#3878 Bump k0sctl to v0.17.1
  .github/workflows/check-network.yaml
  .github/workflows/ostests-e2e.yaml
  docs/nllb.md
  hack/ostests/README.md
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/k0sctl/k0sctl_test.go
Labels: area/ci, chore, area/smoke-tests

#3888 [Backport release-1.28] Fix executable suffix typo in build workflow
  .github/workflows/build-k0s.yml
Labels: bug, area/ci

#3890 [Backport release-1.27]: Change AWS TF credentials
  .github/workflows/autopilot-branch-to-latest.yaml
  .github/workflows/check-network.yaml
  .github/workflows/release.yml
Labels: area/ci, chore, backport/release-1.26

#3879 Add CoreDNS deployment to ostests pre-flight checks
  hack/ostests/modules/k0sctl/main.tf
  hack/ostests/modules/k0sctl/outputs.tf
  hack/ostests/modules/k0sctl/pre-flight-checks.sh
Labels: bug, area/ci

#3892 Bump containerd to v1.7.11
  docs/external-runtime-deps.md
  docs/nllb.md
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, component/containerd

#3897 Bump k0sctl used in tests to v0.17.2
  .github/workflows/check-network.yaml
  .github/workflows/ostests-e2e.yaml
  docs/nllb.md
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/k0sctl/k0sctl_test.go
Labels: area/ci, chore, area/k0sctl

#3899 Set Dependabot version bumps to auto-merge
  .github/workflows/dependabot-prs.yaml
Labels: area/ci, chore

#3900 Bump go-sqlite3 to v1.14.19
  Makefile
  go.mod
  go.sum
Labels: chore, area/backup, dependencies

#3891 Remove kubelet-config stack after deprecation in 1.26
  cmd/controller/controller.go
  go.mod
  inttest/ap-ha3x3/ha3x3_test.go
  pkg/applier/applier.go
  pkg/component/controller/kubeletconfig.go
  pkg/component/controller/kubeletconfig_test.go
  pkg/config/cli.go
  pkg/config/cli_test.go
  pkg/constant/constant_shared.go
Labels: area/controlplane, chore

#3909 Bump Go to v1.21.6
  embedded-bins/Makefile.variables
  go.mod
  hack/tool/go.mod
Labels: chore

#3910 [release-1.28] Bump Go to v1.20.13
  embedded-bins/Makefile.variables
Labels: chore, backport/release-1.27

#3916 Bump kine to v0.11.3
  embedded-bins/Makefile.variables
Labels: area/controlplane, chore, component/kine, backport/release-1.28

#3911 [Backport release-1.27] Bump Go to v1.20.13
  embedded-bins/Makefile.variables
Labels: chore, backport/release-1.26

#3912 [Backport release-1.26] Bump Go to v1.20.13
  embedded-bins/Makefile.variables
Labels: chore

#3913 Remove image validation check
  .github/workflows/go.yml
  Makefile
  go.mod
  go.sum
  hack/validate-images/main.go
Labels: area/ci, chore

#3902 Add `extraArgs` config for kube-router
  docs/configuration.md
  pkg/apis/k0s/v1beta1/kuberouter.go
  pkg/apis/k0s/v1beta1/zz_generated.deepcopy.go
  pkg/component/controller/kuberouter.go
  pkg/component/controller/kuberouter_test.go
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: enhancement, area/network, component/kube-router

#3925 Bump controller-tools to v0.14.0
  Makefile
  hack/tools/Makefile.variables
  static/manifests/autopilot/CustomResourceDefinition/autopilot.k0sproject.io_controlnodes.yaml
  static/manifests/autopilot/CustomResourceDefinition/autopilot.k0sproject.io_plans.yaml
  static/manifests/autopilot/CustomResourceDefinition/autopilot.k0sproject.io_updateconfigs.yaml
  static/manifests/helm/CustomResourceDefinition/helm.k0sproject.io_charts.yaml
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore

#3927 Use upload/download to share airgap bundles between tests
  .github/workflows/build-airgap-image-bundle.yml
  .github/workflows/go.yml
Labels: area/ci, chore

#3908 Automate k0sctl version setting across test suites
  .github/workflows/check-network.yaml
  .github/workflows/ostests-e2e.yaml
  .github/workflows/release.yml
  inttest/Makefile
  inttest/k0sctl/k0sctl_test.go
Labels: enhancement, area/ci, github_actions

#3905 Provide empty asset offsets without codegen
  .github/workflows/go.yml
  Makefile
  hack/gen-bindata/gen_bindata.go
  hack/gen-bindata/gen_bindata_test.go
  pkg/assets/offsets_other.go
Labels: chore

#3928 Bump containerd to v1.7.12
  .github/dependabot.yml
  docs/external-runtime-deps.md
  docs/nllb.md
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
  pkg/constant/constant_shared_test.go
Labels: area/containers, chore, component/containerd

#3932 [release-1.26] Bump containerd to v1.6.27
  .github/dependabot.yml
  docs/external-runtime-deps.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
  pkg/constant/constant_shared_test.go
Labels: area/containers, chore, component/containerd

#3935 Add k0sctl version lookup to vars.sh
  .github/workflows/check-network.yaml
  .github/workflows/ostests-e2e.yaml
  .github/workflows/prepare-build-env.sh
  .github/workflows/release.yml
  vars.sh
Labels: area/ci, chore

#3941 Remove api-config component flag
  docs/configuration.md
  pkg/config/cli.go
  pkg/constant/constant_shared.go
Labels: area/controlplane, area/cli

#3937 Add external Etcd options to docs
  docs/configuration.md
Labels: documentation, chore, backport/release-1.26, backport/release-1.27, backport/release-1.28

#3947 Correct links in docs
  docs/configuration-validation.md
  docs/configuration.md
  docs/examples/nginx-ingress.md
  docs/high-availability.md
  docs/nllb.md
  docs/troubleshooting.md
Labels: documentation, chore

#3956 Bump etcd to v3.5.11
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/controlplane, area/etcd, chore, backport/release-1.28

#3959 Remove experimental badge from NLLB
  docs/configuration.md
  docs/nllb.md
  pkg/apis/k0s/v1beta1/network.go
  pkg/apis/k0s/v1beta1/nllb.go
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: documentation, chore

#3958 Bump envoy to v1.29.0
  pkg/constant/constant_shared.go
Labels: area/worker, chore

#3948 Bump Kubernetes to v1.29.1
  .github/workflows/publish-docs-manual.yml
  docs/autopilot.md
  docs/verifying-signs.md
  embedded-bins/Makefile.variables
  examples/bootloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/constant/constant_shared.go
Labels: chore

#3952 [release-1.27] Bump Kubernetes to v1.27.10
  .github/workflows/publish-docs-manual.yml
  docs/autopilot.md
  docs/dockershim.md
  docs/k0s-multi-node.md
  docs/nllb.md
  docs/raspberry-pi4.md
  docs/worker-node-config.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/conformance/README.md
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/constant/constant_shared.go
Labels: chore

#3970 Use downloaded cosign binary in release workflow
  .github/workflows/release.yml
Labels: bug, area/ci

#3971 Correctly set compression level in upload-artifact action
  .github/workflows/build-airgap-image-bundle.yml
Labels: bug, area/ci

#3960 Drop k0sctl integration test
  inttest/Makefile
  inttest/Makefile.variables
  inttest/k0sctl/.gitignore
  inttest/k0sctl/k0sctl_test.go
Labels: chore, area/smoke-tests

#3981 Install less packages in k0s Docker image
  Dockerfile
Labels: chore
