Repository k0sproject/k0s, pull requests merged in 2024-03, with the labels that each got.

#4118 Harden etcd subcommand usage and validation
  cmd/etcd/leave.go
  cmd/etcd/leave_test.go
  cmd/etcd/list.go
  cmd/etcd/list_test.go
Labels: bug, area/etcd, area/cli, backport/release-1.29

#4105 Use the official musl domain for the git link
  pkg/component/worker/kubelet.go
Labels: chore

#4112 [Backport release-1.29] Bump helm.sh/helm/v3 from 3.14.1 to 3.14.2
  go.mod
  go.sum
Labels: security fix, dependencies, go

#4027 Bump metrics-server to v0.7.0
  docs/configuration.md
  docs/raspberry-pi4.md
  pkg/constant/constant_shared.go
Labels: chore, component/metrics-server

#4120 Move Containerd component into the containerd subpackage
  cmd/worker/worker.go
  pkg/component/worker/containerd/component.go
  pkg/component/worker/containerd/component_test.go
  pkg/component/worker/containerd/configurer.go
  pkg/component/worker/containerd/configurer_test.go
  pkg/component/worker/containerd/utils_linux.go
  pkg/component/worker/containerd/utils_windows.go
Labels: area/worker, chore, component/containerd

#4115 Bump Go to v1.22.0
  embedded-bins/Makefile.variables
  go.mod
  hack/tool/go.mod
Labels: chore

#4081 Bump envoy to v1.29.1
  pkg/constant/constant_shared.go
Labels: security fix, backport/release-1.29

#4150 [Backport release-1.28] bug: retry saving helm chart object status
  pkg/component/controller/extensions_controller.go
Labels: bug, area/helm, backport/release-1.26, backport/release-1.27

#4155 Bump containerd 1.7.14
  docs/airgap-install.md
  docs/external-runtime-deps.md
  docs/nllb.md
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/controlplane, area/etcd, backport/release-1.29

#4169 [Backport release-1.29] Bump containerd 1.7.14
  docs/external-runtime-deps.md
  docs/nllb.md
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, component/containerd

#4029 Wrap errors correctly
  cmd/backup/backup_unix.go
  cmd/controller/controller.go
  cmd/etcd/list.go
  cmd/install/controller.go
  cmd/install/install.go
  cmd/reset/reset.go
  inttest/common/bootloosesuite.go
  pkg/apis/k0s/v1beta1/network.go
  pkg/applier/stack.go
  pkg/autopilot/controller/readyprober.go
  pkg/autopilot/controller/root_controller.go
  pkg/autopilot/controller/updates/clusterinfo.go
  pkg/backup/manager_unix.go
  pkg/backup/sqlitedb_unix.go
  pkg/backup/util_unix.go
  pkg/cleanup/bridge_linux.go
  pkg/cleanup/cleanup_unix.go
  pkg/cleanup/cni.go
  pkg/cleanup/containers.go
  pkg/cleanup/directories.go
  pkg/cleanup/services.go
  pkg/component/controller/apiserver.go
  pkg/component/controller/calico.go
  pkg/component/controller/clusterConfig.go
  pkg/component/controller/controllermanager.go
  pkg/component/controller/controllersleasecounter.go
  pkg/component/controller/coredns.go
  pkg/component/controller/crd.go
  pkg/component/controller/csrapprover.go
  pkg/component/controller/etcd.go
  pkg/component/controller/kine.go
  pkg/component/controller/konnectivity.go
  pkg/component/controller/konnectivityagent.go
  pkg/component/controller/leaderelector/leasepool.go
  pkg/component/controller/scheduler.go
  pkg/component/controller/windowsstackcomponent.go
  pkg/component/status/status.go
  pkg/component/worker/autopilot.go
  pkg/component/worker/kubelet.go
  pkg/component/worker/ocibundle.go
  pkg/helm/helm.go
  pkg/install/service.go
  pkg/supervisor/supervisor_unix.go
  pkg/supervisor/supervisor_unix_test.go
  pkg/telemetry/telemetry.go
Labels: chore

#4168 [Backport release 1.29] Fix CVE-2024-24786
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
Labels: security fix, dependencies, go, backport/release-1.28

#4171 [release-1.29] Bump Go to v1.21.8
  embedded-bins/Makefile.variables
  go.mod
  hack/tool/go.mod
Labels: security fix, chore, backport/release-1.28

#4170 Bump Go to v1.22.1
  embedded-bins/Makefile.variables
  go.mod
  hack/tool/go.mod
Labels: security fix, chore

#4184 [Backport release 1.28] Fix CVE-2024-24786
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
Labels: security fix, dependencies, go, backport/release-1.27

#4185 [release-1.26] Bump Kubernetes to v1.26.15
  .github/workflows/publish-docs-manual.yml
  docs/airgap-install.md
  docs/autopilot-multicommand.md
  docs/autopilot.md
  docs/configuration.md
  docs/docker-shim.md
  docs/examples/ambassador-ingress.md
  docs/install.md
  docs/k0s-in-docker.md
  docs/k0s-multi-node.md
  docs/nllb.md
  docs/raspberry-pi4.md
  docs/releases.md
  docs/reset.md
  docs/upgrade.md
  docs/worker-node-config.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/conformance/README.md
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/constant/constant_shared.go
Labels: chore

#4191 [Backport release-1.28] Bump Go to v1.21.8
  embedded-bins/Makefile.variables
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
Labels: security fix, backport/release-1.27

#4203 Bump troubleshoot to v0.84.1
  inttest/bootloose-alpine/Dockerfile
Labels: chore, area/smoke-tests

#4199 [Backport release-1.27] Bump Go to v1.21.8
  embedded-bins/Makefile.variables
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
Labels: security fix, backport/release-1.26

#3903 Remove some workarounds for self-hosted arm64 runners
  .github/workflows/go.yml
  .github/workflows/release.yml
Labels: area/ci, chore

#4187 [release-1.28] Bump Kubernetes to v1.28.8
  .github/workflows/publish-docs-manual.yml
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/constant/constant_shared.go
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore

#4188 Bump Kubernetes to v1.29.3
  .github/workflows/publish-docs-manual.yml
  embedded-bins/Makefile.variables
  examples/bootloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/constant/constant.go
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore, backport/release-1.29

#4204 Bump cri-dockerd to v0.3.11
  inttest/bootloose-alpine/Dockerfile
Labels: chore, area/smoke-tests

#4205 [Backport release 1.27] Fix CVE-2024-24786
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
Labels: security fix, dependencies, go

#4201 Bump metrics-server to v0.7.1
  docs/configuration.md
  docs/raspberry-pi4.md
  pkg/constant/constant.go
Labels: chore, component/metrics-server

#4202 Bump golangci-lint to v1.57.1
  hack/tools/Makefile.variables
Labels: area/ci, chore

#4209 Wrap errors correctly, part 2
  cmd/backup/backup_unix.go
  pkg/applier/stack.go
  pkg/component/controller/konnectivity.go
  pkg/supervisor/supervisor_unix.go
Labels: chore

#4156 Bump envoy to v1.29.2
  pkg/constant/constant.go
Labels: chore, backport/release-1.29

#4186 [release-1.27] Bump Kubernetes to v1.27.12
  .github/workflows/publish-docs-manual.yml
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/conformance/README.md
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/constant/constant_shared.go
Labels: chore

#4208 Bump kine to v0.11.7
  embedded-bins/Makefile.variables
Labels: area/controlplane, chore, component/kine, backport/release-1.29

#4160 Pass along containerd config as return value
  docs/runtime.md
  pkg/component/worker/containerd/component.go
  pkg/component/worker/containerd/configurer.go
  pkg/component/worker/containerd/configurer_test.go
Labels: area/configuration, chore, component/containerd

#4214 Update and enhance reset docs
  docs/reset.md
  mkdocs.yml
Labels: documentation
