Repository k0sproject/k0s, pull requests merged in 2024-11, with the labels that each got.

#5176 Bump runc to 1.2.1
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, component/runc

#5181 Fix etcd peer URL to support ipv6
  pkg/apis/k0s/v1beta1/storage.go
  pkg/backup/etcd_unix.go
  pkg/component/controller/etcd.go
  pkg/component/controller/etcd_member_reconciler.go
Labels: bug, area/network, component/etcd, backport/release-1.29, backport/release-1.30, backport/release-1.31

#5203 Bump Go to v1.23.3
  build/Dockerfile
  embedded-bins/Makefile.variables
Labels: chore

#5204 [release-1.31] Bump Go to v1.22.9
  build/Dockerfile
  embedded-bins/Makefile.variables
Labels: chore, backport/release-1.30

#5206 Bump golangci-lint to v1.62.0
  hack/tools/Makefile.variables
  pkg/applier/manager.go
Labels: area/ci, chore

#5205 Bump troubleshoot to v0.109.0
  inttest/bootloose-alpine/Dockerfile
Labels: area/ci, chore

#5220 Add releases page for quick install in airgapped environment
  docs/install.md
Labels: backport/release-1.28, backport/release-1.29, backport/release-1.30, backport/release-1.31

#5221 Enable dupwords linter
  .golangci.yml
  cmd/airgap/listimages_test.go
  inttest/common/autopilot/waitfor.go
  inttest/customca/customca_test.go
  pkg/apis/helm/v1beta1/chart_types.go
  pkg/apis/k0s/v1beta1/extensions.go
  pkg/component/controller/cplb_unix.go
  pkg/component/worker/utils.go
  pkg/constant/constant_test.go
  pkg/debounce/debounce.go
  pkg/install/linux_sysv.go
  pkg/install/linux_upstart.go
  static/_crds/helm/helm.k0sproject.io_charts.yaml
  static/_crds/k0s/k0s.k0sproject.io_clusterconfigs.yaml
Labels: area/ci, chore

#5207 Bump kine to v0.13.3
  embedded-bins/Makefile.variables
  pkg/component/controller/kine.go
Labels: area/controlplane, chore, component/kine

#5240 Enable copyloopvar linter
  .golangci.yml
  inttest/bind-address/bind_address_test.go
  inttest/etcdmember/etcdmember_test.go
  inttest/nllb/nllb_test.go
  pkg/autopilot/controller/readyprober.go
  pkg/component/worker/config/loader.go
  pkg/kubernetes/watch/watcher_test.go
  pkg/token/joinclient_test.go
Labels: area/ci, chore

#5218 Enable intrange linter
  .golangci.yml
  internal/testutil/fakeclient/tracker.go
  inttest/ap-controllerworker/controllerworker_test.go
  inttest/ap-ha3x3/ha3x3_test.go
  inttest/ap-quorum/quorum_test.go
  inttest/ap-quorumsafety/quorumsafety_test.go
  inttest/ap-selector/selector_test.go
  inttest/basic/basic_test.go
  inttest/bind-address/bind_address_test.go
  inttest/common/bootloosesuite.go
  inttest/configchange/config_test.go
  inttest/cplb/cplb_test.go
  inttest/dualstack/dualstack_test.go
  inttest/etcdmember/etcdmember_test.go
  inttest/hacontrolplane/hacontrolplane_test.go
  inttest/kubeletcertrotate/kubeletcertrotate_test.go
  inttest/nllb/nllb_test.go
  pkg/apis/k0s/v1beta1/cplb_test.go
  pkg/autopilot/controller/plans/cmdprovider/airgapupdate/schedulablewait.go
  pkg/autopilot/controller/plans/cmdprovider/k0supdate/schedulablewait.go
  pkg/autopilot/controller/plans/cmdprovider/k0supdate/utils/find_test.go
  pkg/autopilot/controller/plans/core/lookup.go
  pkg/autopilot/signaling/v2/marshal.go
  pkg/autopilot/updater/api.go
  pkg/component/controller/cplb_unix.go
  pkg/component/prober/events_test.go
  pkg/debounce/debounce_test.go
  pkg/supervisor/supervisor_test.go
Labels: area/ci, chore

#5208 Bump envoy to v1.31.3
  pkg/constant/constant.go
Labels: security fix, area/worker, backport/release-1.31

#5241 [Backport release-1.30] Bump containerd to 1.7.23
  docs/airgap-install.md
  docs/external-runtime-deps.md
  docs/nllb.md
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, component/containerd

#5245 Bump etcd to v3.5.17
  embedded-bins/Makefile.variables
  go.mod
  go.sum
  pkg/component/controller/etcd.go
Labels: area/controlplane, component/etcd, chore, backport/release-1.31

#5235 Add note to docs that --single cannot be extended
  docs/install.md
  docs/support-dump.md
Labels: documentation

#5229 Enable unconvert linter
  .golangci.yml
  internal/pkg/sysinfo/probes/memory_linux.go
  pkg/apis/autopilot/v1beta2/updateconfig.go
  pkg/autopilot/controller/updates/periodicupdater.go
  pkg/component/controller/extensions_controller.go
  pkg/component/controller/updateprober.go
Labels: chore

#5247 Properly format docker flags in docs
  docs/k0s-in-docker.md
Labels: documentation

#5243 Bump CoreDNS to v1.11.4
  pkg/constant/constant.go
Labels: area/network, chore, backport/release-1.31

#5246 Refactor kubelet config generation
  pkg/component/worker/kubelet.go
Labels: area/configuration, chore, component/kubelet

#5242 [Backport release-1.30] Bump Go to v1.22.9
  embedded-bins/Makefile.variables
Labels: chore, backport/release-1.29

#5239 Enable usestdlibvars linter
  .golangci.yml
  internal/http/download.go
  pkg/autopilot/channels/channelclient.go
  pkg/component/worker/static_pods_test.go
Labels: area/ci, chore

#5234 Enable unparam linter
  .golangci.yml
  internal/pkg/file/atomic_test.go
  inttest/bind-address/bind_address_test.go
  pkg/applier/manager_test.go
  pkg/autopilot/controller/plans/init.go
  pkg/autopilot/controller/updates/periodicupdater.go
  pkg/autopilot/controller/updates/updater.go
  pkg/certificate/manager.go
  pkg/component/controller/workerconfig/reconciler_test.go
  pkg/component/prober/prober.go
  pkg/kubernetes/watch/watcher_test.go
Labels: chore

#5262 Include adopters in docs so that ADOPTERS.md is not a symlink
  ADOPTERS.md
  docs/adopters.md
Labels: documentation, chore

#5256 [Backport release-1.30] Bump etcd to v3.5.17
  embedded-bins/Makefile.variables
  go.mod
  go.sum
  pkg/component/controller/etcd.go
Labels: area/controlplane, component/etcd, chore, backport/release-1.29

#5185 Don't try to compile CPLB on darwin
  pkg/component/controller/cplb_linux.go
  pkg/component/controller/cplb_other.go
Labels: chore

#5272 Fix nolintlint
  pkg/kubernetes/watch/watcher_test.go
Labels: chore

#5263 Overhaul container entrypoint script and Docker docs
  Dockerfile
  docker-entrypoint.sh
  docs/compose.yaml
  docs/k0s-in-docker.md
Labels: documentation, enhancement

#5223 Enable nosprintfhostport linter
  .golangci.yml
  inttest/customports/customports_test.go
  pkg/apis/k0s/v1beta1/api.go
  pkg/apis/k0s/v1beta1/network.go
Labels: area/ci, chore

#5193 Fix deletion of persistent data with k0s reset
  docs/reset.md
  inttest/reset/clutter-data-dir.sh
  inttest/reset/reset_test.go
  pkg/cleanup/containers.go
  pkg/cleanup/directories.go
  pkg/cleanup/unmount_unix.go
  pkg/cleanup/unmount_windows.go
Labels: bug, backport/release-1.29, backport/release-1.30, backport/release-1.31
