Repository k0sproject/k0s, pull requests merged in 2024-12, with the labels that each got.

#5313 Reuse boolean for toggling the k0s endpoint reconciler
  cmd/controller/controller.go
Labels: chore

#5312 [release-1.31] Bump Go to v1.22.10
  embedded-bins/Makefile.variables
Labels: chore, backport/release-1.30

#5311 Bump Go to v1.23.4
  embedded-bins/Makefile.variables
Labels: chore

#5315 [Backport release-1.29] Bump containerd to 1.7.23
  docs/external-runtime-deps.md
  docs/nllb.md
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, component/containerd

#5314 Bump containerd to v1.7.24
  docs/airgap-install.md
  docs/external-runtime-deps.md
  docs/nllb.md
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, component/containerd, backport/release-1.31

#5297 Add troubleshooting section on regenerating CAs
  docs/custom-ca.md
  docs/k0s-multi-node.md
  docs/runtime.md
  docs/troubleshooting/FAQ.md
  docs/troubleshooting/certificate-authorities.md
  docs/troubleshooting/logs.md
  docs/troubleshooting/support-dump.md
  docs/troubleshooting/troubleshooting.md
  mkdocs.yml
Labels: documentation

#5294 Replace requests module with standard library http
  go.mod
  go.sum
  pkg/node/nodehostname.go
  pkg/node/nodename.go
  pkg/node/nodename_other.go
  pkg/node/nodename_test.go
  pkg/node/nodename_windows.go
  pkg/node/nodename_windows_test.go
Labels: chore

#5329 Don't check for dynamic config when listing images
  cmd/airgap/listimages.go
Labels: chore, area/cli

#5194 Let cleanup steps hold their own data
  cmd/reset/reset.go
  pkg/cleanup/cleanup.go
  pkg/cleanup/containers.go
  pkg/cleanup/directories.go
  pkg/cleanup/services.go
  pkg/cleanup/users.go
Labels: chore

#5305 Move kubelet config file into run directory
  pkg/component/worker/kubelet.go
Labels: area/configuration, chore, component/kubelet

#5316 Bump CoreDNS to v1.12.0
  pkg/constant/constant.go
Labels: area/network, chore, backport/release-1.31

#5340 Bump runc to v1.2.3
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, component/runc

#5320 [release-1.30] Bump Kubernetes to v1.30.7
  .github/workflows/publish-docs-manual.yml
  embedded-bins/Makefile.variables
  examples/bootloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/constant/constant.go
  static/_crds/v1beta1/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore

#5325 [release-1.29] Bump Kubernetes to v1.29.11
  .github/workflows/publish-docs-manual.yml
  embedded-bins/Makefile.variables
  examples/bootloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/constant/constant_shared.go
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore

#5318 Bump Kubernetes to v1.31.3
  .github/workflows/publish-docs-manual.yml
  embedded-bins/Makefile.variables
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/constant/constant.go
  static/_crds/k0s/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore

#5344 [release-1.30] Bump Alpine to v3.19.4
  embedded-bins/Makefile.variables
Labels: chore, backport/release-1.29

#5345 Bump Python verison for docs to v3.13.1
  docs/Makefile.variables
Labels: chore

#5339 [Backport release-1.31] Bump containerd to v1.7.24
  docs/airgap-install.md
  docs/external-runtime-deps.md
  docs/nllb.md
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, component/containerd, backport/release-1.30

#5330 Honor IO errors in list-images sub-command
  cmd/airgap/listimages.go
  cmd/airgap/listimages_test.go
Labels: bug, area/cli

#5348 Use fixed kube-router image
  pkg/constant/constant.go
Labels: bug, area/network, component/kube-router, backport/release-1.31

#5346 [Backport release-1.29] Fix deletion of persistent data with k0s reset
  docs/reset.md
  inttest/reset/clutter-data-dir.sh
  inttest/reset/reset_test.go
  pkg/cleanup/containers.go
  pkg/cleanup/directories.go
  pkg/cleanup/unmount_unix.go
  pkg/cleanup/unmount_windows.go
Labels: bug

#5342 Bump Alpine to v3.21.0
  embedded-bins/Makefile.variables
Labels: chore

#5343 [release-1.31] Bump Alpine to v3.20.3
  embedded-bins/Makefile.variables
Labels: chore

#5349 [Backport release-1.30] Bump containerd to v1.7.24
  docs/airgap-install.md
  docs/external-runtime-deps.md
  docs/nllb.md
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, component/containerd, backport/release-1.29

#5355 [release-1.29] Bump containerd to v1.7.24
  docs/external-runtime-deps.md
  docs/nllb.md
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, component/containerd

#5096 Make possible to build with podman or without docker
  Makefile
Labels: chore

#5361 Bump kine to v0.13.7
  embedded-bins/Makefile.variables
  pkg/component/controller/kine.go
Labels: area/controlplane, chore, component/kine

#5367 Don't print errors when building without git
  Makefile
Labels: chore

#5357 Enable gocritic linter
  .golangci.yml
  cmd/token/invalidate.go
  cmd/token/list.go
  internal/pkg/sysinfo/probes/linux/cgroup_v1.go
  internal/pkg/sysinfo/probes/probes.go
  internal/pkg/sysinfo/probes/util.go
  internal/pkg/sysinfo/sysinfo.go
  internal/testutil/fakeclient/tracker.go
  inttest/kubeletcertrotate/kubeletcertrotate_test.go
  pkg/apis/k0s/v1beta1/clusterconfig_types.go
  pkg/apis/k0s/v1beta1/network.go
  pkg/autopilot/controller/plans/cmdprovider/k0supdate/utils/find_test.go
  pkg/autopilot/controller/readyprober.go
  pkg/autopilot/controller/root_controller.go
  pkg/autopilot/controller/signal/k0s/cordon.go
  pkg/autopilot/controller/signal/k0s/uncordon.go
  pkg/backup/filesystem_unix_test.go
  pkg/component/worker/nllb/reconciler.go
  pkg/k0scloudprovider/provider.go
  pkg/kubernetes/watch/watcher_test.go
  pkg/supervisor/logwriter.go
  pkg/supervisor/supervisor.go
  pkg/token/kubeconfig.go
Labels: chore

#5151 fix: join node creates new cluster when initial etcd sync config fails
  cmd/controller/controller.go
  pkg/component/controller/etcd.go
Labels: backport/release-1.29, backport/release-1.30, backport/release-1.31

#5380 Run unit tests on macOS in CI
  .github/workflows/go.yml
  pkg/cleanup/unmount_linux.go
  pkg/cleanup/unmount_other.go
  pkg/component/worker/containerd/utils_other.go
  pkg/constant/constant_test.go
  pkg/supervisor/supervisor_test.go
Labels: enhancement, area/ci

#5382 Reject unknown sub-commands
  cmd/airgap/airgap.go
  cmd/airgap/listimages.go
  cmd/airgap/listimages_test.go
  cmd/api/api.go
  cmd/backup/backup_unix.go
  cmd/backup/backup_windows.go
  cmd/config/config.go
  cmd/config/config_test.go
  cmd/config/create.go
  cmd/config/edit.go
  cmd/config/status.go
  cmd/config/validate.go
  cmd/controller/controller.go
  cmd/etcd/etcd.go
  cmd/etcd/leave.go
  cmd/etcd/list.go
  cmd/etcd/list_test.go
  cmd/install/controller.go
  cmd/install/install.go
  cmd/install/worker.go
  cmd/kubeconfig/admin.go
  cmd/kubeconfig/kubeconfig.go
  cmd/reset/reset.go
  cmd/root.go
  cmd/root_test.go
  cmd/start/start.go
  cmd/status/status.go
  cmd/stop/stop.go
  cmd/sysinfo/sysinfo.go
  cmd/token/create.go
  cmd/token/invalidate.go
  cmd/token/list.go
  cmd/token/preshared.go
  cmd/token/token.go
  cmd/validate/validate.go
  cmd/version/version.go
  cmd/worker/worker.go
  inttest/customports/customports_test.go
  pkg/autopilot/controller/root_worker.go
  pkg/backup/manager_unix.go
Labels: chore, area/cli

#5383 Some small improvements to inttests
  inttest/common/bootloosesuite.go
  inttest/containerdimports/containerd_imports_test.go
Labels: chore, area/smoke-tests
