Repository k0sproject/k0s, pull requests merged in 2024-09, with the labels that each got.

#4918 Calico v3.28.1
  .github/workflows/go.yml
  pkg/constant/constant.go
  static/manifests/calico/ClusterRole/calico-node.yaml
  static/manifests/calico/CustomResourceDefinition/bgppeers.crd.projectcalico.org.yaml
  static/manifests/calico/CustomResourceDefinition/felixconfigurations.crd.projectcalico.org.yaml
  static/manifests/calico/CustomResourceDefinition/globalnetworkpolicies.crd.projectcalico.org.yaml
  static/manifests/calico/CustomResourceDefinition/networkpolicies.crd.projectcalico.org.yaml
  static/manifests/calico/DaemonSet/calico-node.yaml
Labels: area/network, component/calico

#4941 bug: disable oci bundle loader on byocri
  cmd/worker/worker.go
Labels: bug, area/worker, area/containers, backport/release-1.30

#4676 Deprecate the Calico ipip mode in favor of bird
  docs/configuration.md
  docs/internal/upgrading-calico.md
  docs/networking.md
  pkg/apis/k0s/v1beta1/calico.go
  pkg/apis/k0s/v1beta1/network.go
  pkg/apis/k0s/v1beta1/network_test.go
  pkg/component/controller/calico.go
  pkg/component/controller/windowsstackcomponent.go
  static/_crds/k0s/k0s.k0sproject.io_clusterconfigs.yaml
  static/manifests/calico/DaemonSet/calico-node.yaml
Labels: documentation, area/configuration, chore, component/calico

#4262 Rework users.GetUID
  cmd/controller/certificates.go
  cmd/kubeconfig/create.go
  cmd/kubeconfig/kubeconfig_test.go
  docs/external-runtime-deps.md
  internal/pkg/file/file.go
  internal/pkg/users/users.go
  internal/pkg/users/users_test.go
  pkg/certificate/manager.go
  pkg/component/controller/apiserver.go
  pkg/component/controller/controllermanager.go
  pkg/component/controller/cplb_unix.go
  pkg/component/controller/etcd.go
  pkg/component/controller/kine.go
  pkg/component/controller/konnectivity.go
  pkg/component/controller/scheduler.go
  pkg/install/users.go
Labels: chore

#4895 Replace go-bindata with go:embed
  .gitignore
  Makefile
  embedded-bins/kubernetes/Dockerfile
  hack/tools/Makefile.variables
  pkg/component/controller/calico.go
  pkg/component/controller/calico_test.go
  pkg/component/controller/crd.go
  pkg/component/controller/windowsstackcomponent.go
  static/assets.go
  static/doc.go
Labels: chore

#4945 [Backport release-1.28] Bump Go to v1.22.6
  embedded-bins/Makefile.variables
Labels: chore

#4866 feat(helm): add option to disable helm upgrade force flag
  docs/helm-charts.md
  inttest/addons/addons_test.go
  pkg/apis/helm/v1beta1/chart_types.go
  pkg/apis/helm/v1beta1/zz_generated.deepcopy.go
  pkg/apis/k0s/v1beta1/extensions.go
  pkg/apis/k0s/v1beta1/zz_generated.deepcopy.go
  pkg/component/controller/extensions_controller.go
  pkg/component/controller/extensions_controller_test.go
  pkg/helm/helm.go
  static/_crds/helm/helm.k0sproject.io_charts.yaml
  static/_crds/k0s/k0s.k0sproject.io_clusterconfigs.yaml
Labels: enhancement, area/helm

#4733 Don't store contexts in lease pool structs
  pkg/autopilot/controller/leases.go
  pkg/component/controller/controllersleasecounter.go
  pkg/component/controller/leaderelector/leasepool.go
  pkg/leaderelection/lease_pool.go
  pkg/leaderelection/lease_pool_test.go
Labels: chore

#4832 Use Kubernetes APIs to construct user kubeconfigs
  cmd/kubeconfig/create.go
  cmd/kubeconfig/create_test.go
  cmd/kubeconfig/kubeconfig_test.go
Labels: chore, area/cli

#4951 [doc] Remove non-existant 'targets' field in Autopilot airgapupdate description
  docs/autopilot.md
Labels: bug, documentation, area/configuration, component/autopilot

#4647 Bump Kubernetes to v1.31.0
  .github/dependabot.yml
  .github/workflows/publish-docs-manual.yml
  embedded-bins/Makefile.variables
  examples/bootloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  internal/testutil/fakeclient/tracker.go
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/autopilot/controller/root_controller.go
  pkg/client/clientset/fake/clientset_generated.go
  pkg/client/clientset/typed/autopilot/v1beta2/controlnode.go
  pkg/client/clientset/typed/autopilot/v1beta2/fake/fake_controlnode.go
  pkg/client/clientset/typed/autopilot/v1beta2/fake/fake_plan.go
  pkg/client/clientset/typed/autopilot/v1beta2/fake/fake_updateconfig.go
  pkg/client/clientset/typed/autopilot/v1beta2/plan.go
  pkg/client/clientset/typed/autopilot/v1beta2/updateconfig.go
  pkg/client/clientset/typed/etcd/v1beta1/etcdmember.go
  pkg/client/clientset/typed/etcd/v1beta1/fake/fake_etcdmember.go
  pkg/client/clientset/typed/helm/v1beta1/chart.go
  pkg/client/clientset/typed/helm/v1beta1/fake/fake_chart.go
  pkg/client/clientset/typed/k0s/v1beta1/clusterconfig.go
  pkg/client/clientset/typed/k0s/v1beta1/fake/fake_clusterconfig.go
  pkg/component/controller/workerconfig/reconciler_test.go
  pkg/constant/constant.go
  pkg/constant/constant_test.go
  static/_crds/k0s/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore

#4957 Remove minReadySeconds from kube-router DaemonSet
  pkg/component/controller/kuberouter.go
Labels: bug, area/controlplane, component/kube-router, backport/release-1.30

#4938 Introduce new leader election client
  pkg/leaderelection/client.go
  pkg/leaderelection/client_test.go
  pkg/leaderelection/lease_pool.go
  pkg/leaderelection/lease_pool_test.go
Labels: chore

#4913 Bump metrics-server to v0.7.2
  docs/configuration.md
  docs/raspberry-pi4.md
  pkg/apis/k0s/v1beta1/images_test.go
  pkg/constant/constant.go
Labels: area/worker, chore, component/metrics-server, backport/release-1.30

#4982 Bump etcd to 3.5.16
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/controlplane, area/etcd, chore, backport/release-1.30

#4981 Bump kine to 0.12.2
  embedded-bins/Makefile.variables
  pkg/component/controller/kine.go
Labels: area/controlplane, chore, component/kine

#4979 Bump go to v1.22.7
  embedded-bins/Makefile.variables
Labels: chore, backport/release-1.28, backport/release-1.29, backport/release-1.30

#4989 Download k0sctl-amd64 instead of k0sctl-x86, take 2
  .github/workflows/check-network.yaml
Labels: bug, area/ci

#4985 [Backport release-1.30] Move generated CRDs into their own directory
  Makefile
  pkg/component/controller/crd.go
  static/_crds/autopilot/autopilot.k0sproject.io_controlnodes.yaml
  static/_crds/autopilot/autopilot.k0sproject.io_plans.yaml
  static/_crds/autopilot/autopilot.k0sproject.io_updateconfigs.yaml
  static/_crds/etcd/etcd.k0sproject.io_etcdmembers.yaml
  static/_crds/helm/helm.k0sproject.io_charts.yaml
  static/_crds/v1beta1/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore

#4980 Bump containerd to 1.7.22
  docs/airgap-install.md
  docs/external-runtime-deps.md
  docs/nllb.md
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, component/containerd, backport/release-1.30

#4994 Use a bulleted list for the ADOPTERS file
  ADOPTERS.md
Labels: chore

#4987 [Backport release-1.30] Bump etcd to 3.5.16
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/controlplane, area/etcd, chore, backport/release-1.29

#4958 Wait until containerd is reachable when starting
  pkg/component/worker/containerd/component.go
  pkg/container/runtime/cri.go
  pkg/container/runtime/runtime.go
Labels: area/worker, chore, component/containerd

#4998 [Backport release-1.28] Bump go to v1.22.7
  embedded-bins/Makefile.variables
Labels: chore

#4986 [Backport release-1.30] Bump metrics-server to v0.7.2
  docs/configuration.md
  docs/raspberry-pi4.md
  pkg/apis/k0s/v1beta1/images_test.go
  pkg/constant/constant.go
Labels: area/worker, chore, component/metrics-server, backport/release-1.29

#5002 [release-1.28] Kubernetes 1.28.14
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/constant/constant_shared.go
Labels: chore

#4997 [Backport release-1.30] Bump containerd to 1.7.22
  docs/airgap-install.md
  docs/external-runtime-deps.md
  docs/nllb.md
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, component/containerd, backport/release-1.29

#5003 [Backport release-1.29] Bump containerd to 1.7.22
  docs/external-runtime-deps.md
  docs/nllb.md
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, component/containerd

#5004 [Backport release-1.29] Bump metrics-server to v0.7.2
  docs/configuration.md
  docs/raspberry-pi4.md
  pkg/apis/k0s/v1beta1/images_test.go
  pkg/constant/constant_shared.go
Labels: area/worker, chore, component/metrics-server, backport/release-1.28

#4934 Enable nftables for kube-proxy
  inttest/Makefile
  inttest/Makefile.variables
  inttest/network-conformance/network_test.go
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/apis/k0s/v1beta1/zz_generated.deepcopy.go
  pkg/component/controller/kubeproxy.go
  static/_crds/k0s/k0s.k0sproject.io_clusterconfigs.yaml
Labels: enhancement, area/network, component/kube-proxy

#5024 Create the autopilot client before applying the plan
  inttest/ap-airgap/airgap_test.go
  inttest/ap-controllerworker/controllerworker_test.go
  inttest/ap-platformselect/platformselect_test.go
  inttest/ap-quorum/quorum_test.go
  inttest/ap-quorumsafety/quorumsafety_test.go
  inttest/ap-removedapis/removedapis_test.go
  inttest/ap-selector/selector_test.go
  inttest/ap-single/single_test.go
  inttest/ap-updater-periodic/updater_test.go
  inttest/ap-updater/updater_test.go
  inttest/kubeletcertrotate/kubeletcertrotate_test.go
Labels: bug, area/smoke-tests

#5028 Twitter -> X
  docs/contributors/overview.md
  mkdocs.yml
Labels: documentation, chore

#5031 Call supportbundle binary directly
  inttest/bootloose-alpine/root/usr/local/bin/troubleshoot-k0s-inttest.sh
Labels: chore, area/smoke-tests

#5005 [Backport release-1.30] bug: disable oci bundle loader on byocri
  cmd/worker/worker.go
Labels: bug, area/worker, area/containers, backport/release-1.29

#5033 Remove old stack tests from Autopilot update inttest
  inttest/ap-ha3x3/ha3x3_test.go
Labels: chore, area/smoke-tests

#5035 [Backport release-1.29] bug: disable oci bundle loader on byocri
  cmd/worker/worker.go
Labels: bug, area/worker, area/containers, backport/release-1.28

#5036 Bump kine to v0.13.0
  embedded-bins/Makefile.variables
  pkg/component/controller/kine.go
Labels: area/controlplane, chore, component/kine

#5022 Capture errors when creating new users in inttests
  inttest/common/bootloosesuite.go
Labels: chore, area/smoke-tests

#5029 Replace kubectl apply usage in inttests
  inttest/ap-airgap/airgap_test.go
  inttest/ap-controllerworker/controllerworker_test.go
  inttest/ap-platformselect/platformselect_test.go
  inttest/ap-quorum/quorum_test.go
  inttest/ap-quorumsafety/quorumsafety_test.go
  inttest/ap-removedapis/removedapis_test.go
  inttest/ap-selector/selector_test.go
  inttest/ap-single/single_test.go
  inttest/ap-updater-periodic/updater_test.go
  inttest/ap-updater/updater_test.go
  inttest/common/util.go
  inttest/kubeletcertrotate/kubeletcertrotate_test.go
Labels: chore, area/smoke-tests

#5042 Disable grab download resume
  pkg/autopilot/constant/static.go
  pkg/autopilot/controller/signal/common/download.go
  pkg/autopilot/controller/signal/k0s/apply.go
  pkg/autopilot/controller/signal/k0s/download.go
  pkg/autopilot/download/downloader.go
Labels: bug, component/autopilot, backport/release-1.30

#5048 [Backport release-1.30] chore(backport): make helm timeout backward compatible
  pkg/apis/k0s/v1beta1/extensions.go
  pkg/apis/k0s/v1beta1/extenstions_test.go
  pkg/apis/k0s/v1beta1/zz_generated.deepcopy.go
  pkg/component/controller/extensions_controller.go
  pkg/component/controller/extensions_controller_test.go
  static/_crds/v1beta1/k0s.k0sproject.io_clusterconfigs.yaml
Labels: area/configuration, area/helm

#5020 Replace grab with internal download function
  go.mod
  go.sum
  internal/http/download.go
  internal/http/download_test.go
  internal/http/filename.go
  internal/http/filename_test.go
  internal/io/io.go
  internal/pkg/file/atomic.go
  inttest/common/ssh.go
  pkg/autopilot/controller/signal/common/download.go
  pkg/autopilot/controller/signal/k0s/download.go
  pkg/autopilot/download/downloader.go
  pkg/k0scontext/context.go
  pkg/k0scontext/timeout.go
  pkg/k0scontext/timeout_test.go
Labels: bug, component/autopilot

#5044 Use the correct template when installing as a SystemV service
  pkg/install/darwin_launchd.go
  pkg/install/linux_openrc.go
  pkg/install/linux_systemd.go
  pkg/install/process.go
  pkg/install/service.go
Labels: bug, chore, area/cli, area/install, backport/release-1.28, backport/release-1.29, backport/release-1.30
