Repository k0sproject/k0s, pull requests merged in 2024-06, with the labels that each got.

#4479 Bump Alpine to v3.20
  embedded-bins/Makefile.variables
Labels: chore

#4525 Bump etcd to v3.5.14
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/controlplane, area/etcd, chore, backport/release-1.30

#4530 Don't use the wrong PID in error strings
  pkg/supervisor/supervisor_unix.go
Labels: bug, backport/release-1.30

#4506 Fix docs link to manual k0s install
  docs/install.md
Labels: documentation, chore, backport/release-1.30

#4543 Add GitHub Workflow based DCO check
  .github/workflows/dco.yaml
Labels: area/ci, chore

#4536 Autodetect the k0s APIs to be built
  Makefile
  cmd/controller/controller.go
  pkg/component/controller/crd.go
  static/manifests/k0s/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore

#4549 Ignore dependabot in DCO check
  .github/workflows/dco.yaml
Labels: bug, area/ci

#4434 Make k0s reset fail if it can't reach containerd
  pkg/cleanup/containers.go
  pkg/container/runtime/cri.go
  pkg/container/runtime/runtime.go
Labels: backport/release-1.30

#4553 Bump kine to v0.11.10
  embedded-bins/Makefile.variables
  pkg/component/controller/kine.go
Labels: area/controlplane, chore, component/kine, backport/release-1.30

#4550 Bump Go to v1.22.4
  embedded-bins/Makefile.variables
Labels: security fix, backport/release-1.30

#4566 Remove the wrong default timeout from the Helm docs
  docs/helm-charts.md
Labels: bug, documentation, backport/release-1.30

#4568 Set correct version number in containerd CRI config
  pkg/component/worker/containerd/configurer.go
  pkg/component/worker/containerd/configurer_test.go
Labels: bug, area/configuration, component/containerd, backport/release-1.30

#4535 Use register-gen to generate schema registration boilerplate
  Makefile
  inttest/addons/addons_test.go
  inttest/common/autopilot/waitfor.go
  pkg/apis/autopilot/doc.go
  pkg/apis/autopilot/v1beta2/doc.go
  pkg/apis/autopilot/v1beta2/info.go
  pkg/apis/autopilot/v1beta2/types.go
  pkg/apis/autopilot/v1beta2/updateconfig.go
  pkg/apis/autopilot/v1beta2/zz_generated.register.go
  pkg/apis/etcd/doc.go
  pkg/apis/etcd/v1beta1/doc.go
  pkg/apis/etcd/v1beta1/types.go
  pkg/apis/etcd/v1beta1/zz_generated.register.go
  pkg/apis/helm/doc.go
  pkg/apis/helm/v1beta1/doc.go
  pkg/apis/helm/v1beta1/groupversion_info.go
  pkg/apis/helm/v1beta1/zz_generated.register.go
  pkg/apis/k0s/doc.go
  pkg/apis/k0s/v1beta1/clusterconfig_types.go
  pkg/apis/k0s/v1beta1/doc.go
  pkg/apis/k0s/v1beta1/groupversion_info.go
  pkg/apis/k0s/v1beta1/zz_generated.register.go
  pkg/autopilot/controller/setup.go
  pkg/component/controller/extensions_controller.go
Labels: chore

#4559 Document constraints of dynamic config install
  docs/dynamic-configuration.md
Labels: documentation, backport/release-1.30

#4574 Wait for containerd to be extracted before using it
  pkg/component/worker/containerd/component.go
Labels: bug, area/windows, component/containerd

#4564 [Backport release-1.29] Make k0s reset fail if it can't reach containerd
  pkg/cleanup/containers.go
  pkg/container/runtime/cri.go
  pkg/container/runtime/docker.go
  pkg/container/runtime/runtime.go
Labels: bug, area/cli, backport/release-1.28

#4531 Test PID file handling directly via Supervisor
  internal/testutil/pingpong/pingpong.go
  internal/testutil/pingpong/pingpong.ps1
  internal/testutil/pingpong/pingpong.sh
  internal/testutil/pingpong/pingpong_unix.go
  internal/testutil/pingpong/pingpong_windows.go
  pkg/supervisor/pingpong_unix.go
  pkg/supervisor/supervisor.go
  pkg/supervisor/supervisor_test.go
  pkg/supervisor/supervisor_unix.go
  pkg/supervisor/supervisor_unix_test.go
  pkg/supervisor/supervisor_windows.go
Labels: chore

#4539 [Backport release-1.30] Bump etcd to v3.5.14
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/controlplane, area/etcd, chore, backport/release-1.29

#4516 Improve manifest stack application w.r.t. CRDs
  inttest/Makefile.variables
  inttest/common/autopilot/waitfor.go
  inttest/stackapplier/rings.yaml
  inttest/stackapplier/stackapplier_test.go
  pkg/applier/applier.go
  pkg/applier/applier_test.go
  pkg/applier/stack.go
  pkg/autopilot/controller/setup.go
  pkg/component/controller/etcd_member_reconciler.go
  pkg/component/controller/workerconfig/reconciler.go
  pkg/kubernetes/watch/apiextensions.go
  pkg/kubernetes/watch/unstructured.go
Labels: bug

#4575 Marshal containerd.toml instead of templating it
  pkg/component/worker/containerd/component.go
  pkg/component/worker/containerd/configurer.go
  pkg/component/worker/containerd/configurer_test.go
Labels: chore, component/containerd

#4592 [Backport release-1.29] Bump golangci-lint to v1.57.1
  .golangci.yml
  hack/tools/Makefile.variables
Labels: area/ci, chore

#4593 [Backport release-1.28] Bump golangci-lint to v1.57.1
  .golangci.yml
  hack/tools/Makefile.variables
  internal/pkg/sysinfo/probes/linux/cgroup_controllers.go
  internal/pkg/sysinfo/probes/linux/kernel.go
  internal/pkg/sysinfo/probes/linux/linux.go
Labels: area/ci, chore

#4594 [Backport release-1.27] Bump golangci-lint to v1.57.1
  .golangci.yml
  hack/tools/Makefile.variables
  internal/pkg/sysinfo/probes/linux/cgroup_controllers.go
  internal/pkg/sysinfo/probes/linux/kernel.go
  internal/pkg/sysinfo/probes/linux/linux.go
Labels: area/ci, chore

#4596 [Backport release-1.29] Don't use the wrong PID in error strings
  pkg/supervisor/supervisor_unix.go
Labels: bug, backport/release-1.28

#4589 [Backport release-1.29] Set correct version number in containerd CRI config
  pkg/component/worker/containerd/criconfig.go
  pkg/component/worker/containerd/criconfig_test.go
Labels: bug, area/configuration, component/containerd, backport/release-1.28

#4609 Whitelist local IPv6 CIDRs when airgapping nodes
  inttest/common/airgap.go
Labels: chore, area/smoke-tests, backport/release-1.30

#4603 [Backport release-1.29] Bump containerd to v1.7.18
  docs/external-runtime-deps.md
  docs/nllb.md
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, component/containerd

#4622 Remvove usage of deprecated containerd docker package
  go.mod
  pkg/apis/k0s/v1beta1/images.go
Labels: chore

#4627 Install packages before airgapping
  inttest/common/airgap.go
Labels: bug, area/smoke-tests, backport/release-1.30

#4555 [release-1.29] Bump Envoy to v1.29.5
  pkg/constant/constant_shared.go
Labels: security fix, area/worker

#4618 Bump Kubernetes to v1.30.2
  .github/workflows/publish-docs-manual.yml
  embedded-bins/Makefile.variables
  examples/bootloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/constant/constant.go
  pkg/constant/constant_test.go
  static/manifests/k0s/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore, backport/release-1.30

#4630 Bump runc to v1.1.13
  embedded-bins/Makefile.variables
Labels: area/containers, chore, backport/release-1.30

#4620 [release-1.28] Bump Kubernetes to v1.28.11
  .github/workflows/publish-docs-manual.yml
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/constant/constant_shared.go
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore

#4607 Use a ten second timeout for join requests
  cmd/controller/controller.go
  pkg/component/controller/etcd.go
  pkg/token/joinclient.go
  pkg/token/joinclient_test.go
Labels: bug, area/controlplane

#4619 [release-1.29] Bump Kubernetes to v1.29.6
  .github/workflows/publish-docs-manual.yml
  embedded-bins/Makefile.variables
  examples/bootloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/constant/constant_shared.go
  pkg/constant/constant_shared_test.go
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore

#4621 [release-1.27] Bump Kubernetes to v1.27.15
  .github/workflows/publish-docs-manual.yml
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/conformance/README.md
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s.k0sproject.io/v1beta1/kubeproxy.go
  pkg/constant/constant_shared.go
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore

#4657 [Backport release-1.27] Use statically initialized runtime schemes
  pkg/autopilot/controller/root_controller.go
  pkg/autopilot/controller/root_worker.go
  pkg/autopilot/controller/scheme.go
  pkg/component/controller/extensions_controller.go
Labels: bug

#4659 [Backport release-1.30] Bump Kubernetes to v1.30.2
  .github/workflows/publish-docs-manual.yml
  embedded-bins/Makefile.variables
  examples/bootloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/constant/constant.go
  pkg/constant/constant_test.go
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore

#4653 Use the Kubernetes REST client for joining
  pkg/component/controller/etcd.go
  pkg/token/joinclient.go
  pkg/token/joinclient_test.go
Labels: chore

#4666 Allow nulls for helm values
  pkg/apis/helm/v1beta1/generic_hash.go
Labels: bug, backport/release-1.28, backport/release-1.29, backport/release-1.30

#4652 Also add kube-proxy mode to uploaded artifact names
  .github/workflows/ostests-e2e.yaml
Labels: bug, area/ci

#4660 Enable and document the insecure field for Helm Repos
  docs/helm-charts.md
  pkg/apis/k0s/v1beta1/extensions.go
  pkg/apis/k0s/v1beta1/zz_generated.deepcopy.go
  pkg/helm/helm.go
  static/manifests/k0s/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: area/configuration, area/helm

#4638 Use make builtins to split the Kubernetes version
  Makefile
Labels: chore

#4656 Drop k0s' RESTClientGetter implementation
  inttest/ap-removedapis/removedapis_test.go
  pkg/applier/applier.go
  pkg/autopilot/checks/checks.go
  pkg/autopilot/controller/plans/cmdprovider/airgapupdate/newplan.go
  pkg/autopilot/controller/plans/cmdprovider/k0supdate/newplan.go
  pkg/kubernetes/rest.go
Labels: chore

#4681 [Backport release-1.28] Upload airgap image list as release artifact
  .github/workflows/release.yml
Labels: area/ci, backport/release-1.27

#4695 Fix testify.Suite Run() usages across tests
  inttest/cli/cli_test.go
  inttest/configchange/config_test.go
  inttest/customdomain/customdomain_test.go
  inttest/customports/customports_test.go
  inttest/embedded-binaries/embedded_binaries_test.go
  inttest/kine/kine_test.go
  inttest/kubectl/kubectl_test.go
  inttest/kuberouter/kuberouter_hairpin_test.go
  inttest/singlenode/singlenode_test.go
  inttest/stackapplier/stackapplier_test.go
  pkg/apis/k0s/v1beta1/api_test.go
  pkg/apis/k0s/v1beta1/network_test.go
  pkg/apis/k0s/v1beta1/storage_test.go
Labels: area/ci, area/smoke-tests
