Repository k0sproject/k0s, pull requests merged in 2024-07, with the labels that each got.

#4690 Drop upgrade inttest
  inttest/Makefile.variables
  inttest/upgrade/upgrade_test.go
Labels: chore, area/smoke-tests

#4704 Correct log collection in release workflow
  .github/workflows/release.yml
Labels: bug, area/ci, backport/release-1.30

#4687 [Backoprt release-1.29] golang.org/x version bumps
  go.mod
  go.sum
Labels: dependencies, go

#4705 Cleanup unknown Helm chart manifest files
  cmd/controller/controller.go
  inttest/addons/addons_test.go
  pkg/apis/k0s/v1beta1/extensions.go
  pkg/apis/k0s/v1beta1/extenstions_test.go
  pkg/component/controller/extensions_controller.go
  pkg/component/controller/extensions_controller_test.go
Labels: bug, area/helm, backport/release-1.30

#4701 Support for running OS tests for Debian 12 on arm64
  .github/workflows/build-k0s.yml
  .github/workflows/ostests-e2e.yaml
  .github/workflows/ostests-matrix.yaml
  hack/ostests/README.md
  hack/ostests/main.tf
  hack/ostests/modules/infra/main.tf
  hack/ostests/modules/infra/variables.tf
  hack/ostests/modules/os/os_al2023.tf
  hack/ostests/modules/os/os_alpine_3_17.tf
  hack/ostests/modules/os/os_centos_7.tf
  hack/ostests/modules/os/os_centos_8.tf
  hack/ostests/modules/os/os_centos_9.tf
  hack/ostests/modules/os/os_debian_10.tf
  hack/ostests/modules/os/os_debian_11.tf
  hack/ostests/modules/os/os_debian_12.tf
  hack/ostests/modules/os/os_fcos_38.tf
  hack/ostests/modules/os/os_fedora_38.tf
  hack/ostests/modules/os/os_flatcar.tf
  hack/ostests/modules/os/os_oracle_7_9.tf
  hack/ostests/modules/os/os_oracle_8_7.tf
  hack/ostests/modules/os/os_oracle_9_1.tf
  hack/ostests/modules/os/os_rhel_7.tf
  hack/ostests/modules/os/os_rhel_8.tf
  hack/ostests/modules/os/os_rhel_9.tf
  hack/ostests/modules/os/os_rocky_8.tf
  hack/ostests/modules/os/os_rocky_9.tf
  hack/ostests/modules/os/os_ubuntu_2004.tf
  hack/ostests/modules/os/os_ubuntu_2204.tf
  hack/ostests/modules/os/os_ubuntu_2304.tf
  hack/ostests/modules/os/outputs.tf
  hack/ostests/modules/os/variables.tf
  hack/ostests/variables.tf
Labels: enhancement, area/ci

#4720 Overhaul dual-stack docs
  .github/workflows/go.yml
  docs/configuration.md
  docs/dual-stack.md
  docs/networking.md
  mkdocs.yml
  pkg/apis/k0s/v1beta1/network.go
  pkg/component/worker/static_pods.go
Labels: documentation, area/network, component/calico, component/kube-router

#4691 Add hardening/retry flags to curl invocations
  .github/workflows/check-network.yaml
  .github/workflows/dco.yaml
  .github/workflows/go.yml
  .github/workflows/ostests-e2e.yaml
  .github/workflows/publish-docs.yml
  .github/workflows/release.yml
  docs/Makefile
  docs/examples/gitops-flux.md
  docs/install.md
  docs/k0s-multi-node.md
  docs/raspberry-pi4.md
  docs/upgrade.md
  embedded-bins/iptables/Dockerfile
  embedded-bins/keepalived/Dockerfile
  embedded-bins/runc/Dockerfile
  examples/bootloose-ha-controllers/Dockerfile
  hack/get-calico.sh
  hack/tool/Dockerfile
  hack/tools/run-autopilot-matrix-tests.sh
  inttest/Makefile
  inttest/bootloose-alpine/Dockerfile
Labels: chore, area/security

#4708 Bump containerd to v1.7.19
  docs/airgap-install.md
  docs/external-runtime-deps.md
  docs/nllb.md
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, component/containerd, backport/release-1.30

#4717 [Backport release-1.30] Cleanup unknown Helm chart manifest files
  cmd/controller/controller.go
  inttest/addons/addons_test.go
  pkg/apis/k0s/v1beta1/extensions.go
  pkg/apis/k0s/v1beta1/extenstions_test.go
  pkg/component/controller/extensions_controller.go
  pkg/component/controller/extensions_controller_test.go
Labels: bug, area/helm, backport/release-1.29

#4715 Bump controller-tools to v0.15.0
  hack/tools/Makefile.variables
  static/manifests/autopilot/CustomResourceDefinition/autopilot.k0sproject.io_controlnodes.yaml
  static/manifests/autopilot/CustomResourceDefinition/autopilot.k0sproject.io_plans.yaml
  static/manifests/autopilot/CustomResourceDefinition/autopilot.k0sproject.io_updateconfigs.yaml
  static/manifests/etcd/CustomResourceDefinition/etcd.k0sproject.io_etcdmembers.yaml
  static/manifests/helm/CustomResourceDefinition/helm.k0sproject.io_charts.yaml
  static/manifests/k0s/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore

#4613 Determine new etcd member join names via etcd extra-args
  pkg/component/controller/etcd.go
Labels: area/etcd, area/configuration

#4675 Unify view of the world for the fake clients
  internal/testutil/fakeclient/tracker.go
  internal/testutil/kube_client.go
  pkg/applier/applier_test.go
  pkg/component/controller/apiendpointreconciler_test.go
  pkg/component/controller/workerconfig/reconciler_test.go
Labels: chore

#4739 [Backport release-1.30] Bump containerd to v1.7.19
  docs/airgap-install.md
  docs/external-runtime-deps.md
  docs/nllb.md
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, component/containerd, backport/release-1.29

#4542 Remove StorageExtensions
  cmd/config/validate_test.go
  docs/configuration.md
  docs/examples/openebs.md
  docs/storage.md
  inttest/Makefile
  inttest/Makefile.variables
  inttest/defaultstorage/defaultstorage_test.go
  inttest/openebs/openebs_test.go
  pkg/apis/k0s/v1beta1/clusterconfig_types.go
  pkg/apis/k0s/v1beta1/extensions.go
  pkg/apis/k0s/v1beta1/storageextensions.go
  pkg/component/controller/extensions_controller.go
  pkg/component/controller/extensions_controller_test.go
  static/manifests/k0s/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: area/configuration, chore

#4745 Remove useless errcheck
  inttest/common/ssh.go
Labels: chore

#4755 Enable embedded NATS server in kine
  embedded-bins/Makefile.variables
Labels: enhancement, area/controlplane, component/kine

#4737 [Backport release-1.29] Cleanup unknown Helm chart manifest files
  cmd/controller/controller.go
  inttest/addons/addons_test.go
  pkg/apis/k0s/v1beta1/extensions.go
  pkg/apis/k0s/v1beta1/extenstions_test.go
  pkg/component/controller/extensions_controller.go
  pkg/component/controller/extensions_controller_test.go
Labels: bug, area/helm, backport/release-1.28

#4674 Remove package-wide kubebuilder:validation:optional annotation
  cmd/config/create.go
  docs/configuration.md
  inttest/configchange/config_test.go
  pkg/apis/autopilot/v1beta2/updateconfig.go
  pkg/apis/etcd/v1beta1/types.go
  pkg/apis/helm/v1beta1/chart_types.go
  pkg/apis/k0s/v1beta1/api.go
  pkg/apis/k0s/v1beta1/calico.go
  pkg/apis/k0s/v1beta1/clusterconfig_types.go
  pkg/apis/k0s/v1beta1/controltypes.go
  pkg/apis/k0s/v1beta1/cplb.go
  pkg/apis/k0s/v1beta1/dualstack.go
  pkg/apis/k0s/v1beta1/extensions.go
  pkg/apis/k0s/v1beta1/feature_gates.go
  pkg/apis/k0s/v1beta1/images.go
  pkg/apis/k0s/v1beta1/konnectivity.go
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/apis/k0s/v1beta1/kuberouter.go
  pkg/apis/k0s/v1beta1/network.go
  pkg/apis/k0s/v1beta1/network_test.go
  pkg/apis/k0s/v1beta1/nllb.go
  pkg/apis/k0s/v1beta1/storage.go
  pkg/apis/k0s/v1beta1/telemetry.go
  pkg/apis/k0s/v1beta1/workerprofile.go
  pkg/apis/k0s/v1beta1/zz_generated.deepcopy.go
  pkg/component/controller/kuberouter.go
  pkg/component/controller/kuberouter_test.go
  pkg/telemetry/component.go
  static/manifests/autopilot/CustomResourceDefinition/autopilot.k0sproject.io_updateconfigs.yaml
  static/manifests/k0s/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore

#4749 [release-1.29] Bump Go to v1.21.12
  embedded-bins/Makefile.variables
Labels: chore

#4751 [release-1.30] Bump Alpine to v3.19.2
  embedded-bins/Makefile.variables
Labels: chore, backport/release-1.29

#4752 [release-1.28] Bump Alpine to v3.18.4
  embedded-bins/Makefile.variables
Labels: chore

#4746 Remove some context fields from some structs
  cmd/controller/controller.go
  cmd/worker/worker.go
  pkg/component/controller/etcd.go
  pkg/component/controller/kine.go
  pkg/component/status/status.go
  pkg/component/worker/autopilot.go
  pkg/component/worker/certificate_manager.go
Labels: chore

#4678 Extract smoketests job into its own file
  .github/workflows/go.yml
  .github/workflows/smoketest.yaml
Labels: area/ci, chore

#4743 [Backport release-1.29] Bump containerd to v1.7.19
  docs/external-runtime-deps.md
  docs/nllb.md
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, component/containerd

#4757 Bump Troubleshoot to v0.95.1
  inttest/bootloose-alpine/Dockerfile
Labels: chore, area/smoke-tests

#4750 Bump Alpine to v3.20.1
  embedded-bins/Makefile.variables
Labels: chore

#4748 Bump Go to v1.22.5
  embedded-bins/Makefile.variables
Labels: chore, backport/release-1.30

#4740 Add liveness/readiness probe for konnectivity-server
  pkg/component/controller/konnectivity.go
Labels: area/controlplane, component/konnectivity

#4688 [Backport release-1.27] Bump runc to v1.1.13
  embedded-bins/Makefile.variables
  embedded-bins/containerd/Dockerfile
  go.mod
  go.sum
Labels: area/containers, chore, dependencies, go

#4762 [Backport release-1.28] Cleanup unknown Helm chart manifest files
  cmd/controller/controller.go
  inttest/addons/addons_test.go
  pkg/apis/k0s/v1beta1/extensions.go
  pkg/apis/k0s/v1beta1/extenstions_test.go
  pkg/component/controller/extensions_controller.go
  pkg/component/controller/extensions_controller_test.go
Labels: bug, area/helm, backport/release-1.27

#4771 Remove autopilot/build
  pkg/autopilot/build/version.go
  pkg/autopilot/download/downloader.go
Labels: chore

#4760 [Backport release-1.27] Integrate controllerworker test into autopilot matrix
  .github/workflows/go.yml
  inttest/ap-controllerworker/controllerworker_test.go
Labels: chore, area/smoke-tests

#4778 Ensure that cgroups is mounted with openrc
  pkg/install/service.go
Labels: backport/release-1.27, backport/release-1.28, backport/release-1.29, backport/release-1.30

#4788 [release-1.29] Bump Calico to v3.26.4 including security patches
  pkg/constant/constant_shared.go
Labels: security fix, area/network, component/calico

#4742 Telemetry component cleanup
  cmd/controller/controller.go
  pkg/telemetry/component.go
  pkg/telemetry/segment.go
  pkg/telemetry/telemetry.go
Labels: chore

#4792 bug: add support for image tag and digest
  pkg/apis/k0s/v1beta1/clusterconfig_types_test.go
  pkg/apis/k0s/v1beta1/images.go
  pkg/apis/k0s/v1beta1/images_test.go
  pkg/apis/k0s/v1beta1/nllb_test.go
  static/manifests/k0s/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: bug, area/configuration, backport/release-1.30

#4793 [Backport release-1.30] bug: add support for image tag and digest
  pkg/apis/k0s/v1beta1/clusterconfig_types_test.go
  pkg/apis/k0s/v1beta1/images.go
  pkg/apis/k0s/v1beta1/images_test.go
  pkg/apis/k0s/v1beta1/nllb_test.go
Labels: bug, area/configuration, backport/release-1.29

#4790 [Backport release-1.29] Bump metrics-server to patched v0.7.1
  docs/configuration.md
  docs/raspberry-pi4.md
  pkg/apis/k0s/v1beta1/images_test.go
  pkg/constant/constant_shared.go
Labels: security fix, area/worker, component/metrics-server, backport/release-1.28

#4797 Bump kine to v0.11.12
  embedded-bins/Makefile.variables
  pkg/component/controller/kine.go
Labels: area/controlplane, chore, component/kine, backport/release-1.30

#4774 [release-1.27] Bump Kubernetes to v1.27.16
  .github/workflows/publish-docs-manual.yml
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/conformance/README.md
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s.k0sproject.io/v1beta1/kubeproxy.go
  pkg/constant/constant_shared.go
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: security fix

#4779 [release-1.28] Bump Kubernetes to v1.28.12
  .github/workflows/publish-docs-manual.yml
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/constant/constant_shared.go
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: security fix

#4780 Bump Kubernetes to v1.30.3
  .github/workflows/publish-docs-manual.yml
  embedded-bins/Makefile.variables
  examples/bootloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/constant/constant.go
  static/manifests/k0s/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: security fix, backport/release-1.30

#4799 Bump containerd to v1.7.20
  docs/airgap-install.md
  docs/external-runtime-deps.md
  docs/nllb.md
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, component/containerd, backport/release-1.30

#4776 [release-1.29] Bump Kubernetes to v1.29.7
  .github/workflows/publish-docs-manual.yml
  embedded-bins/Makefile.variables
  examples/bootloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/constant/constant_shared.go
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: security fix

#4798 Bump etcd to v3.5.15
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/controlplane, area/etcd, chore, backport/release-1.30

#4807 [Backport release-1.30] Bump Kubernetes to v1.30.3
  .github/workflows/publish-docs-manual.yml
  embedded-bins/Makefile.variables
  examples/bootloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/constant/constant.go
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: security fix

#4802 [release-1.29] Bump Envoy to v1.29.7
  pkg/constant/constant_shared.go
Labels: security fix, area/worker

#4801 Bump Envoy to v1.30.4
  pkg/constant/constant.go
Labels: security fix, area/worker, backport/release-1.30

#4805 [Backport release-1.30] Bump etcd to v3.5.15
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/controlplane, area/etcd, chore, backport/release-1.29

#4806 [Backport release-1.30] Bump containerd to v1.7.20
  docs/airgap-install.md
  docs/external-runtime-deps.md
  docs/nllb.md
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, component/containerd, backport/release-1.29

#4814 [Backport release-1.29] Bump containerd to v1.7.20
  docs/external-runtime-deps.md
  docs/nllb.md
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, component/containerd

#4815 Bump cosign to v2.3.0
  .github/workflows/release.yml
  Makefile
Labels: area/ci, chore

#4817 fix: ClusterImages.Validate images
  pkg/apis/k0s/v1beta1/clusterconfig_types_test.go
  pkg/apis/k0s/v1beta1/images.go
Labels: area/configuration
