Repository k0sproject/k0s, pull requests merged in 2024-05, with the labels that each got.

#4355 Bump kine to v0.11.8
  embedded-bins/Makefile.variables
Labels: area/controlplane, chore, component/kine, backport/release-1.29

#4358 Fix timing issue in ap-removedapis inttest
  inttest/ap-removedapis/removedapis_test.go
Labels: bug, area/smoke-tests, backport/release-1.29

#4340 Honor API port number in kubeconfig admin subcommand
  cmd/controller/certificates.go
  cmd/kubeconfig/admin.go
  cmd/kubeconfig/admin_test.go
Labels: bug, area/cli

#4356 Bump CoreDNS to v1.11.3
  pkg/constant/constant.go
Labels: area/network, chore, backport/release-1.29

#4360 Fix metadata test
  pkg/node/nodehostname_test.go
Labels: bug, backport/release-1.29

#4363 Bump containerd to v1.7.16
  docs/airgap-install.md
  docs/external-runtime-deps.md
  docs/nllb.md
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, component/containerd, backport/release-1.29

#4371 Group mkdocs version bumps
  .github/dependabot.yml
Labels: area/ci, chore

#4378 Disallow test code outside of tests
  .golangci.yml
  pkg/autopilot/controller/plans/cmdprovider/airgapupdate/newplan_test.go
  pkg/autopilot/controller/plans/cmdprovider/airgapupdate/schedulable_test.go
  pkg/autopilot/controller/plans/cmdprovider/k0supdate/newplan_test.go
  pkg/autopilot/controller/plans/cmdprovider/k0supdate/schedulable_test.go
  pkg/autopilot/controller/plans/cmdprovider/k0supdate/utils/exists_test.go
Labels: area/ci, chore

#4385 Log keepalived config in debug mode
  cmd/controller/controller.go
  pkg/component/controller/cplb_unix.go
  pkg/component/controller/cplb_windows.go
Labels: area/controlplane, chore

#4389 Bump Go to v1.22.3
  embedded-bins/Makefile.variables
Labels: chore

#4390 [release-1.29] Bump Go to v1.21.10
  embedded-bins/Makefile.variables
Labels: chore, backport/release-1.28

#4391 Default DelayLoop to 1m
  docs/configuration.md
  pkg/apis/k0s/v1beta1/cplb.go
  pkg/apis/k0s/v1beta1/cplb_test.go
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: area/configuration, chore

#4388 Close update channel when the watch loop terminates
  pkg/component/controller/cplb_reconciler.go
Labels: bug

#4386 Some adjustments to the VRRP instance config
  docs/configuration.md
  pkg/apis/k0s/v1beta1/cplb.go
  pkg/apis/k0s/v1beta1/cplb_test.go
  pkg/apis/k0s/v1beta1/zz_generated.deepcopy.go
  pkg/component/controller/cplb_unix.go
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: area/configuration, chore

#4396 Move KeepalivedSpec validation into its own method
  pkg/apis/k0s/v1beta1/cplb.go
Labels: bug, area/configuration

#4395 Stop reconciler before keepalived
  pkg/component/controller/cplb_reconciler.go
  pkg/component/controller/cplb_unix.go
Labels: area/controlplane, chore

#4400 Install docker buildx for self-hosted runners
  .github/workflows/release.yml
Labels: bug, area/ci

#4394 [Backport release-1.27] Bump Go to v1.21.10
  embedded-bins/Makefile.variables
Labels: chore

#4387 Add an error callback to the CPLB reconciler watcher
  pkg/component/controller/cplb_reconciler.go
Labels: chore

#4405 Bump kine to v0.11.9
  embedded-bins/Makefile.variables
Labels: area/controlplane, chore, component/kine, backport/release-1.30

#4412 Remove disable-upgrade-check flag from k0sctl
  hack/ostests/modules/k0sctl/main.tf
Labels: area/ci, chore

#4421 Change kine metrics port from 8080 to 2380
  pkg/component/controller/kine.go
  pkg/component/controller/metrics.go
Labels: bug, component/kube-router, component/kine, backport/release-1.30

#4419 Introduce `check-metricsscraper-singlenode`
  inttest/Makefile
  inttest/Makefile.variables
  inttest/metricsscraper/metricsscraper_test.go
Labels: chore, area/smoke-tests, backport/release-1.30

#4416 Use a versioned worker config stack
  pkg/component/controller/workerconfig/reconciler.go
  pkg/component/controller/workerconfig/reconciler_test.go
Labels: bug, area/configuration, backport/release-1.30

#4432 Lessen the systemd RestartSec to 10 secs
  pkg/install/service.go
Labels: area/install, backport/release-1.27, backport/release-1.28, backport/release-1.29, backport/release-1.30

#4424 Bump Kubernetes to v1.30.1
  .github/workflows/publish-docs-manual.yml
  embedded-bins/Makefile.variables
  examples/bootloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/constant/constant.go
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore, backport/release-1.30

#4425 [release-1.29] Bump Kubernetes to v1.29.5
  .github/workflows/publish-docs-manual.yml
  embedded-bins/Makefile.variables
  examples/bootloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/constant/constant_shared.go
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore

#4426 [release-1.28] Bump Kubernetes to v1.28.10
  .github/workflows/publish-docs-manual.yml
  docs/dockershim.md
  docs/nllb.md
  docs/raspberry-pi4.md
  docs/worker-node-config.md
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/constant/constant_shared.go
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore

#4427 [release-1.27] Bump Kubernetes to v1.27.14
  .github/workflows/publish-docs-manual.yml
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/conformance/README.md
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s.k0sproject.io/v1beta1/kubeproxy.go
  pkg/constant/constant_shared.go
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore

#4435 Fix error handling in EtcdMemberReconciler
  pkg/component/controller/etcd_member_reconciler.go
Labels: bug, area/controlplane, area/etcd, backport/release-1.30

#4457 Use dedicated leasepool for worker config component
  cmd/controller/controller.go
  inttest/Makefile
  inttest/Makefile.variables
  inttest/ap-controllerworker/controllerworker_test.go
  pkg/component/controller/leaderelector/leasepool.go
Labels: area/controlplane, component/autopilot, backport/release-1.30

#4299 Drop multierr module and rely on the standard lib
  go.mod
  internal/pkg/file/file.go
  internal/pkg/file/file_test.go
  internal/pkg/iptablesutils/iptables.go
  internal/pkg/iptablesutils/iptables_test.go
  inttest/common/airgap.go
  inttest/common/bootloosesuite.go
  inttest/common/launchdelegate.go
  inttest/nllb/nllb_test.go
  pkg/component/controller/clusterConfig.go
  pkg/component/controller/workerconfig/reconciler.go
  pkg/component/worker/config/config.go
  pkg/component/worker/config/config_test.go
  pkg/component/worker/config/loader.go
  pkg/component/worker/nllb/envoy.go
  pkg/component/worker/nllb/envoy_test.go
  pkg/component/worker/utils.go
  pkg/supervisor/pingpong_unix.go
  pkg/supervisor/pingpong_windows.go
Labels: chore

#4461 Use atomic.Bool instead of atomic.Value for leader status
  pkg/component/controller/leaderelector/leasepool.go
Labels: chore

#4462 Remove unused atomic.Value from CSRApprover constructor
  pkg/component/controller/csrapprover.go
Labels: chore

#4460 Remove unused autopilot inttest toolsuite
  .github/workflows/autopilot-branch-to-latest.yaml
  go.mod
  go.sum
  inttest/toolsuite/operations/planapply.go
  inttest/toolsuite/operations/sonobuoy.go
  inttest/toolsuite/tests/conformance_test.go
  inttest/toolsuite/tests/versionupdate_test.go
  inttest/toolsuite/toolsuite.go
  inttest/toolsuite/util/terraform.go
Labels: area/ci, chore

#4420 Add readinessProbe/minReadySeconds to kube-router
  pkg/component/controller/kuberouter.go
Labels: bug, component/kube-router, backport/release-1.30

#4467 Skip `kube-bridge` interface for api/etcd address
  internal/pkg/iface/iface.go
  inttest/singlenode/singlenode_test.go
Labels: bug, area/controlplane, area/configuration, backport/release-1.27, backport/release-1.28, backport/release-1.29, backport/release-1.30

#4331 Fluent interface for atomic file writes
  internal/pkg/file/atomic.go
  internal/pkg/file/atomic_test.go
  internal/pkg/file/file.go
  internal/pkg/file/file_test.go
  pkg/component/controller/cplb_unix.go
Labels: chore

#4476 [Backport release-1.27] Skip `kube-bridge` interface for api/etcd address
  internal/pkg/iface/iface.go
  inttest/singlenode/singlenode_test.go
Labels: bug, area/controlplane, area/configuration

#4477 Bump Python verison for docs to v3.12.3
  docs/Makefile.variables
Labels: chore

#4480 [Backport release-1.27] Use a versioned worker config stack
  pkg/component/controller/workerconfig/reconciler.go
  pkg/component/controller/workerconfig/reconciler_test.go
Labels: bug, area/controlplane

#4429 [Backport release-1.29] feat: implement watcher for oci bundles
  pkg/component/worker/ocibundle.go
Labels: enhancement, area/worker, component/containerd

#4428 [Backport release-1.28] feat: implement watcher for oci bundles
  go.mod
  go.sum
  pkg/component/worker/ocibundle.go
Labels: enhancement, area/worker, component/containerd, backport/release-1.27

#4488 [Backport release-1.29] Use dedicated leasepool for worker config component
  cmd/controller/controller.go
  inttest/Makefile
  inttest/Makefile.variables
  inttest/ap-controllerworker/controllerworker_test.go
  pkg/component/controller/leaderelector/leasepool.go
Labels: bug, area/controlplane, backport/release-1.28

#4489 [Backport release-1.27] feat: implement watcher for oci bundles
  go.mod
  go.sum
  pkg/component/worker/ocibundle.go
Labels: enhancement, area/worker, component/containerd

#4487 Let temporary untar dirs start with a dot
  embedded-bins/Makefile
Labels: bug, backport/release-1.30

#4501 Adding CLI args reference to the docs
  mkdocs.yml
Labels: backport/release-1.28, backport/release-1.29, backport/release-1.30

#4484 Fix ocibundle for 32bit arm
  docs/airgap-install.md
  pkg/component/worker/ocibundle.go
Labels: bug, area/worker, component/containerd, backport/release-1.27, backport/release-1.28, backport/release-1.29, backport/release-1.30

#4505 Fix docs link to fish shell
  docs/shell-completion.md
Labels: documentation, chore, backport/release-1.30

#4507 Fix docs link to custom CRI runtime
  docs/architecture.md
Labels: documentation, chore, backport/release-1.30

#4515 Construct Helm actions using Helm env helpers
  pkg/helm/helm.go
Labels: area/helm, backport/release-1.27, backport/release-1.28, backport/release-1.29, backport/release-1.30

#4526 Bump RHEL9 to 9.3.x in ostests
  hack/ostests/README.md
  hack/ostests/modules/os/os_rhel_9.tf
Labels: area/ci, chore

#4279 Remove worker related flags from GetControllerFlags()
  cmd/controller/controller.go
  cmd/controller/controller_test.go
  cmd/install/controller_test.go
  cmd/worker/worker.go
  pkg/config/cli.go
  pkg/config/cli_test.go
Labels: chore, area/cli
