Repository k0sproject/k0s, pull requests merged in 2024-04, with the labels that each got.

#4217 [Backport release-1.27] Harden etcd subcommand usage and validation
  cmd/etcd/leave.go
  cmd/etcd/leave_test.go
  cmd/etcd/list.go
  cmd/etcd/list_test.go
Labels: bug, area/etcd, area/cli, backport/release-1.26

#4235 Bump Go to v1.22.2
  embedded-bins/Makefile.variables
Labels: security fix

#4236 [release-1.29] Bump Go to v1.21.9
  embedded-bins/Makefile.variables
Labels: security fix, backport/release-1.28

#4220 Remove superfluous nil check
  pkg/component/worker/config/config.go
Labels: chore

#4226 Update backport-action settings
  .github/workflows/backport.yaml
Labels: area/ci, chore

#4240 Bump envoy to v1.29.3
  pkg/constant/constant.go
Labels: security fix, area/worker, backport/release-1.29

#4243 Bump etcd to v3.5.13
  embedded-bins/Makefile.variables
  go.mod
  go.sum
  pkg/component/controller/etcd.go
Labels: area/controlplane, area/etcd, chore, backport/release-1.29

#4241 [Backport to release-1.27] Bump Go to v1.21.9
  embedded-bins/Makefile.variables
Labels: security fix, backport/release-1.26

#4238 Add integration tests around k0s reset
  inttest/Makefile.variables
  inttest/backup/backup_test.go
  inttest/byocri/byocri_test.go
  inttest/common/bootloosesuite.go
  inttest/common/ssh.go
  inttest/common/util.go
  inttest/reset/reset_test.go
Labels: chore, area/smoke-tests

#4254 Bump golang.org/x/net to v0.23.0
  go.mod
  go.sum
Labels: security fix, backport/release-1.29

#4250 [Backport release-1.29] Bump etcd to v3.5.13
  embedded-bins/Makefile.variables
  go.mod
  go.sum
  pkg/component/controller/etcd.go
Labels: area/controlplane, area/etcd, chore

#4256 [Backport release-1.29] Fix CVE-2023-45288
  go.mod
  go.sum
Labels: security fix, backport/release-1.28

#4257 [Backport release-1.28] Fix CVE-2023-45288
  go.mod
  go.sum
Labels: security fix, backport/release-1.27

#4258 [Backport release-1.27] Fix CVE-2023-45288
  go.mod
  go.sum
Labels: security fix, backport/release-1.26

#4230 Replace the Machine ID usage with an "Invocation ID"
  cmd/controller/controller.go
  docker-entrypoint.sh
  docs/external-runtime-deps.md
  docs/raspberry-pi4.md
  go.mod
  go.sum
  hack/ostests/modules/os/os_alpine_3_17_userdata.tftpl
  hack/ostests/modules/os/os_centos_7.tf
  internal/pkg/sysinfo/machineid/machineid.go
  internal/pkg/sysinfo/machineid/machineid_test.go
  internal/pkg/sysinfo/probes/machineid.go
  internal/pkg/sysinfo/sysinfo.go
  inttest/bootloose-alpine/Dockerfile
  inttest/cli/cli_test.go
  pkg/autopilot/controller/leases.go
  pkg/autopilot/controller/leases_test.go
  pkg/autopilot/controller/root/root.go
  pkg/autopilot/controller/root_controller.go
  pkg/autopilot/controller/root_controller_test.go
  pkg/component/controller/autopilot.go
  pkg/component/controller/controllersleasecounter.go
  pkg/component/controller/konnectivity.go
  pkg/component/controller/leaderelector/leasepool.go
  pkg/config/cfgvars.go
  pkg/leaderelection/lease_pool.go
  pkg/leaderelection/lease_pool_test.go
  pkg/telemetry/telemetry.go
Labels: area/controlplane, chore

#4259 [Backport release-1.26] Fix CVE-2023-45288
  go.mod
  go.sum
Labels: security fix

#4251 Remove Docker container runtime support
  docs/experimental-windows.md
  docs/runtime.md
  pkg/cleanup/cleanup_unix.go
  pkg/component/worker/cri_runtime.go
  pkg/component/worker/cri_runtime_test.go
  pkg/component/worker/kubelet.go
  pkg/component/worker/kubelet_test.go
  pkg/container/runtime/docker.go
  pkg/container/runtime/runtime.go
Labels: area/containers, chore

#4270 Cleanup golangci-lint config
  .golangci.yml
Labels: area/ci, chore

#4271 Fix kind dsn leakage
  pkg/component/controller/kine.go
Labels: security fix, backport/release-1.26, backport/release-1.27, backport/release-1.28, backport/release-1.29

#4282 Fix kind credentials leakage in the logs (2)
  pkg/component/controller/kine.go
Labels: security fix, backport/release-1.26, backport/release-1.27, backport/release-1.28, backport/release-1.29

#4229 Have a constant to indicate Kubernetes pre-releases
  inttest/kubectl/kubectl_test.go
  pkg/constant/constant.go
Labels: chore, area/smoke-tests

#4277 Ignore token-file argument when value not needed
  cmd/controller/controller.go
  cmd/worker/worker.go
  inttest/hacontrolplane/hacontrolplane_test.go
  inttest/upgrade/upgrade_test.go
  pkg/component/worker/utils.go
Labels: bug, area/cli, backport, backport/release-1.29

#4293 [Backport release-1.28] Ignore token-file argument when value not needed
  cmd/controller/controller.go
  cmd/worker/worker.go
  inttest/hacontrolplane/hacontrolplane_test.go
  inttest/upgrade/upgrade_test.go
  pkg/component/worker/utils.go
Labels: bug, area/cli, backport/release-1.27

#4291 Enable console logging for keepalived
  cmd/controller/controller.go
  pkg/component/controller/cplb_unix.go
  pkg/component/controller/cplb_windows.go
Labels: enhancement, area/controlplane

#4295 [Backport release-1.27] Ignore token-file argument when value not needed
  cmd/controller/controller.go
  cmd/worker/worker.go
  inttest/hacontrolplane/hacontrolplane_test.go
  inttest/upgrade/upgrade_test.go
  pkg/component/worker/utils.go
Labels: bug, area/cli, backport/release-1.26

#4306 Bump containerd to v1.7.15
  docs/airgap-install.md
  docs/external-runtime-deps.md
  docs/nllb.md
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, component/containerd, backport/release-1.29

#4294 Remove binary before building it
  Makefile
Labels: bug, backport/release-1.29

#4304 Bump Kubernetes to v1.29.4
  .github/workflows/publish-docs-manual.yml
  embedded-bins/Makefile.variables
  examples/bootloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/constant/constant.go
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: security fix, backport/release-1.29

#4307 [Backport release-1.29] Bump containerd to v1.7.15
  docs/external-runtime-deps.md
  docs/nllb.md
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, component/containerd

#4303 [release-1.27] Bump Kubernetes to v1.27.13
  .github/workflows/publish-docs-manual.yml
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/conformance/README.md
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/constant/constant_shared.go
Labels: security fix

#4302 [release-1.28] Bump Kubernetes to v1.28.9
  .github/workflows/publish-docs-manual.yml
  embedded-bins/Makefile.variables
  examples/footloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/constant/constant_shared.go
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: security fix

#4308 Bump kube-router to v1.6.1
  pkg/constant/constant.go
Labels: area/network, chore, component/kube-router, backport/release-1.29

#4313 [Backport release-1.29] Bump Kubernetes to v1.29.4
  .github/workflows/publish-docs-manual.yml
  embedded-bins/Makefile.variables
  examples/bootloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/constant/constant_shared.go
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: security fix

#4287 Remove implicit build tag
  pkg/apis/k0s/v1beta1/cplb_linux.go
  pkg/apis/k0s/v1beta1/cplb_other.go
Labels: chore

#4264 Rework user installation functions
  cmd/install/install.go
  pkg/cleanup/users.go
  pkg/install/users.go
Labels: chore

#4288 Remove convertFileParamsToAbsolute
  cmd/install/controller.go
  cmd/install/install.go
  cmd/install/util.go
  cmd/install/worker.go
Labels: chore

#4267 Consolidate network bridge cleanup
  pkg/cleanup/bridge_linux.go
  pkg/cleanup/bridge_other.go
  pkg/cleanup/bridge_windows.go
  pkg/cleanup/cleanup.go
  pkg/cleanup/cleanup_windows.go
Labels: chore

#4305 Add community hours details to READMEs
  README.md
  docs/README.md
Labels: documentation

#4228 Let k0s cloud provider assign a node's provider ID
  inttest/k0scloudprovider/k0scloudprovider_test.go
  pkg/k0scloudprovider/instances.go
Labels: area/controlplane, chore

#4117 Improve k0s-managed containerd config detection
  pkg/component/worker/containerd/component.go
  pkg/component/worker/containerd/component_test.go
Labels: area/configuration, chore, component/containerd

#4327 Fixed Stop() for external etcd
  pkg/component/controller/etcd.go
Labels: bug, area/etcd, backport/release-1.27, backport/release-1.28, backport/release-1.29

#4333 Remove testutil.ConfigGetter
  cmd/kubeconfig/kubeconfig_test.go
  internal/testutil/runtime_config.go
Labels: chore

#4335 Proper defaulting and validation for the API spec
  inttest/common/bootloosesuite.go
  pkg/apis/k0s/v1beta1/api.go
  pkg/apis/k0s/v1beta1/api_test.go
  pkg/apis/k0s/v1beta1/clusterconfig_types.go
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: area/configuration, chore

#4114 Bump Kubernetes to v1.30.0
  .github/workflows/publish-docs-manual.yml
  Makefile
  embedded-bins/Makefile.variables
  examples/bootloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/component/controller/workerconfig/reconciler_test.go
  pkg/component/worker/config/config_test.go
  pkg/constant/constant.go
Labels: chore

#4341 More helpful error message for empty/absent token files
  pkg/component/worker/utils.go
Labels: chore

#4108 Completely remove kubelet-config component
  cmd/controller/controller.go
  inttest/ap-ha3x3/ha3x3_test.go
  pkg/component/controller/kubeletconfig.go
  pkg/component/controller/kubeletconfig_test.go
Labels: area/controlplane, chore

#4310 Bump Envoy to v1.30.1
  pkg/constant/constant.go
Labels: area/worker, chore
