Repository k0sproject/k0s, pull requests merged in 2024-08, with the labels that each got.

#4800 Bump Envoy to v1.31.0
  pkg/constant/constant.go
Labels: security fix, area/worker

#4764 [Backport release-1.27] Cleanup unknown Helm chart manifest files
  cmd/controller/controller.go
  inttest/addons/addons_test.go
  pkg/apis/k0s.k0sproject.io/v1beta1/extensions.go
  pkg/apis/k0s.k0sproject.io/v1beta1/extenstions_test.go
  pkg/component/controller/extensions_controller.go
  pkg/component/controller/extensions_controller_test.go
Labels: bug, area/helm

#4826 Remove unused error return type from Supervisor.Stop
  pkg/component/controller/apiserver.go
  pkg/component/controller/controllermanager.go
  pkg/component/controller/cplb_unix.go
  pkg/component/controller/etcd.go
  pkg/component/controller/k0scontrolapi.go
  pkg/component/controller/kine.go
  pkg/component/controller/konnectivity.go
  pkg/component/controller/scheduler.go
  pkg/component/worker/containerd/component.go
  pkg/component/worker/kubelet.go
  pkg/supervisor/supervisor.go
  pkg/supervisor/supervisor_test.go
Labels: chore

#4823 [Backport release-1.29] Bump Go to v1.22.5
  embedded-bins/Makefile.variables
  go.mod
  hack/tool/go.mod
Labels: chore, backport/release-1.28

#4827 Use dynamic base IDs for NLLB envoy process
  pkg/component/worker/nllb/envoy.go
Labels: area/network, area/worker, backport/release-1.30

#4824 [Backport release-1.28] Bump Go to v1.22.5
  Makefile
  embedded-bins/Makefile
  embedded-bins/Makefile.variables
  embedded-bins/kine/Dockerfile
  go.mod
  hack/tool/go.mod
  hack/tools/Makefile.variables
  static/manifests/autopilot/CustomResourceDefinition/autopilot.k0sproject.io_controlnodes.yaml
  static/manifests/autopilot/CustomResourceDefinition/autopilot.k0sproject.io_plans.yaml
  static/manifests/autopilot/CustomResourceDefinition/autopilot.k0sproject.io_updateconfigs.yaml
  static/manifests/helm/CustomResourceDefinition/helm.k0sproject.io_charts.yaml
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore, backport/release-1.27

#4772 Install QEMU emulator in e2e ostests if needed
  .github/workflows/ostests-e2e.yaml
Labels: bug, area/ci

#4714 [helm] don't start reconciler before leaderelection
  pkg/component/controller/extensions_controller.go
Labels: bug, area/helm, backport/release-1.27, backport/release-1.28, backport/release-1.29, backport/release-1.30

#4830 Allow all kine schemes to be joined except the local ones
  pkg/apis/k0s/v1beta1/storage.go
  pkg/apis/k0s/v1beta1/storage_test.go
Labels: enhancement, area/controlplane, component/kine

#4829 Validate storage type
  pkg/apis/k0s/v1beta1/clusterconfig_types_test.go
  pkg/apis/k0s/v1beta1/storage.go
  pkg/apis/k0s/v1beta1/storage_test.go
  pkg/autopilot/controller/updates/clusterinfo.go
  pkg/component/controller/metrics.go
  pkg/config/cfgvars.go
  pkg/config/cfgvars_test.go
  pkg/telemetry/component.go
  pkg/telemetry/telemetry.go
Labels: area/configuration

#4808 Correct the image override YAML snippet in the docs
  docs/configuration.md
Labels: documentation

#4747 Separate the initialization and reconciliation in ClusterConfigReconciler
  cmd/controller/controller.go
  pkg/component/controller/clusterConfig.go
  pkg/component/controller/clusterconfig/apiconfigsource.go
  pkg/component/controller/clusterconfig/configsource.go
  pkg/component/controller/clusterconfig/staticsource.go
Labels: area/controlplane, chore

#4834 Allow reading config file from stdin
  pkg/config/cfgvars.go
  pkg/config/cfgvars_test.go
Labels: bug, area/configuration, area/cli

#4744 Add controller lease counter component after API server
  cmd/controller/controller.go
  internal/sync/value/latest.go
  internal/sync/value/latest_test.go
  pkg/autopilot/controller/updates/clusterinfo.go
  pkg/component/controller/controllersleasecounter.go
  pkg/component/controller/konnectivity.go
  pkg/component/controller/konnectivityagent.go
  pkg/kubernetes/lease.go
  pkg/telemetry/telemetry.go
Labels: area/controlplane

#4825 [Backport release-1.27] Bump Go to v1.22.5
  Makefile
  embedded-bins/Makefile
  embedded-bins/Makefile.variables
  embedded-bins/kine/Dockerfile
  go.mod
  hack/tool/go.mod
  hack/tools/Makefile.variables
  pkg/apis/autopilot.k0sproject.io/v1beta2/zz_generated.deepcopy.go
  pkg/apis/helm.k0sproject.io/v1beta1/zz_generated.deepcopy.go
  pkg/apis/k0s.k0sproject.io/v1beta1/zz_generated.deepcopy.go
  static/manifests/autopilot/CustomResourceDefinition/autopilot.k0sproject.io_controlnodes.yaml
  static/manifests/autopilot/CustomResourceDefinition/autopilot.k0sproject.io_plans.yaml
  static/manifests/autopilot/CustomResourceDefinition/autopilot.k0sproject.io_updateconfigs.yaml
  static/manifests/helm/CustomResourceDefinition/helm.k0sproject.io_charts.yaml
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore

#4876 (docs typo) Unwriteable => unwritable
  docs/configuration.md
Labels: documentation, chore

#4860 Detect --hostname-override flag in Autopilot for controller+worker nodes
  cmd/controller/controller.go
  inttest/ap-controllerworker/controllerworker_test.go
  pkg/autopilot/common/hostname.go
  pkg/autopilot/controller/root/root.go
  pkg/autopilot/controller/root_controller.go
  pkg/autopilot/controller/setup.go
  pkg/autopilot/controller/signal/k0s/cordon.go
  pkg/autopilot/controller/signal/k0s/uncordon.go
  pkg/component/controller/autopilot.go
Labels: bug, component/autopilot, backport/release-1.28, backport/release-1.29, backport/release-1.30

#4880 Bump kube to 1.30.4
  .github/workflows/publish-docs-manual.yml
  embedded-bins/Makefile.variables
  examples/bootloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/constant/constant.go
  static/manifests/k0s/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore, backport/release-1.30

#4884 [Backport release-1.30] Bump kube to 1.30.4
  .github/workflows/publish-docs-manual.yml
  embedded-bins/Makefile.variables
  examples/bootloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/constant/constant.go
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore

#4879 Don't treat kine data sources as URLs
  pkg/apis/k0s/v1beta1/storage.go
  pkg/apis/k0s/v1beta1/storage_test.go
  pkg/backup/manager_unix.go
  pkg/backup/sqlitedb_unix.go
  pkg/component/controller/kine.go
  pkg/config/kine/datasource.go
Labels: bug, area/configuration, component/kine

#4900 etcd join workflow fix when the first attempt fails
  cmd/controller/controller.go
Labels: bug, backport/release-1.28, backport/release-1.29, backport/release-1.30

#4905 Fix panic in ExtensionsController when reacquring the lease
  pkg/component/controller/extensions_controller.go
Labels: bug, area/controlplane, area/helm, backport/release-1.30

#4890 Bump kine to v0.12.1
  embedded-bins/Makefile.variables
  pkg/component/controller/kine.go
Labels: area/controlplane, chore, component/kine

#4915 Bump containerd to v1.7.21
  docs/airgap-install.md
  docs/external-runtime-deps.md
  docs/nllb.md
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/containers, chore, component/containerd, backport/release-1.30

#4912 Bump Go to v1.22.6
  embedded-bins/Makefile.variables
Labels: chore, backport/release-1.30

#4914 Bump sonobuoy to v0.57.2
  .github/dependabot.yml
  go.mod
  go.sum
  inttest/Makefile.variables
Labels: area/ci, chore

#4894 Move generated CRDs into their own directory
  Makefile
  pkg/component/controller/crd.go
  static/_crds/autopilot/autopilot.k0sproject.io_controlnodes.yaml
  static/_crds/autopilot/autopilot.k0sproject.io_plans.yaml
  static/_crds/autopilot/autopilot.k0sproject.io_updateconfigs.yaml
  static/_crds/etcd/etcd.k0sproject.io_etcdmembers.yaml
  static/_crds/helm/helm.k0sproject.io_charts.yaml
  static/_crds/k0s/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore
