Repository k0sproject/k0s, pull requests merged in 2025-09, with the labels that each got.

#6407 Only count Linux nodes when scaling CoreDNS
  pkg/component/controller/coredns.go
Labels: bug, area/windows

#6411 Add ExternalAddress for konnectivity
  cmd/controller/controller.go
  pkg/apis/k0s/v1beta1/api.go
  pkg/apis/k0s/v1beta1/konnectivity.go
  pkg/component/controller/apiendpointreconciler.go
  static/_crds/k0s/k0s.k0sproject.io_clusterconfigs.yaml
Labels: backport/release-1.31, backport/release-1.32, backport/release-1.33

#6426 Use fake version in update server inttest
  inttest/update-server/html/unstable/index.yaml
Labels: chore, area/smoke-tests

#6410 Run Kube-Router only on Linux nodes
  pkg/component/controller/kuberouter.go
Labels: area/windows, chore, component/kube-router

#6443 Replace links to Medium with links to the community blog
  docs/contributors/index.md
  docs/governance/cncf/security-self-assessment.md
  mkdocs.yml
Labels: documentation, chore, backport/release-1.33
