Repository k0sproject/k0s, pull requests merged in 2025-02, with the labels that each got.

#5491 Apply the bootstraprbac stack directly
  cmd/controller/controller.go
  pkg/component/controller/systemrbac.go
  pkg/component/controller/systemrbac.yaml
  pkg/config/cli.go
  pkg/constant/constant.go
Labels: area/controlplane, chore

#5490 Disable leader election in single-controller clusters
  cmd/controller/controller.go
  pkg/component/controller/autopilot.go
  pkg/component/controller/controllermanager.go
  pkg/component/controller/scheduler.go
Labels: enhancement, area/controlplane

#5492 New Logo
  README.md
  docs/README.md
  docs/img/k0s-favicon-192.png
  docs/img/k0s-logo-2025-horizontal-inverted.svg
  docs/img/k0s-logo-2025-horizontal.svg
  docs/img/k0s-logo-full-color-dark.svg
  docs/img/k0s-logo-full-color-light.svg
  docs/img/k0s_social.png
  mkdocs.yml
Labels: documentation, chore, backport/release-1.32

#5493 Remove "by Team Lens"
  README.md
Labels: documentation, chore

#5506 Always skip controller-runtime name validation
  pkg/autopilot/controller/root_controller.go
  pkg/autopilot/controller/root_worker.go
Labels: bug, component/autopilot, backport/release-1.32

#5509 Deprecate Autopilot client factory
  .golangci.yml
  cmd/controller/controller.go
  internal/autopilot/testutil/client.go
  pkg/autopilot/client/client.go
  pkg/autopilot/controller/readyprober.go
  pkg/autopilot/controller/root_controller.go
  pkg/autopilot/controller/root_worker.go
  pkg/autopilot/controller/setup.go
  pkg/component/controller/autopilot.go
  pkg/component/controller/updateprober.go
  pkg/component/status/status.go
  pkg/component/worker/autopilot.go
Labels: chore, component/autopilot

#5520 Handle pushgateway image as any other image
  pkg/airgap/images.go
  pkg/apis/k0s/v1beta1/images.go
  pkg/apis/k0s/v1beta1/images_test.go
Labels: bug, area/configuration, backport/release-1.29, backport/release-1.30, backport/release-1.31, backport/release-1.32

#5515 Bump Go to v1.23.6
  embedded-bins/Makefile.variables
Labels: chore, backport/release-1.32

#5517 Bump cosign to v2.4.2
  .github/workflows/release.yml
  Makefile
Labels: area/ci, chore

#5540 [Backport 1.31] Handle pushgateway image as any other image
  pkg/airgap/images.go
  pkg/apis/k0s/v1beta1/images.go
  pkg/apis/k0s/v1beta1/images_test.go
Labels: bug, area/configuration, backport/release-1.29, backport/release-1.30

#5438 Decouple controller flags from CLIOptions struct
  cmd/controller/controller.go
  cmd/install/controller.go
  cmd/worker/worker.go
  cmd/worker/worker_other.go
  cmd/worker/worker_unix.go
  pkg/config/cli.go
Labels: area/controlplane, chore, area/cli

#5534 [release-1.30] Bump Envoy to v1.30.9
  pkg/constant/constant.go
Labels: area/worker, chore

#5536 Bump golangci-lint to v1.63.3
  .golangci.yml
  hack/tools/Makefile.variables
Labels: area/ci, chore

#5533 [release-1.32] Bump Envoy to v1.31.5
  pkg/constant/constant.go
Labels: area/worker, chore, backport/release-1.31

#5529 Bump containerd to v1.7.25
  docs/airgap-install.md
  docs/external-runtime-deps.md
  docs/nllb.md
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/worker, area/containers, chore, component/containerd, backport/release-1.32

#5518 Bump kine to v0.13.9
  embedded-bins/Makefile.variables
  pkg/component/controller/kine.go
Labels: area/controlplane, chore, component/kine, backport/release-1.32

#5513 docs: Pi-5 k0s installation instructions
  docs/raspberry-pi5.md
  mkdocs.yml
Labels: documentation

#5505 Don't trim paths when DEBUG is not false
  Makefile
Labels: chore

#5545 Replace markdownlint GitHub Action
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/docs.yml
Labels: area/ci, chore

#5532 Bump Envoy to v1.32.3
  pkg/constant/constant.go
Labels: area/worker, chore

#5522 Bump etcd to v3.5.18
  embedded-bins/Makefile.variables
  go.mod
  go.sum
  pkg/component/controller/etcd.go
Labels: area/controlplane, component/etcd, chore, backport/release-1.32

#5528 Bump runc to v1.2.4
  embedded-bins/Makefile.variables
Labels: area/worker, chore, component/runc, backport/release-1.32

#5514 Remove storage parameter from DefaultClusterConfig
  cmd/config/validate.go
  pkg/apis/k0s/v1beta1/clusterconfig_types.go
  pkg/apis/k0s/v1beta1/clusterconfig_types_test.go
  pkg/apis/k0s/v1beta1/extenstions_test.go
  pkg/apis/k0s/v1beta1/images_test.go
  pkg/apis/k0s/v1beta1/network_test.go
  pkg/apis/k0s/v1beta1/nllb_test.go
  pkg/apis/k0s/v1beta1/storage_test.go
  pkg/backup/manager_unix.go
  pkg/component/controller/workerconfig/reconciler_test.go
  pkg/config/cfgvars.go
  pkg/config/cfgvars_test.go
Labels: area/configuration, chore

#5507 Use unique controller names for Autopilot
  pkg/autopilot/controller/plans/init.go
  pkg/autopilot/controller/root_controller.go
  pkg/autopilot/controller/root_worker.go
  pkg/autopilot/controller/signal/airgap/download.go
  pkg/autopilot/controller/signal/airgap/init.go
  pkg/autopilot/controller/signal/airgap/signal.go
  pkg/autopilot/controller/signal/init.go
  pkg/autopilot/controller/signal/k0s/apply.go
  pkg/autopilot/controller/signal/k0s/cordon.go
  pkg/autopilot/controller/signal/k0s/download.go
  pkg/autopilot/controller/signal/k0s/init.go
  pkg/autopilot/controller/signal/k0s/restart_unix.go
  pkg/autopilot/controller/signal/k0s/restarted_unix.go
  pkg/autopilot/controller/signal/k0s/signal.go
  pkg/autopilot/controller/signal/k0s/uncordon.go
Labels: bug, component/autopilot

#5521 [release-1.32] Bump libseccomp to v2.5.6
  embedded-bins/runc/Dockerfile
Labels: area/worker, chore, component/runc, backport/release-1.31

#5552 [Backport release-1.31] Bump kine to v0.13.9
  embedded-bins/Makefile.variables
  pkg/component/controller/kine.go
Labels: area/controlplane, chore, component/kine

#5523 Bump controller-tools to v0.17.1
  hack/tools/Makefile.variables
  static/_crds/autopilot/autopilot.k0sproject.io_controlnodes.yaml
  static/_crds/autopilot/autopilot.k0sproject.io_plans.yaml
  static/_crds/autopilot/autopilot.k0sproject.io_updateconfigs.yaml
  static/_crds/etcd/etcd.k0sproject.io_etcdmembers.yaml
  static/_crds/helm/helm.k0sproject.io_charts.yaml
  static/_crds/k0s/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore

#5557 Use correct permissions when cleanuing up old PRs
  .github/workflows/pr-closed.yaml
Labels: bug, area/ci

#5548 Enable usetesting linter
  .golangci.yml
  cmd/config/validate_test.go
  pkg/component/worker/ocibundle_test.go
Labels: area/ci, chore

#5531 Bump cri-dockerd to v0.3.16
  inttest/bootloose-alpine/Dockerfile
Labels: chore, area/smoke-tests

#5567 Don't try to install iptables binaries on non-Linux workers
  cmd/worker/worker.go
Labels: bug, area/worker, area/windows

#5568 Completely remove old Windows-only CLI flags
  cmd/controller/controller_test.go
  cmd/install/controller_test.go
  cmd/install/worker.go
  docs/experimental-windows.md
  pkg/config/cli.go
Labels: documentation, area/windows, chore, area/cli

#5487 Don't use join tokens to bootstrap embedded kubelet
  cmd/controller/controller.go
  cmd/token/preshared.go
  cmd/worker/worker.go
  pkg/component/worker/kubelet.go
  pkg/component/worker/utils.go
  pkg/token/joinclient.go
  pkg/token/joinclient_test.go
  pkg/token/kubeconfig.go
Labels: enhancement, area/worker

#5569 Bump Alpine to 3.21.2
  embedded-bins/Makefile.variables
Labels: chore, backport/release-1.32

#5477 Allow to override k0sctl version in OS tests matrix
  .github/workflows/ostests-matrix.yaml
Labels: area/ci, chore

#5570 [release-1.31] Bump Alpine to 3.20.5
  embedded-bins/Makefile.variables
Labels: chore

#5571 [release-1.30] Bump Alpine to 3.19.6
  embedded-bins/Makefile.variables
Labels: chore, backport/release-1.29

#5559 [Backport release-1.31] Bump containerd to v1.7.25
  docs/airgap-install.md
  docs/external-runtime-deps.md
  docs/nllb.md
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/worker, area/containers, chore, component/containerd, backport/release-1.30

#5511 [Backport release-1.31] Always skip controller-runtime name validation
  pkg/autopilot/controller/root_controller.go
  pkg/autopilot/controller/root_worker.go
Labels: bug, component/autopilot

#5466 Use shared k0s build workflow in nighty network conformance runs
  .github/workflows/check-network.yaml
Labels: area/ci, chore

#5578 Document --kubelet-root-dir flag
  docs/configuration.md
Labels: documentation, backport/release-1.32

#5580 fix: kernel modules not enabled, modprobe is not executed
  pkg/component/worker/kernelsetup_linux.go
Labels: bug, area/worker, backport/release-1.32

#5593 Bump kine to v0.13.10 (to fix a bug introduced in v0.13.4)
  embedded-bins/Makefile.variables
  pkg/component/controller/kine.go
Labels: bug, area/controlplane, component/kine, backport/release-1.32

#5476 Validate removed apis
  pkg/autopilot/checks/checks.go
  pkg/autopilot/checks/removedapis.go
  pkg/autopilot/checks/removedapis_test.go
Labels: backport/release-1.31, backport/release-1.32

#5601 Ignore replacement errors for containerd executables on Windows
  pkg/component/worker/containerd/component.go
Labels: area/worker, area/windows, component/containerd

#5600 Include last error when waiting for containerd failed
  pkg/component/worker/containerd/component.go
Labels: area/worker, chore, component/containerd

#5602 Use correct containerd endpoints on Windows
  cmd/ctr/ctr.go
  pkg/component/worker/cri_runtime.go
  pkg/component/worker/ocibundle.go
Labels: bug, area/worker, area/windows, component/containerd

#5560 [Backport release 1.31] Bump etcd to v3.5.18
  embedded-bins/Makefile.variables
  go.mod
  go.sum
  pkg/component/controller/etcd.go
Labels: area/controlplane, component/etcd, chore, backport/release-1.30

#5610 [Backport release-1.30] Bump containerd to v1.7.25
  docs/airgap-install.md
  docs/external-runtime-deps.md
  docs/nllb.md
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/worker, area/containers, chore, component/containerd, backport/release-1.29

#5615 Bump runc to v1.2.5
  embedded-bins/Makefile.variables
Labels: area/containers, area/dependencies, backport/release-1.32

#5616 [Backport release-1.29] Bump containerd to v1.7.25
  docs/external-runtime-deps.md
  docs/nllb.md
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
  hack/tool/go.mod
Labels: area/containers, chore, component/containerd

#5617 [Backport release-1.29]: Bump etcd to v3.5.18
  embedded-bins/Makefile.variables
  go.mod
  go.sum
  pkg/component/controller/etcd.go
Labels: area/controlplane, component/etcd, chore

#5627 [Release-1.31] Bump alpine version to 3.20.6
  embedded-bins/Makefile.variables
Labels: security fix

#5628 [Release-1.30] Bump alpine version to 3.19.7
  embedded-bins/Makefile.variables
Labels: security fix, backport/release-1.29

#5626 Bump alpine version to 3.21.3
  embedded-bins/Makefile.variables
Labels: security fix, backport/release-1.32

#5581 Initialize common directories once
  cmd/controller/controller.go
  cmd/kubeconfig/admin_test.go
  cmd/worker/worker.go
  pkg/assets/stage.go
  pkg/component/controller/apiserver.go
  pkg/component/controller/controllermanager.go
  pkg/component/controller/cplb/cplb_linux.go
  pkg/component/controller/etcd.go
  pkg/component/controller/kine.go
  pkg/component/controller/konnectivity.go
  pkg/component/controller/scheduler.go
  pkg/component/iptables/iptables.go
  pkg/component/status/status.go
  pkg/component/worker/containerd/component.go
  pkg/component/worker/kubelet.go
  pkg/config/runtime.go
  pkg/config/runtime_test.go
  pkg/supervisor/supervisor.go
  pkg/supervisor/supervisor_test.go
Labels: chore

#5634 Bump containerd to 1.7.26
  docs/airgap-install.md
  docs/external-runtime-deps.md
  docs/nllb.md
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: backport/release-1.29, backport/release-1.30, backport/release-1.31, backport/release-1.32

#5637 [Backport release-1.31] Bump containerd to 1.7.26
  docs/airgap-install.md
  docs/external-runtime-deps.md
  docs/nllb.md
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: backport/release-1.29, backport/release-1.30
