Repository k0sproject/k0s, pull requests merged in 2025-07, with the labels that each got.

#6030 Use OS tests in release workflow
  .github/workflows/ostests-e2e.yaml
  .github/workflows/release.yml
  RELEASE.md
  docs/conformance-testing.md
  docs/contributors/testing.md
  inttest/sonobuoy/README.md
  inttest/sonobuoy/terraform/.gitignore
  inttest/sonobuoy/terraform/controller.tf
  inttest/sonobuoy/terraform/k0sctl.tf
  inttest/sonobuoy/terraform/main.tf
  inttest/sonobuoy/terraform/output.tf
  inttest/sonobuoy/terraform/variables.tf
  inttest/sonobuoy/terraform/vpc.tf
  inttest/sonobuoy/terraform/worker.tf
Labels: area/ci, chore

#6072 Fix the nightly OS tests Slack notification
  .github/workflows/ostests-nightly.yaml
Labels: bug, area/ci

#6006 Switch to stable stream for Fedora CoreOS in OS tests
  .github/workflows/ostests-matrix.yaml
  .github/workflows/ostests-nightly.yaml
  hack/ostests/README.md
  hack/ostests/modules/os/main.tf
  hack/ostests/modules/os/os_fcos_41.tf
  hack/ostests/modules/os/os_fcos_stable.tf
Labels: area/ci, chore

#6053 [docs] make security docs always point to main
  docs/security.md
Labels: backport/release-1.32, backport/release-1.33

#6075 One graceful termination request per orphaned process
  pkg/supervisor/supervisor.go
Labels: chore

#6055 Implement NLLB IPv6 test
  inttest/Makefile
  inttest/Makefile.variables
  inttest/nllb/nllb_test.go
Labels: area/network

#6044 Docs improvements: style, formatting, typos
  ADOPTERS.md
  docs/airgap-install.md
  docs/autopilot-multicommand.md
  docs/autopilot.md
  docs/backup.md
  docs/configuration.md
  docs/cplb.md
  docs/custom-ca.md
  docs/dual-stack.md
  docs/dynamic-configuration.md
  docs/environment-variables.md
  docs/examples/nginx-ingress.md
  docs/examples/rook-ceph.md
  docs/examples/traefik-ingress.md
  docs/experimental-windows.md
  docs/external-runtime-deps.md
  docs/governance/cncf/gtr.md
  docs/governance/cncf/security-self-assessment.md
  docs/helm-charts.md
  docs/high-availability.md
  docs/install.md
  docs/internal/upgrading-calico.md
  docs/k0s-in-docker.md
  docs/k0s-multi-node.md
  docs/networking.md
  docs/raspberry-pi5.md
  docs/remove_controller.md
  docs/runtime.md
  docs/selinux.md
  docs/storage.md
  docs/system-monitoring.md
  docs/system-requirements.md
  docs/troubleshooting/FAQ.md
  docs/troubleshooting/logs.md
  docs/troubleshooting/troubleshooting.md
  docs/upgrade.md
  docs/user-management.md
  docs/worker-node-config.md
Labels: documentation, chore

#6064 Bump kubernetes to v1.34.0-alpha.2
  embedded-bins/Makefile.variables
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/component/controller/workerconfig/reconciler_test.go
  pkg/component/worker/kubelet.go
  pkg/constant/constant.go
  pkg/token/kubeconfig_test.go
  static/_crds/k0s/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore

#6085 Use Go's os.Process API when cleaning up PID files
  pkg/supervisor/prochandle.go
  pkg/supervisor/prochandle_unix.go
  pkg/supervisor/prochandle_windows.go
  pkg/supervisor/supervisor.go
Labels: chore

#6094 Use Ctrl+Break events to shutdown supervised Windows processes
  pkg/supervisor/detachattr_windows.go
  pkg/supervisor/prochandle_unix.go
  pkg/supervisor/prochandle_windows.go
  pkg/supervisor/supervisor.go
Labels: enhancement, area/windows

#6099 [release-1.32] Verify airgap bundle integrity in bundler script
  .github/workflows/build-airgap-image-bundle.yml
  hack/image-bundler/Dockerfile
  hack/image-bundler/bundler.sh
Labels: bug, area/ci, backport/release-1.31

#6107 Parse the keepalived templates in the stack
  pkg/component/controller/cplb/cplb_linux.go
Labels: chore

#6105 [Backport release-1.31] Update dependency go to v1.23.11
  build/Dockerfile
  embedded-bins/Makefile.variables
Labels: dependencies

#6098 [Backport release-1.33] Bump helm.sh/helm/v3 from 3.18.0 to 3.18.4
  go.mod
  go.sum
Labels: security fix, area/helm, dependencies, go

#6109 Let Renovate Bot update container image tags
  renovate.json
Labels: area/ci, chore

#5822 Change worker labels to be a map
  cmd/controller/controller.go
  cmd/controller/controller_test.go
  cmd/install/controller_test.go
  pkg/component/worker/kubelet.go
  pkg/config/cli.go
Labels: chore, area/cli

#6124 Fix semantic merge conflict
  cmd/controller/controller.go
Labels: bug

#6121 Let Renovate run every four hours
  .github/workflows/renovate.yaml
Labels: area/ci, chore

#6120 [Backport release-1.33] Update dependency k3s-io/kine to v0.13.17
  embedded-bins/Makefile.variables
  pkg/component/controller/kine.go
Labels: dependencies, backport/release-1.32

#6146 More generic renovate updates via comments
  .github/workflows/backport.yaml
  .github/workflows/lint.yaml
  .github/workflows/prepare-build-env.sh
  .github/workflows/release.yml
  Makefile
  docs/Makefile.variables
  docs/cplb.md
  embedded-bins/Makefile.variables
  hack/tools/Makefile.variables
  inttest/Makefile.variables
  inttest/bootloose-alpine/Dockerfile
  renovate.json
Labels: area/ci, chore

#6115 Revisit GitHub workflow (ignore) paths
  .github/workflows/build-docs.yml
  .github/workflows/go.yml
  .github/workflows/lint.yaml
Labels: area/ci, chore

#6164 Also bump OpenTofu version in ostests
  .github/workflows/ostests-e2e.yaml
Labels: area/ci, chore

#6171 Don't ignore the Go build workflow file itself
  .github/workflows/go.yml
Labels: bug, area/ci

#6177 Allow release workflow to push images to GHCR
  .github/workflows/release.yml
Labels: bug, area/ci, backport/release-1.31, backport/release-1.32, backport/release-1.33

#6062 Fix CRI runtime connections on Windows
  cmd/ctr/ctr.go
  pkg/component/worker/containerd/component.go
  pkg/component/worker/containerd/utils_other.go
  pkg/component/worker/containerd/utils_windows.go
  pkg/component/worker/cri_runtime.go
  pkg/component/worker/ocibundle.go
  pkg/container/runtime/cri.go
  pkg/container/runtime/cri_other.go
  pkg/container/runtime/cri_windows.go
  pkg/container/runtime/runtime.go
Labels: bug, area/containers, area/windows

#6172 Use more imperative voice in the docs
  docs/install.md
  docs/k0s-multi-node.md
  docs/podsecurity.md
  docs/support-bundle-controller.yaml
  docs/support-bundle-worker.yaml
  docs/troubleshooting/certificate-authorities.md
  docs/troubleshooting/logs.md
  docs/troubleshooting/support-dump.md
Labels: documentation

#6174 Determine inttest configs from smoke test name
  inttest/Makefile
  inttest/common/bootloosesuite.go
  inttest/cplb-ipvs/cplbipvs_test.go
  inttest/cplb-userspace/cplbuserspace_test.go
  inttest/customports/customports_test.go
  inttest/dualstack/dualstack_test.go
  inttest/ipv6/ipv6_test.go
  inttest/metricsscraper/metricsscraper_test.go
  inttest/network-conformance/network_test.go
  inttest/nllb/nllb_test.go
Labels: chore, area/smoke-tests

#6188 Add CNCF required footer to docs
  mkdocs.yml
Labels: documentation, backport/release-1.31, backport/release-1.32, backport/release-1.33

#6194 Use tags instead of releases when updating keepalived
  embedded-bins/Makefile.variables
Labels: bug, area/ci

#6070 Run gopls modernize
  cmd/etcd/list.go
  cmd/sysinfo/sysinfo.go
  internal/pkg/flags/flags.go
  internal/pkg/strictyaml/strictyaml.go
  internal/pkg/stringmap/stringmap.go
  internal/pkg/sysinfo/probes/linux/linux_test.go
  internal/pkg/templatewriter/templatewriter.go
  internal/testutil/manifest_parser.go
  inttest/addons/addons_test.go
  inttest/ap-removedapis/removedapis_test.go
  inttest/common/filetools.go
  inttest/k0scloudprovider/k0scloudprovider_test.go
  inttest/reset/reset_test.go
  pkg/apis/autopilot/v1beta2/types.go
  pkg/apis/autopilot/v1beta2/updateconfig.go
  pkg/apis/autopilot/v1beta2/zz_generated.deepcopy.go
  pkg/apis/etcd/v1beta1/types.go
  pkg/apis/helm/v1beta1/chart_types.go
  pkg/apis/helm/v1beta1/generic_hash.go
  pkg/apis/k0s/v1beta1/api.go
  pkg/apis/k0s/v1beta1/cert.go
  pkg/apis/k0s/v1beta1/clusterconfig_types.go
  pkg/apis/k0s/v1beta1/clusterconfig_types_test.go
  pkg/apis/k0s/v1beta1/cplb.go
  pkg/apis/k0s/v1beta1/extensions.go
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/apis/k0s/v1beta1/network.go
  pkg/apis/k0s/v1beta1/nllb_test.go
  pkg/apis/k0s/v1beta1/workerprofile.go
  pkg/apis/k0s/v1beta1/workerprofile_test.go
  pkg/apis/k0s/v1beta1/zz_generated.deepcopy.go
  pkg/applier/manager_test.go
  pkg/applier/meta.go
  pkg/applier/stack.go
  pkg/autopilot/signaling/v2/marshal.go
  pkg/autopilot/updater/api.go
  pkg/component/controller/calico_test.go
  pkg/component/controller/konnectivity.go
  pkg/component/controller/kubeproxy_test.go
  pkg/component/iptables/iptables_test.go
  pkg/component/prober/events.go
  pkg/component/prober/prober.go
  pkg/component/status/client.go
  pkg/component/worker/kernelsetup_linux.go
  pkg/component/worker/nllb/reconciler_test.go
  pkg/component/worker/static_pods.go
  pkg/component/worker/static_pods_test.go
  pkg/config/runtime.go
  pkg/etcd/client.go
  pkg/helm/helm.go
  pkg/install/service_linux.go
  pkg/k0scloudprovider/addresses.go
  pkg/k0scontext/context_test.go
  pkg/supervisor/supervisor_test.go
  pkg/telemetry/telemetry.go
Labels: chore
