Repository k0sproject/k0s, pull requests merged in 2025-01, with the labels that each got.

#5392 Remove duplicate test
  cmd/config/config_test.go
Labels: chore

#5317 Bump kube-router to v2.4.1
  pkg/constant/constant.go
Labels: area/network, chore, component/kube-router

#5403 Replace dig with plain maps
  go.mod
  go.sum
  pkg/component/controller/kuberouter_test.go
Labels: chore

#5370 Move hard-coded cgroup settings into worker profiles
  pkg/component/controller/workerconfig/reconciler.go
  pkg/component/controller/workerconfig/reconciler_test.go
  pkg/component/worker/kubelet.go
Labels: enhancement, area/configuration, area/worker

#5375 Remove redundant logrus.SetOutput(stderr) statements
  cmd/api/api.go
  cmd/backup/backup_unix.go
  cmd/controller/controller.go
  cmd/etcd/list.go
  cmd/kubeconfig/admin.go
  cmd/kubeconfig/create.go
  cmd/root.go
  cmd/worker/worker.go
  main.go
Labels: chore, area/cli

#5374 Disable BuildKit's InvalidDefaultArgInFrom build check
  embedded-bins/Makefile
Labels: chore

#5415 Narrow down kubelet-root-dir flag
  cmd/reset/reset.go
  pkg/config/cli.go
Labels: chore, area/cli

#5418 Include Security Policy in the docs
  SECURITY.md
  docs/security.md
  mkdocs.yml
Labels: documentation

#5365 Tweak and document disabling Docker build integration
  .github/workflows/go.yml
  Makefile
  README.md
Labels: chore

#5420 Remove unused CfgVars origin
  pkg/config/cfgvars.go
Labels: area/configuration, chore

#5417 Remove legacy runtime config migration
  pkg/config/runtime.go
  pkg/config/runtime_test.go
Labels: area/configuration, chore

#5416 Show help again for non-leaf subcommands
  cmd/airgap/airgap.go
  cmd/config/config.go
  cmd/etcd/etcd.go
  cmd/install/install.go
  cmd/kubeconfig/kubeconfig.go
  cmd/token/token.go
Labels: chore, area/cli

#5426 Use localhost in admin kubeconfig again, if possible
  cmd/controller/certificates.go
  cmd/kubeconfig/admin.go
  pkg/apis/k0s/v1beta1/api.go
Labels: bug, area/controlplane, backport/release-1.31

#5423 Only use persistent flags if appropriate
  cmd/airgap/airgap.go
  cmd/airgap/listimages.go
  cmd/api/api.go
  cmd/backup/backup_unix.go
  cmd/config/create.go
  cmd/config/edit.go
  cmd/config/status.go
  cmd/config/validate.go
  cmd/controller/controller.go
  cmd/etcd/etcd.go
  cmd/etcd/leave.go
  cmd/etcd/list.go
  cmd/install/controller.go
  cmd/install/install.go
  cmd/install/worker.go
  cmd/kubeconfig/admin.go
  cmd/kubeconfig/create.go
  cmd/kubeconfig/kubeconfig.go
  cmd/reset/reset.go
  cmd/restore/restore_unix.go
  cmd/status/status.go
  cmd/token/create.go
  cmd/token/invalidate.go
  cmd/token/list.go
  cmd/token/preshared.go
  cmd/version/version.go
  cmd/worker/worker.go
Labels: chore, area/cli

#5433 Don't cache the node config in the CfgVars struct
  pkg/config/cfgvars.go
  pkg/config/cfgvars_test.go
  pkg/config/cli.go
  pkg/config/runtime.go
  pkg/config/runtime_test.go
Labels: area/configuration, chore

#5422 Let API subcommand accept the runtime config via stdin
  cmd/api/api.go
  cmd/controller/controller.go
  pkg/component/controller/k0scontrolapi.go
  pkg/config/runtime.go
  pkg/config/runtime_test.go
  pkg/supervisor/supervisor.go
Labels: chore, area/cli

#5440 [release-1.29] Bump Kubernetes to v1.29.13
  .github/workflows/publish-docs-manual.yml
  embedded-bins/Makefile.variables
  examples/bootloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/constant/constant_shared.go
  static/manifests/v1beta1/CustomResourceDefinition/k0s.k0sproject.io_clusterconfigs.yaml
Labels: security fix

#5441 [release-1.30] Bump Kubernetes to v1.30.9
  .github/workflows/publish-docs-manual.yml
  embedded-bins/Makefile.variables
  examples/bootloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/constant/constant.go
  static/_crds/v1beta1/k0s.k0sproject.io_clusterconfigs.yaml
Labels: security fix

#5442 Bump Kubernetes to v1.31.5
  .github/workflows/publish-docs-manual.yml
  cncf/GTR.md
  cncf/security-self-assessment.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
  hack/tool/go.mod
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/constant/constant.go
  static/_crds/k0s/k0s.k0sproject.io_clusterconfigs.yaml
Labels: security fix, backport/release-1.31

#5445 Use full patch version for go directives in go.mod
  go.mod
  hack/tool/go.mod
Labels: chore

#5447 [Backport release-1.31] Bump Kubernetes to v1.31.5
  .github/workflows/publish-docs-manual.yml
  embedded-bins/Makefile.variables
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/constant/constant.go
  static/_crds/k0s/k0s.k0sproject.io_clusterconfigs.yaml
Labels: security fix

#5457 Airgap image bundle verification in GH Action step
  .github/workflows/build-airgap-image-bundle.yml
Labels: area/ci, chore

#5451 EtcdMember full resync on leader change
  inttest/etcdmember/etcdmember_test.go
  pkg/apis/etcd/v1beta1/types.go
  pkg/component/controller/etcd_member_reconciler.go
Labels: bug, area/controlplane, component/etcd

#5454 Load node configuration only once
  cmd/backup/backup_unix.go
  cmd/controller/controller.go
  cmd/reset/reset.go
  cmd/token/create.go
  pkg/backup/manager_unix.go
  pkg/cleanup/cleanup.go
  pkg/component/controller/coredns.go
  pkg/config/runtime.go
  pkg/config/runtime_test.go
Labels: area/configuration, chore

#5458 [Backport release-1.31] Do full EtcdMember re-sync on leader changes
  inttest/etcdmember/etcdmember_test.go
  pkg/apis/etcd/v1beta1/types.go
  pkg/component/controller/etcd_member_reconciler.go
Labels: bug, area/controlplane, component/etcd, backport/release-1.30

#5459 Bump go 1.23.5
  embedded-bins/Makefile.variables
Labels: chore

#5469 Bump Ubuntu runners to 24.04
  .github/workflows/backport.yaml
  .github/workflows/build-airgap-image-bundle.yml
  .github/workflows/build-docs.yml
  .github/workflows/build-k0s.yml
  .github/workflows/check-network.yaml
  .github/workflows/commit.yaml
  .github/workflows/conflicts.yaml
  .github/workflows/dco.yaml
  .github/workflows/dependabot-prs.yaml
  .github/workflows/docs.yml
  .github/workflows/go.yml
  .github/workflows/lint.yaml
  .github/workflows/ostests-e2e.yaml
  .github/workflows/ostests-nightly.yaml
  .github/workflows/publish-docs-manual.yml
  .github/workflows/publish-docs.yml
  .github/workflows/release.yml
  .github/workflows/sbom-upload.yml
  .github/workflows/smoketest.yaml
  .github/workflows/stale.yml
Labels: area/ci, chore

#5471 Update flowcontrol entries in removed APIs
  pkg/autopilot/checks/removedapis.go
Labels: bug, component/autopilot, backport/release-1.29, backport/release-1.30, backport/release-1.31

#5437 Always treat an etcd backend as joinable
  pkg/apis/k0s/v1beta1/storage.go
  pkg/apis/k0s/v1beta1/storage_test.go
Labels: enhancement, area/controlplane, component/etcd

#5479 Revert "Remove default-config and validate sub-commands"
  cmd/root.go
  cmd/validate/validate.go
Labels: chore, area/cli

#5472 Sleep 5 secs after airgap image bundle creation
  hack/image-bundler/bundler.sh
Labels: bug, area/ci

#5482 Add note to the example of Manifest Deployer
  docs/manifests.md
Labels: documentation

#5489 Disable Go telemetry in Docker based builds
  build/Dockerfile
Labels: area/ci, chore

#5488 Share node name detection between controller and worker
  cmd/controller/controller.go
  cmd/worker/worker.go
  pkg/autopilot/common/hostname.go
  pkg/component/controller/controllersleasecounter.go
  pkg/component/worker/kubelet.go
  pkg/component/worker/utils.go
  pkg/node/nodename.go
  pkg/node/nodename_other.go
  pkg/node/nodename_test.go
  pkg/node/nodename_windows.go
  pkg/node/nodename_windows_test.go
Labels: area/controlplane, chore

#5494 Add 1.32.x as maintained
  SECURITY.md
Labels: bug, documentation, backport/release-1.32
