Repository k0sproject/k0s, pull requests merged in 2025-06, with the labels that each got.

#5908 Remove leader election callbacks from EtcdMemberReconciler
  pkg/component/controller/etcd_member_reconciler.go
Labels: area/controlplane, chore

#5909 Replace leader election callbacks in Helm extensions manager
  pkg/component/controller/extensions_controller.go
Labels: chore, area/helm

#5934 Improve/extend renovate config (go version updates)
  build/Dockerfile
  internal/pkg/file/atomic_test.go
  renovate.json
Labels: area/ci, chore

#5901 Support extensions from OCI registries with self-signed CA
  docs/extensions.md
  docs/helm-charts.md
  inttest/addons/addons_test.go
  inttest/addons/testdata/chart/echo-server-0.5.0.tgz
  inttest/common/bootloosesuite.go
  pkg/helm/helm.go
  pkg/helm/oci.go
  pkg/helm/oci_test.go
Labels: enhancement, area/configuration, backport/release-1.33

#5946 Fix docs links in pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#5945 [Backport release-1.33] Support extensions from OCI registries with self-signed CA
  docs/extensions.md
  docs/helm-charts.md
  inttest/addons/addons_test.go
  inttest/addons/testdata/chart/echo-server-0.5.0.tgz
  inttest/common/bootloosesuite.go
  pkg/helm/helm.go
  pkg/helm/oci.go
  pkg/helm/oci_test.go
Labels: enhancement, area/configuration, backport/release-1.32

#5921 [Backport release-1.31] Remove timeout from dynamic cluster config initializer
  pkg/component/controller/clusterConfig.go
Labels: bug, area/controlplane, backport/release-1.30

#5959 [release-1.30] Bump calico v3.27.5 0
  pkg/constant/constant.go
Labels: area/network, chore, component/calico

#5955 [release-1.31] Bump calico to 3.28.4-0
  pkg/constant/constant.go
Labels: area/network, chore, component/calico

#5963 Bump CoreDNS to v1.12.2
  docs/configuration.md
  docs/raspberry-pi4.md
  pkg/constant/constant.go
Labels: area/network, chore, backport/release-1.33

#5954 Bump calico to 3.29.4-0
  pkg/constant/constant.go
Labels: area/network, chore, component/calico, backport/release-1.32, backport/release-1.33

#5974 [Backport release-1.32] Bump calico to 3.29.4-0
  pkg/constant/constant.go
Labels: area/network, chore, component/calico

#5977 [Backport release-1.31] Update dependency go to v1.23.10
  build/Dockerfile
  embedded-bins/Makefile.variables
  go.mod
  hack/tool/go.mod
  internal/http/download.go
  internal/http/download_test.go
Labels: chore

#5975 [Backport release-1.32] Bump CoreDNS to v1.12.2
  docs/configuration.md
  docs/raspberry-pi4.md
  pkg/constant/constant.go
Labels: area/network, chore

#5962 Overhaul docs templating
  .github/workflows/publish-docs.yml
  Makefile
  docs/.gitignore
  docs/Dockerfile.serve-dev
  docs/Makefile
  docs/airgap-install.md
  docs/autopilot-multicommand.md
  docs/autopilot.md
  docs/compose-cluster.yaml
  docs/compose.yaml
  docs/configuration.md
  docs/cplb.md
  docs/install.md
  docs/k0s-in-docker.md
  docs/k0s-multi-node.md
  docs/k0sctl-install.md
  docs/mkdocs_modules/k0s_mkdocs_hacks/macros.py
  docs/nllb.md
  docs/raspberry-pi4.md
  docs/raspberry-pi5.md
  docs/releases.md
  docs/reset.md
  docs/runtime.md
  docs/upgrade.md
  docs/verifying-signs.md
  docs/worker-node-config.md
  mkdocs.yml
Labels: documentation, area/ci, backport/release-1.33

#5986 Fix docs version updates
  .github/workflows/publish-docs.yml
Labels: bug, documentation, area/ci

#5994 Fix docs version updates, attempt 2
  .github/workflows/publish-docs.yml
Labels: bug, documentation, area/ci

#5996 Remove autopilot example files
  examples/autopilot/plan.yaml
  examples/autopilot/update-server-unstable.yaml
  examples/autopilot/updateconfig.yaml
Labels: chore

#5985 Only set cgroups kubelet flag on Linux
  pkg/component/worker/kubelet.go
Labels: area/worker, chore, component/kubelet

#5991 Re-add k0s 1.32 as maintained
  SECURITY.md
Labels: bug, documentation, backport/release-1.33

#5874 [release-1.33] Wait for lease pool shutdown when stopping components
  pkg/autopilot/controller/leases.go
  pkg/component/controller/controllersleasecounter.go
  pkg/component/controller/leaderelector/leasepool.go
  pkg/leaderelection/lease_pool.go
  pkg/leaderelection/lease_pool_test.go
Labels: bug, area/controlplane, backport/release-1.32

#6018 [Backport release-1.33] Overhaul docs templating
  .github/workflows/publish-docs.yml
  Makefile
  docs/.gitignore
  docs/Dockerfile.serve-dev
  docs/Makefile
  docs/airgap-install.md
  docs/autopilot-multicommand.md
  docs/autopilot.md
  docs/compose-cluster.yaml
  docs/compose.yaml
  docs/configuration.md
  docs/cplb.md
  docs/install.md
  docs/k0s-in-docker.md
  docs/k0s-multi-node.md
  docs/k0sctl-install.md
  docs/mkdocs_modules/k0s_mkdocs_hacks/macros.py
  docs/nllb.md
  docs/raspberry-pi4.md
  docs/raspberry-pi5.md
  docs/releases.md
  docs/reset.md
  docs/runtime.md
  docs/upgrade.md
  docs/verifying-signs.md
  docs/worker-node-config.md
  mkdocs.yml
Labels: documentation, area/ci, backport/release-1.32

#6013 [release-1.30] Bump Kubernetes to v1.30.14
  embedded-bins/Makefile.variables
  examples/bootloose-ha-controllers/Dockerfile
  go.mod
  go.sum
  hack/tool/go.mod
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/constant/constant.go
  static/_crds/v1beta1/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore

#6024 [docs] Use version macro in some additional places
  docs/governance/cncf/gtr.md
Labels: documentation, backport/release-1.33

#5992 Remove manual docs publishing workflow
  .github/workflows/publish-docs-manual.yml
Labels: documentation, area/ci, chore

#6019 [Backport release-1.30] Wait for lease pool shutdown when stopping components
  cmd/controller/controller.go
  internal/sync/value/latest.go
  internal/sync/value/latest_test.go
  pkg/autopilot/controller/leases.go
  pkg/autopilot/controller/updates/clusterinfo.go
  pkg/component/controller/controllersleasecounter.go
  pkg/component/controller/konnectivity.go
  pkg/component/controller/konnectivityagent.go
  pkg/component/controller/leaderelector/leasepool.go
  pkg/kubernetes/lease.go
  pkg/leaderelection/lease_pool.go
  pkg/leaderelection/lease_pool_test.go
  pkg/telemetry/telemetry.go
Labels: bug, area/controlplane

#6026 Use Mergiraf when backporting PRs
  .github/workflows/backport.yaml
  renovate.json
Labels: area/ci

#6020 [Backport release-1.32] Overhaul docs templating
  .github/workflows/publish-docs.yml
  Makefile
  docs/.gitignore
  docs/Dockerfile.serve-dev
  docs/Makefile
  docs/airgap-install.md
  docs/autopilot-multicommand.md
  docs/autopilot.md
  docs/compose.yaml
  docs/configuration.md
  docs/cplb.md
  docs/install.md
  docs/k0s-in-docker.md
  docs/k0s-multi-node.md
  docs/k0sctl-install.md
  docs/mkdocs_modules/k0s_mkdocs_hacks/macros.py
  docs/nllb.md
  docs/raspberry-pi4.md
  docs/releases.md
  docs/reset.md
  docs/runtime.md
  docs/upgrade.md
  docs/verifying-signs.md
  docs/worker-node-config.md
  mkdocs.yml
Labels: documentation, area/ci, backport/release-1.31

#6028 [Backport release-1.33] Replace hardcoded k0s versions in docs
  .github/workflows/publish-docs-manual.yml
  SECURITY.md
  docs/examples/ambassador-ingress.md
  docs/governance/cncf/gtr.md
  docs/governance/cncf/security-self-assessment.md
  docs/mkdocs_modules/k0s_mkdocs_hacks/macros.py
  docs/releases.md
  docs/verifying-signs.md
  examples/autopilot/plan.yaml
  examples/autopilot/update-server-unstable.yaml
  examples/autopilot/updateconfig.yaml
  mkdocs.yml
Labels: chore

#6031 [conformance] Replace removed vpc for domain
  inttest/sonobuoy/terraform/controller.tf
Labels: bug, github_actions, backport/release-1.30, backport/release-1.31, backport/release-1.32, backport/release-1.33

#6029 Removing memory limit for CoreDNS
  pkg/component/controller/coredns.go
Labels: backport/release-1.31, backport/release-1.32, backport/release-1.33

#6007 Drop nightly network conformance tests
  .github/workflows/check-network.yaml
  .github/workflows/ostests-nightly.yaml
  README.md
Labels: area/ci, chore

#6005 Remove Debian 10 from OS tests as it's EOL
  .github/workflows/ostests-matrix.yaml
  .github/workflows/ostests-nightly.yaml
  hack/ostests/README.md
  hack/ostests/modules/os/main.tf
  hack/ostests/modules/os/os_debian_10.tf
Labels: area/ci, chore

#6060 Always run nightly OS test post actions
  .github/workflows/ostests-nightly.yaml
Labels: bug, area/ci
