Repository k0sproject/k0s, pull requests merged in 2025-08, with the labels that each got.

#6241 Improve worker profile validation
  pkg/apis/k0s/v1beta1/workerprofile.go
  pkg/apis/k0s/v1beta1/workerprofile_test.go
Labels: area/configuration, backport/release-1.31, backport/release-1.32, backport/release-1.33

#6231 [Konnectivity] More restrictive security context
  pkg/component/controller/konnectivityagent.go
Labels: chore

#6243 Add "idempotency" to image repository override
  pkg/apis/k0s/v1beta1/images.go
  pkg/apis/k0s/v1beta1/images_test.go
Labels: bug, area/configuration, backport/release-1.31, backport/release-1.32, backport/release-1.33

#6292 Add FOSSA badge
  README.md
Labels: chore

#6264 Semantic kubelet config validation for worker profiles
  go.mod
  go.sum
  pkg/apis/k0s/v1beta1/clusterconfig_types.go
  pkg/apis/k0s/v1beta1/workerprofile.go
  pkg/apis/k0s/v1beta1/workerprofile_test.go
Labels: area/configuration

#6306 Use custom API port in autopilot
  cmd/controller/controller.go
  pkg/autopilot/controller/readyprober.go
  pkg/autopilot/controller/root/root.go
  pkg/autopilot/controller/root_controller.go
  pkg/component/controller/autopilot.go
Labels: backport/release-1.31, backport/release-1.32, backport/release-1.33
