Repository k0sproject/k0s, pull requests merged in 2025-05, with the labels that each got.

#5802 Add initial RISC-V support to Makefile
  Makefile
Labels: chore

#5806 Bump calico to 3.29.3-1
  pkg/constant/constant.go
Labels: chore

#5799 Remove EnableDynamicConfig from CfgVars
  pkg/config/cfgvars.go
  pkg/config/cfgvars_test.go
Labels: area/configuration, chore

#5825 [Backport release-1.32] Remove CGROUP kconfig checks
  docs/external-runtime-deps.md
  docs/raspberry-pi4.md
  internal/pkg/sysinfo/host_linux.go
Labels: area/worker, chore, backport/release-1.31

#5807 Ignore RISC-V Linux airgap image bundle
  .gitignore
Labels: chore

#5808 Bump go mod to 1.24 and toolchain to 1.24.3
  embedded-bins/Makefile.variables
  go.mod
  hack/gen-bindata/gen_bindata_test.go
  hack/tool/go.mod
  internal/http/download_test.go
  internal/http/filename_test.go
  internal/oci/download_test.go
  internal/pkg/file/atomic_test.go
  internal/testutil/context.go
  inttest/common/bootloosesuite.go
  pkg/applier/applier_test.go
  pkg/applier/manager_test.go
  pkg/autopilot/controller/leases_test.go
  pkg/autopilot/controller/plans/cmdprovider/airgapupdate/newplan_test.go
  pkg/autopilot/controller/plans/cmdprovider/airgapupdate/schedulable_test.go
  pkg/autopilot/controller/plans/cmdprovider/airgapupdate/schedulablewait_test.go
  pkg/autopilot/controller/plans/cmdprovider/k0supdate/discovery/discover_test.go
  pkg/autopilot/controller/plans/cmdprovider/k0supdate/newplan_test.go
  pkg/autopilot/controller/plans/cmdprovider/k0supdate/schedulable_test.go
  pkg/autopilot/controller/plans/cmdprovider/k0supdate/schedulablewait_test.go
  pkg/autopilot/controller/plans/cmdprovider/k0supdate/utils/exists_test.go
  pkg/autopilot/controller/plans/core/initprovidershandler_test.go
  pkg/autopilot/controller/plans/core/planstatecontroller_test.go
  pkg/autopilot/controller/plans/core/planstatehandler_test.go
  pkg/autopilot/controller/root_controller_test.go
  pkg/autopilot/controller/signal/airgap/signal_test.go
  pkg/autopilot/controller/signal/k0s/signal_test.go
  pkg/component/controller/apiendpointreconciler_test.go
  pkg/component/controller/clusterconfig_test.go
  pkg/component/controller/csrapprover_test.go
  pkg/component/controller/kuberouter_test.go
  pkg/component/controller/metricserver_test.go
  pkg/component/controller/workerconfig/reconciler_test.go
  pkg/component/manager/manager_test.go
  pkg/component/prober/events_test.go
  pkg/component/prober/prober_test.go
  pkg/component/worker/config/loader_test.go
  pkg/component/worker/nllb/reconciler_test.go
  pkg/component/worker/static_pods_test.go
  pkg/debounce/debounce_test.go
  pkg/k0scontext/context_test.go
  pkg/k0scontext/timeout_test.go
  pkg/kubernetes/watch/watcher_test.go
  pkg/leaderelection/client_test.go
  pkg/leaderelection/lease_pool_test.go
  pkg/token/joinclient_test.go
Labels: chore

#5834 fix(network_config): don't set kuberouter config if calico config provided
  pkg/apis/k0s/v1beta1/network.go
  pkg/apis/k0s/v1beta1/network_test.go
Labels: area/configuration

#5843 Add docs section on how to configure registry mirrors
  docs/runtime.md
Labels: documentation

#5793 Bump Kubernetes to v1.33.0
  SECURITY.md
  cncf/GTR.md
  cncf/security-self-assessment.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
  hack/tool/go.mod
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/client/clientset/fake/clientset_generated.go
  pkg/client/clientset/typed/autopilot/v1beta2/autopilot_client.go
  pkg/client/clientset/typed/etcd/v1beta1/etcd_client.go
  pkg/client/clientset/typed/helm/v1beta1/helm_client.go
  pkg/client/clientset/typed/k0s/v1beta1/k0s_client.go
  pkg/component/controller/workerconfig/reconciler_test.go
  pkg/component/worker/kubelet.go
  pkg/constant/constant.go
  static/_crds/k0s/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore

#5831 CPLB prevent IPVS routing loops
  cmd/keepalived/keepalived_linux.go
  cmd/keepalived/keepalived_linux_test.go
  cmd/root_linux.go
  docs/cplb.md
  inttest/cplb-ipvs/cplbipvs_test.go
  pkg/component/controller/cplb/cplb_linux.go
  pkg/component/controller/cplb/cplb_linux_test.go
Labels: bug, backport/release-1.32

#5855 Use the correct address for BuildServiceCIDR
  cmd/controller/controller.go
  inttest/dualstack/dualstack_test.go
  pkg/component/controller/apiserver.go
Labels: bug, backport/release-1.30, backport/release-1.31, backport/release-1.32

#5858 [release-1.31]Bump kubernetes to v1.31.9
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/docs.yml
  .markdownlint.jsonc
  embedded-bins/Makefile.variables
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/constant/constant.go
  static/_crds/k0s/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore

#5857 [release-1.32] Bump kubernetes to v1.32.5
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/docs.yml
  cncf/GTR.md
  cncf/security-self-assessment.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/component/worker/kubelet.go
  pkg/constant/constant.go
  static/_crds/k0s/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore

#5863 Use a common struct to configure CA related options
  cmd/controller/certificates.go
  cmd/kubeconfig/create.go
  docs/configuration.md
  pkg/apis/k0s/v1beta1/api.go
  pkg/apis/k0s/v1beta1/cert.go
  pkg/apis/k0s/v1beta1/storage.go
  pkg/apis/k0s/v1beta1/zz_generated.deepcopy.go
  pkg/component/controller/etcd.go
  static/_crds/k0s/k0s.k0sproject.io_clusterconfigs.yaml
Labels: area/configuration

#5890 [Backport release-1.32] Use the correct address for BuildServiceCIDR
  cmd/controller/controller.go
  inttest/dualstack/dualstack_test.go
  pkg/component/controller/apiserver.go
Labels: bug, area/network, backport/release-1.31

#5499 Implement leaderelector.Interface in terms of the new leader elector client
  pkg/applier/manager.go
  pkg/applier/manager_test.go
  pkg/component/controller/controllersleasecounter.go
  pkg/component/controller/leaderelector/dummy.go
  pkg/component/controller/leaderelector/leasepool.go
  pkg/component/controller/leaderelector/types.go
  pkg/component/controller/workerconfig/reconciler_test.go
  pkg/leaderelection/tasks.go
Labels: area/controlplane, chore

#5903 Fix spelling in comment
  pkg/leaderelection/tasks.go
Labels: bug

#5902 [Backport release-1.30] Use the correct address for BuildServiceCIDR
  cmd/controller/controller.go
  inttest/dualstack/dualstack_test.go
  pkg/component/controller/apiserver.go
Labels: bug, area/network
