Repository k0sproject/k0s, pull requests merged in 2025-04, with the labels that each got.

#5709 [release-1.31] Bump Kubernetes to v1.31.7
  embedded-bins/Makefile.variables
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  internal/http/download_test.go
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/constant/constant.go
  static/_crds/k0s/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore

#5708 Bump kubernetes to v1.32.3
  Makefile
  cncf/GTR.md
  cncf/security-self-assessment.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/autopilot/v1beta2/zz_generated.register.go
  pkg/apis/etcd/v1beta1/zz_generated.register.go
  pkg/apis/helm/v1beta1/zz_generated.register.go
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/apis/k0s/v1beta1/zz_generated.register.go
  pkg/component/worker/kubelet.go
  pkg/constant/constant.go
  static/_crds/k0s/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore

#5716 [release-1.32] Bump kubernetes to v1.32.3
  Makefile
  cncf/GTR.md
  cncf/security-self-assessment.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
  hack/tool/go.mod
  hack/tool/go.sum
  inttest/sonobuoy/README.md
  inttest/update-server/html/unstable/index.yaml
  pkg/apis/autopilot/v1beta2/zz_generated.register.go
  pkg/apis/etcd/v1beta1/zz_generated.register.go
  pkg/apis/helm/v1beta1/zz_generated.register.go
  pkg/apis/k0s/v1beta1/kubeproxy.go
  pkg/apis/k0s/v1beta1/zz_generated.register.go
  pkg/component/worker/kubelet.go
  pkg/constant/constant.go
  static/_crds/k0s/k0s.k0sproject.io_clusterconfigs.yaml
Labels: chore

#5724 Upload cosign transparency log and verify signatures before release
  .github/workflows/release.yml
  docs/verifying-signs.md
Labels: bug, area/ci, github_actions, backport/release-1.29, backport/release-1.30, backport/release-1.31, backport/release-1.32

#5721 Bump golangci-lint to v2.0.2
  .github/workflows/lint.yaml
  .golangci.yml
  Makefile
  cmd/backup/backup_unix.go
  cmd/controller/controller.go
  cmd/ctr/ctr.go
  cmd/reset/reset.go
  cmd/worker/worker.go
  go.mod
  go.sum
  hack/tools/Makefile.variables
  internal/pkg/dir/dir_unix_test.go
  internal/pkg/sysinfo/probes/linux/kernel.go
  inttest/ap-controllerworker/controllerworker_test.go
  inttest/ap-ha3x3/ha3x3_test.go
  inttest/ap-quorum/quorum_test.go
  inttest/ap-quorumsafety/quorumsafety_test.go
  inttest/ap-selector/selector_test.go
  inttest/backup/backup_test.go
  inttest/basic/basic_test.go
  inttest/common/util.go
  inttest/cplb-ipvs/cplbipvs_test.go
  inttest/cplb-userspace/cplbuserspace_test.go
  inttest/dualstack/dualstack_test.go
  inttest/etcdmember/etcdmember_test.go
  inttest/kubeletcertrotate/kubeletcertrotate_test.go
  pkg/apis/k0s/v1beta1/clusterconfig_types.go
  pkg/apis/k0s/v1beta1/cplb_test.go
  pkg/apis/k0s/v1beta1/extensions.go
  pkg/apis/k0s/v1beta1/feature_gates_test.go
  pkg/apis/k0s/v1beta1/network_test.go
  pkg/applier/manager_test.go
  pkg/autopilot/checks/removedapis_test.go
  pkg/autopilot/controller/signal/common/download.go
  pkg/autopilot/controller/signal/common/signal.go
  pkg/autopilot/controller/signal/k0s/apply.go
  pkg/autopilot/controller/signal/k0s/cordon.go
  pkg/autopilot/controller/signal/k0s/restart_unix.go
  pkg/autopilot/controller/signal/k0s/restarted_unix.go
  pkg/autopilot/controller/signal/k0s/uncordon.go
  pkg/autopilot/controller/updates/update_controller.go
  pkg/autopilot/controller/updates/updater.go
  pkg/cleanup/services.go
  pkg/component/controller/apiendpointreconciler_test.go
  pkg/component/controller/cplb/cplb_linux.go
  pkg/component/controller/csrapprover.go
  pkg/component/controller/extensions_controller.go
  pkg/component/controller/workerconfig/reconciler.go
  pkg/component/iptables/iptables.go
  pkg/component/worker/containerd/configurer.go
  pkg/component/worker/nllb/envoy.go
  pkg/etcd/client.go
  pkg/kubernetes/lease.go
  pkg/kubernetes/watch/watcher_test.go
  pkg/supervisor/supervisor_test.go
Labels: chore

#5688 [Backport release-1.31] Bump containerd to 1.7.27
  docs/airgap-install.md
  docs/external-runtime-deps.md
  docs/nllb.md
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/worker, area/containers, chore, component/containerd, backport/release-1.30

#5737 [Backport release-1.30] Bump containerd to 1.7.27
  docs/airgap-install.md
  docs/external-runtime-deps.md
  docs/nllb.md
  docs/raspberry-pi4.md
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: area/worker, area/containers, chore, component/containerd, backport/release-1.29

#5735 Remove CGROUP kconfig checks
  docs/external-runtime-deps.md
  docs/raspberry-pi4.md
  docs/raspberry-pi5.md
  internal/pkg/sysinfo/host_linux.go
Labels: backport/release-1.30, backport/release-1.31, backport/release-1.32

#5745 Be less strict about CPLB vs. endpoint reconciler
  cmd/controller/controller.go
  docs/cplb.md
Labels: documentation, chore

#5747 Add missing k8s.io/externaljwt replace config in go.mod
  go.mod
Labels: bug, backport/release-1.32

#5738 [Backport release-1.31] Add support for setting kubelet root directory
  cmd/controller/controller_test.go
  cmd/install/controller_test.go
  cmd/install/util.go
  cmd/reset/reset.go
  docs/configuration.md
  inttest/kubeletcertrotate/kubeletcertrotate_test.go
  inttest/reset/reset_test.go
  pkg/cleanup/directories.go
  pkg/component/worker/kubelet.go
  pkg/component/worker/utils.go
  pkg/config/cfgvars.go
  pkg/config/cfgvars_test.go
  pkg/config/cli.go
Labels: enhancement, area/worker, component/kubelet, area/cli

#5754 Remove duplicate lines in the configuration.md file
  docs/configuration.md
Labels: documentation

#5757 Bump golangci-lint to v2.1.1
  hack/tools/Makefile.variables
Labels: chore

#5756 Remove "What happened to GitHub stargazers?"
  README.md
  docs/README.md
Labels: chore

#5767 Bump go to v1.23.8
  embedded-bins/Makefile.variables
Labels: backport/release-1.30, backport/release-1.31, backport/release-1.32

#5750 Remove unused stuff from konnectivity agent manifest
  pkg/component/controller/konnectivityagent.go
Labels: component/konnectivity, chore

#5782 [Backport release-1.31] Bump Ubuntu runners to 24.04
  .github/workflows/backport.yaml
  .github/workflows/build-airgap-image-bundle.yml
  .github/workflows/build-docs.yml
  .github/workflows/build-k0s.yml
  .github/workflows/check-network.yaml
  .github/workflows/commit.yaml
  .github/workflows/conflicts.yaml
  .github/workflows/dco.yaml
  .github/workflows/dependabot-prs.yaml
  .github/workflows/docs.yml
  .github/workflows/go.yml
  .github/workflows/lint.yaml
  .github/workflows/ostests-e2e.yaml
  .github/workflows/ostests-nightly.yaml
  .github/workflows/publish-docs-manual.yml
  .github/workflows/publish-docs.yml
  .github/workflows/release.yml
  .github/workflows/sbom-upload.yml
  .github/workflows/smoketest.yaml
  .github/workflows/stale.yml
Labels: area/ci, chore

#5792 Bump etcd 3.5.21
  embedded-bins/Makefile.variables
  go.mod
  go.sum
Labels: chore, backport/release-1.30, backport/release-1.31, backport/release-1.32

#5733 Deduce k0s API bind address from API server bind address
  cmd/api/api.go
Labels: area/controlplane

#5801 Use proper types on RISC-V
  internal/pkg/sysinfo/probes/linux/types_signed.go
  internal/pkg/sysinfo/probes/linux/types_unsigned.go
Labels: chore

#5797 Fix konnectivity health check in OS tests
  hack/ostests/modules/k0sctl/pre-flight-checks.sh
Labels: bug, area/ci

#5798 Update OS tests modules lock file
  hack/ostests/.terraform.lock.hcl
Labels: area/ci, chore

#5805 Fix backwards compat for debug flag handling
  cmd/airgap/airgap.go
  cmd/config/config.go
  cmd/config/create.go
  cmd/config/validate.go
  cmd/token/preshared.go
  cmd/token/token.go
Labels: bug, area/cli

#5788 Fix triggers for Oracle Linux 8 in OS tests
  .github/workflows/ostests-matrix.yaml
  .github/workflows/ostests-nightly.yaml
Labels: bug, area/ci
